import type { Locale } from "../i18n";

const en = {
  mode: "Live routes",
  title: "Continuous multi-venue routes",
  subtitle: "Operator-reviewed public feeds. Candidate discovery only — no order placement or profit guarantee.",
  refresh: "Refresh live routes",
  state: "Runtime",
  coverageStatus: "Discovery coverage",
  coverageComplete: "complete and current",
  coverageIncomplete: "incomplete",
  retainedPriorDiscovery: "showing the last successful discovery snapshot; it is not current",
  configured: "Configured",
  active: "Active",
  readyBooks: "Sequence-ready books",
  candidates: "Compatible routes",
  screened: "Market-economics rows",
  sourceHealth: "Public source health",
  sourceHealthTable: "Public source health table",
  routeCandidates: "Research candidates",
  routeCandidatesTable: "Research candidate table",
  economicsTitle: "Observed market economics",
  economicsHint: "Exact visible entry capacity and quote-equivalent public taker-fee estimates. Missing account, transfer and holding-period evidence stays blocked.",
  economicsTable: "Observed market economics table",
  economicsCount: "{shown} of {total} market-economics rows shown",
  noEconomics: "No route has enough verified public-book evidence for market economics under these filters.",
  venueFilter: "Venue filter",
  familyFilter: "Route-family filter",
  allVenues: "All venues",
  allFamilies: "All route families",
  longLeg: "Long-side instrument",
  shortLeg: "Short-side instrument",
  identity: "Reviewed identity",
  family: "Family",
  route: "Route",
  outcome: "Outcome",
  capacity: "Visible capacity",
  grossEdge: "Gross entry basis",
  entryFees: "Estimated public fees",
  netEntryEdge: "Entry basis after estimated fees",
  freshness: "Freshness",
  blockedBy: "Still blocked by",
  marketOnlyStatus: "market-only",
  blockedStatus: "blocked",
  projectedOutcome: "projected",
  maximumVisibleCapacity: "maximum visible top-book capacity",
  referenceNotional: "reference notional {value} {asset}",
  identityValidUntil: "{source} · {version} · valid until {time}",
  receiptClock: "local receipt clock",
  calibratedClock: "calibrated venue-time interval · worst-case bounds",
  permissionDenied: "orders not permitted",
  buyLeg: "buy",
  sellLeg: "sell",
  publicTakerEntryOnly: "public taker · quote-equivalent estimate",
  feeEstimateBoundary: "fee asset and exposure impact are not verified",
  staleHandoff: "Refresh this non-current or stale route before transferring it.",
  quoteAge: "age {value} ms",
  legSkew: "leg skew {value} ms",
  entryOnlyBoundary: "Entry-only screen — no account balances, transfers, borrow recall, margin, liquidation, exit basis or order permission.",
  source: "Source",
  market: "Market",
  feedState: "Feed state",
  evidence: "Evidence",
  book: "book",
  topBook: "top book",
  funding: "funding",
  noEvidence: "status only",
  noCandidates: "No compatible research routes match these filters.",
  unavailable: "Unavailable instruments",
  disabled: "The operator has not configured ARBITRAGE_CONTINUOUS_ROUTES_JSON. No public WebSocket subscriptions were started.",
  starting: "The registry and selected public feeds are starting.",
  degraded: "Some reviewed instruments failed closed. Check the reasons and source states below.",
  error: "Continuous discovery is unavailable and has failed closed.",
  live: "Continuous public discovery is live. Routes remain research-only and non-executable.",
  loading: "Loading continuous route state…",
  loadError: "Could not load continuous route state",
  lastRefresh: "Last registry refresh: {time}",
  observed: "Observed: {time}",
  researchOnly: "read-only research",
  routeCount: "{shown} of {total} routes shown",
  lifecycleTitle: "Continuous-route lifecycle",
  lifecycleHint: "Per-route confirmation and decay from public evidence. Policy-passed never means executable.",
  lifecycleRefresh: "Refresh lifecycle",
  lifecycleError: "Lifecycle is unavailable",
  lifecycleLoading: "Loading lifecycle…",
  lifecycleReadOnly: "read-only research state",
  lifecyclePermission: "execution permission",
  lifecycleNoRoutes: "No retained continuous routes.",
  lifecycleRoute: "Route",
  lifecycleStatus: "Status",
  lifecycleEvidence: "Evidence",
  lifecycleLastSeen: "Last seen",
  lifecyclePolicyPassed: "research policy passed; not an execution permission",
  lifecyclePolicyBlocked: "research policy not satisfied",
  lifecycleEvents: "Recent transitions",
  lifecycleNoEvents: "No lifecycle transitions yet.",
  lifecycleFirstSeen: "First seen",
  lifecycleConfirmed: "Confirmed",
  lifecycleDecaying: "Decaying",
  lifecycleExpired: "Expired"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  mode: "Live-маршруты",
  title: "Непрерывные межбиржевые маршруты",
  subtitle: "Проверенные оператором публичные потоки. Только поиск кандидатов — без выставления ордеров и гарантий прибыли.",
  refresh: "Обновить live-маршруты",
  state: "Состояние",
  coverageStatus: "Полнота поиска",
  coverageComplete: "полная и актуальная",
  coverageIncomplete: "неполная",
  retainedPriorDiscovery: "показан последний успешный снимок поиска; он не является актуальным",
  configured: "Настроено",
  active: "Активно",
  readyBooks: "Стаканы с проверенной последовательностью",
  candidates: "Совместимые маршруты",
  screened: "Строки рыночной экономики",
  sourceHealth: "Состояние публичных источников",
  sourceHealthTable: "Таблица состояния публичных источников",
  routeCandidates: "Исследовательские кандидаты",
  routeCandidatesTable: "Таблица исследовательских кандидатов",
  economicsTitle: "Наблюдаемая рыночная экономика",
  economicsHint: "Точная видимая ёмкость входа и оценка публичных taker-комиссий в эквиваленте котируемого актива. Отсутствующие данные счёта, переводов и горизонта остаются блокирующими.",
  economicsTable: "Таблица наблюдаемой рыночной экономики",
  economicsCount: "Показано {shown} из {total} строк рыночной экономики",
  noEconomics: "Под эти фильтры нет маршрутов с достаточным подтверждением публичных стаканов для расчёта рыночной экономики.",
  venueFilter: "Фильтр биржи",
  familyFilter: "Фильтр типа маршрута",
  allVenues: "Все биржи",
  allFamilies: "Все типы маршрутов",
  longLeg: "Инструмент длинной стороны",
  shortLeg: "Инструмент короткой стороны",
  identity: "Проверенная идентичность",
  family: "Тип",
  route: "Маршрут",
  outcome: "Результат",
  capacity: "Видимая ёмкость",
  grossEdge: "Валовой basis входа",
  entryFees: "Оценочные публичные комиссии",
  netEntryEdge: "Basis входа после оценочных комиссий",
  freshness: "Актуальность",
  blockedBy: "Остаётся заблокировано",
  marketOnlyStatus: "только рынок",
  blockedStatus: "заблокировано",
  projectedOutcome: "прогнозный",
  maximumVisibleCapacity: "максимальная видимая ёмкость верхнего уровня стакана",
  referenceNotional: "опорный объём {value} {asset}",
  identityValidUntil: "{source} · {version} · действует до {time}",
  receiptClock: "по локальному времени получения",
  calibratedClock: "калиброванный интервал времени биржи · худшие границы",
  permissionDenied: "ордера запрещены",
  buyLeg: "покупка",
  sellLeg: "продажа",
  publicTakerEntryOnly: "публичный taker · оценка в эквиваленте котируемого актива",
  feeEstimateBoundary: "актив комиссии и влияние на экспозицию не подтверждены",
  staleHandoff: "Обновите неактуальный или устаревший маршрут перед передачей.",
  quoteAge: "возраст {value} мс",
  legSkew: "перекос ног {value} мс",
  entryOnlyBoundary: "Только оценка входа — без балансов, переводов, отзыва займа, маржи, ликвидации, exit basis и права выставлять ордера.",
  source: "Источник",
  market: "Рынок",
  feedState: "Состояние потока",
  evidence: "Данные",
  book: "стакан",
  topBook: "верх стакана",
  funding: "funding",
  noEvidence: "только статус",
  noCandidates: "Под эти фильтры нет совместимых исследовательских маршрутов.",
  unavailable: "Недоступные инструменты",
  disabled: "Оператор не настроил ARBITRAGE_CONTINUOUS_ROUTES_JSON. Подписки на публичные WebSocket не запускались.",
  starting: "Реестр и выбранные публичные потоки запускаются.",
  degraded: "Часть проверенных инструментов безопасно исключена. Причины и состояния источников указаны ниже.",
  error: "Непрерывный поиск недоступен и безопасно остановлен.",
  live: "Непрерывный публичный поиск работает. Маршруты остаются исследовательскими и неисполняемыми.",
  loading: "Загружаем состояние live-маршрутов…",
  loadError: "Не удалось загрузить состояние live-маршрутов",
  lastRefresh: "Последнее обновление реестра: {time}",
  observed: "Снимок: {time}",
  researchOnly: "исследование только для чтения",
  routeCount: "Показано {shown} из {total} маршрутов",
  lifecycleTitle: "Жизненный цикл live-маршрутов",
  lifecycleHint: "Подтверждение и затухание каждого маршрута по публичным данным. Прохождение политики не означает исполнимость.",
  lifecycleRefresh: "Обновить lifecycle",
  lifecycleError: "Lifecycle недоступен",
  lifecycleLoading: "Загружаем lifecycle…",
  lifecycleReadOnly: "исследовательское состояние только для чтения",
  lifecyclePermission: "право исполнения",
  lifecycleNoRoutes: "Сохранённых live-маршрутов нет.",
  lifecycleRoute: "Маршрут",
  lifecycleStatus: "Статус",
  lifecycleEvidence: "Доказательства",
  lifecycleLastSeen: "Последнее наблюдение",
  lifecyclePolicyPassed: "исследовательская политика пройдена; это не право исполнения",
  lifecyclePolicyBlocked: "исследовательская политика не пройдена",
  lifecycleEvents: "Последние переходы",
  lifecycleNoEvents: "Переходов lifecycle пока нет.",
  lifecycleFirstSeen: "Впервые замечен",
  lifecycleConfirmed: "Подтверждён",
  lifecycleDecaying: "Затухает",
  lifecycleExpired: "Истёк"
};

const kk: Record<Key, string> = {
  mode: "Live бағыттар",
  title: "Үздіксіз көпбиржалық бағыттар",
  subtitle: "Оператор тексерген ашық ағындар. Тек кандидаттарды іздеу — ордер жібермейді және пайдаға кепілдік бермейді.",
  refresh: "Live бағыттарды жаңарту",
  state: "Күйі",
  coverageStatus: "Іздеу толықтығы",
  coverageComplete: "толық және өзекті",
  coverageIncomplete: "толық емес",
  retainedPriorDiscovery: "соңғы сәтті іздеу суреті көрсетілді; ол өзекті емес",
  configured: "Бапталған",
  active: "Белсенді",
  readyBooks: "Реті расталған стакандар",
  candidates: "Үйлесімді бағыттар",
  screened: "Нарық экономикасы жолдары",
  sourceHealth: "Ашық дереккөздер күйі",
  sourceHealthTable: "Ашық дереккөздер күйінің кестесі",
  routeCandidates: "Зерттеу кандидаттары",
  routeCandidatesTable: "Зерттеу кандидаттарының кестесі",
  economicsTitle: "Бақыланатын нарық экономикасы",
  economicsHint: "Көрінетін кіру сыйымдылығы дәл есептеледі, ал ашық taker комиссиясы баға белгілеу активінің баламасы ретінде бағаланады. Шот, аударым және ұстау мерзімі дәлелі жоқ болса, бағыт бұғатталған күйде қалады.",
  economicsTable: "Бақыланатын нарық экономикасының кестесі",
  economicsCount: "{total} нарық экономикасы жолының {shown} көрсетілді",
  noEconomics: "Бұл сүзгілер бойынша нарық экономикасына жеткілікті расталған ашық стакан дәлелі бар бағыт жоқ.",
  venueFilter: "Биржа сүзгісі",
  familyFilter: "Бағыт түрінің сүзгісі",
  allVenues: "Барлық биржа",
  allFamilies: "Барлық бағыт түрі",
  longLeg: "Long жағының құралы",
  shortLeg: "Short жағының құралы",
  identity: "Тексерілген сәйкестік",
  family: "Түрі",
  route: "Бағыт",
  outcome: "Нәтиже",
  capacity: "Көрінетін сыйымдылық",
  grossEdge: "Жалпы кіру basis-і",
  entryFees: "Бағаланған ашық комиссиялар",
  netEntryEdge: "Бағаланған комиссиядан кейінгі кіру basis-і",
  freshness: "Жаңалығы",
  blockedBy: "Әлі бұғаттайтын дәлел",
  marketOnlyStatus: "тек нарық",
  blockedStatus: "бұғатталған",
  projectedOutcome: "болжамды",
  maximumVisibleCapacity: "стакан төбесінде көрінетін ең жоғары сыйымдылық",
  referenceNotional: "тірек көлемі {value} {asset}",
  identityValidUntil: "{source} · {version} · {time} дейін жарамды",
  receiptClock: "жергілікті қабылдау уақыты бойынша",
  calibratedClock: "биржа уақытының калибрленген аралығы · ең нашар шектер",
  permissionDenied: "ордерлерге рұқсат жоқ",
  buyLeg: "сатып алу",
  sellLeg: "сату",
  publicTakerEntryOnly: "ашық taker · баға белгілеу активінің балама бағасы",
  feeEstimateBoundary: "комиссия активі мен экспозицияға әсері расталмаған",
  staleHandoff: "Беруден бұрын өзекті емес немесе ескірген бағытты жаңартыңыз.",
  quoteAge: "жасы {value} мс",
  legSkew: "аяқ ауытқуы {value} мс",
  entryOnlyBoundary: "Тек кіру бағасы — шот балансы, аударым, қарызды кері шақыру, маржа, жойылу, exit basis және ордер құқығы жоқ.",
  source: "Дереккөз",
  market: "Нарық",
  feedState: "Ағын күйі",
  evidence: "Дәлел",
  book: "стакан",
  topBook: "стакан төбесі",
  funding: "funding",
  noEvidence: "тек күйі",
  noCandidates: "Бұл сүзгілерге сәйкес зерттеу бағыты жоқ.",
  unavailable: "Қолжетімсіз құралдар",
  disabled: "Оператор ARBITRAGE_CONTINUOUS_ROUTES_JSON параметрін баптамаған. Ашық WebSocket жазылымдары іске қосылмады.",
  starting: "Реестр және таңдалған ашық ағындар іске қосылуда.",
  degraded: "Кейбір тексерілген құралдар қауіпсіз түрде алынып тасталды. Себептері мен ағын күйлері төменде көрсетілген.",
  error: "Үздіксіз іздеу қолжетімсіз және қауіпсіз тоқтатылды.",
  live: "Үздіксіз ашық іздеу жұмыс істейді. Бағыттар тек зерттеуге арналған және орындалмайды.",
  loading: "Live бағыттар күйі жүктелуде…",
  loadError: "Live бағыттар күйін жүктеу мүмкін болмады",
  lastRefresh: "Реестрдің соңғы жаңартылуы: {time}",
  observed: "Бақыланған уақыты: {time}",
  researchOnly: "тек оқуға арналған зерттеу",
  routeCount: "{total} бағыттың {shown} көрсетілді",
  lifecycleTitle: "Live бағыттардың өмірлік циклі",
  lifecycleHint: "Ашық дәлел бойынша әр бағытты растау және әлсірету. Policy өтуі орындалатынын білдірмейді.",
  lifecycleRefresh: "Lifecycle жаңарту",
  lifecycleError: "Lifecycle қолжетімсіз",
  lifecycleLoading: "Lifecycle жүктелуде…",
  lifecycleReadOnly: "тек оқуға арналған зерттеу күйі",
  lifecyclePermission: "орындау рұқсаты",
  lifecycleNoRoutes: "Сақталған live бағыт жоқ.",
  lifecycleRoute: "Бағыт",
  lifecycleStatus: "Күйі",
  lifecycleEvidence: "Дәлел",
  lifecycleLastSeen: "Соңғы бақылау",
  lifecyclePolicyPassed: "зерттеу policy-і өтті; бұл орындау рұқсаты емес",
  lifecyclePolicyBlocked: "зерттеу policy-і орындалмады",
  lifecycleEvents: "Соңғы ауысулар",
  lifecycleNoEvents: "Lifecycle ауысуы әлі жоқ.",
  lifecycleFirstSeen: "Алғаш байқалды",
  lifecycleConfirmed: "Расталды",
  lifecycleDecaying: "Әлсіреуде",
  lifecycleExpired: "Мерзімі өтті"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function continuousRoutesText(locale: Locale, key: Key, values: Record<string, string> = {}) {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, value), messages[locale][key]);
}

const coverageReasonEn = {
  complete: "all configured instruments were evaluated from the current registry refresh",
  "configuration-disabled": "continuous discovery is not configured",
  "configuration-invalid": "operator configuration is invalid",
  "refresh-pending": "the first registry refresh is still pending",
  "refresh-failed": "the latest registry refresh failed",
  "partial-instruments": "one or more configured instruments failed closed"
} as const;

type CoverageReasonKey = keyof typeof coverageReasonEn;

const coverageReasonText: Record<Locale, Record<CoverageReasonKey, string>> = {
  en: coverageReasonEn,
  ru: {
    complete: "все настроенные инструменты проверены по текущему обновлению реестра",
    "configuration-disabled": "непрерывный поиск не настроен",
    "configuration-invalid": "конфигурация оператора некорректна",
    "refresh-pending": "ожидается первое обновление реестра",
    "refresh-failed": "последнее обновление реестра завершилось ошибкой",
    "partial-instruments": "один или несколько настроенных инструментов безопасно исключены"
  },
  kk: {
    complete: "барлық бапталған құрал ағымдағы реестр жаңартуымен тексерілді",
    "configuration-disabled": "үздіксіз іздеу бапталмаған",
    "configuration-invalid": "оператор конфигурациясы қате",
    "refresh-pending": "реестрдің алғашқы жаңартуы күтілуде",
    "refresh-failed": "реестрдің соңғы жаңартуы сәтсіз аяқталды",
    "partial-instruments": "бір немесе бірнеше бапталған құрал қауіпсіз түрде алынып тасталды"
  }
};

export function continuousCoverageReasonText(locale: Locale, key: CoverageReasonKey) {
  return coverageReasonText[locale][key];
}

const blockReasonEn = {
  "missing-instrument": "normalized instrument metadata is missing",
  "missing-top-book": "verified top-book data is missing",
  "feed-not-live": "public feed is not live",
  "generation-mismatch": "book and live-feed generations do not match",
  "invalid-top-book": "top-book identity or values are invalid",
  "unverified-continuity": "sequence or checksum continuity is not verified",
  "stale-top-book": "top-book data is stale",
  "future-top-book": "top-book time exceeds the future-clock boundary",
  "expiry-boundary": "dated future is at or beyond expiry",
  "skewed-top-books": "cross-leg receipt skew is too large",
  "quantity-unit-mismatch": "book and instrument quantity units do not match",
  "unsupported-quantity-precision": "quantity precision cannot be aligned exactly",
  "no-common-quantity": "the two top books have no common step-aligned quantity",
  "minimum-quantity": "visible quantity is below a venue minimum",
  "minimum-notional": "visible notional is below a venue minimum",
  "derived-arithmetic-invalid": "derived entry arithmetic is non-finite or outside safe bounds",
  "economic-identity-not-yet-valid": "reviewed economic identity is not valid yet",
  "economic-identity-expired": "reviewed economic identity has expired",
  "economic-identity-invalid": "economic identity provenance is malformed or inconsistent",
  "clock-unavailable": "venue clock calibration is unavailable",
  "clock-not-calibrated": "venue clock calibration is degraded or expired",
  "timestamp-definitely-future": "the calibrated timestamp is definitely beyond the future boundary",
  "timestamp-may-be-future": "clock uncertainty allows the timestamp to exceed the future boundary",
  "timestamp-stale": "the worst-case calibrated timestamp age is stale",
  "clock-skew-exceeded": "worst-case calibrated leg skew exceeds the limit",
  "account-capital-missing": "verified account capital is missing",
  "account-inventory-missing": "verified sell-side inventory is missing",
  "network-rebalance-missing": "network availability, fees and rebalance proof are missing",
  "borrow-evidence-missing": "verified borrow capacity, rate and horizon are missing",
  "funding-horizon-missing": "verified full-horizon funding is missing",
  "derivative-margin-missing": "verified margin and collateral are missing",
  "convergence-evidence-missing": "convergence and exit-cost evidence are missing",
  "expiry-delivery-evidence-missing": "expiry, close or delivery evidence is missing"
} as const;

type BlockReasonKey = keyof typeof blockReasonEn;

const blockReasonText: Record<Locale, Record<BlockReasonKey, string>> = {
  en: blockReasonEn,
  ru: {
    "missing-instrument": "нет нормализованных данных инструмента",
    "missing-top-book": "нет проверенного верхнего уровня стакана",
    "feed-not-live": "публичный поток не в состоянии live",
    "generation-mismatch": "поколения стакана и live-потока не совпадают",
    "invalid-top-book": "неверна идентичность или значения верхнего уровня стакана",
    "unverified-continuity": "не подтверждена непрерывность sequence/checksum",
    "stale-top-book": "верхний уровень стакана устарел",
    "future-top-book": "время стакана выходит за допустимую границу будущего",
    "expiry-boundary": "срочный контракт достиг или прошёл экспирацию",
    "skewed-top-books": "слишком велик разрыв времени получения между ногами",
    "quantity-unit-mismatch": "единицы количества стакана и инструмента не совпадают",
    "unsupported-quantity-precision": "невозможно точно согласовать точность количества",
    "no-common-quantity": "у двух стаканов нет общего количества, кратного шагам",
    "minimum-quantity": "видимое количество ниже минимума биржи",
    "minimum-notional": "видимый объём ниже минимального нотионала биржи",
    "derived-arithmetic-invalid": "производная арифметика входа не конечна или вышла за безопасные границы",
    "economic-identity-not-yet-valid": "проверенная экономическая идентичность ещё не вступила в силу",
    "economic-identity-expired": "срок проверенной экономической идентичности истёк",
    "economic-identity-invalid": "источник экономической идентичности повреждён или несогласован",
    "clock-unavailable": "калибровка часов биржи недоступна",
    "clock-not-calibrated": "калибровка часов биржи ухудшена или истекла",
    "timestamp-definitely-future": "калиброванная метка времени точно выходит за границу будущего",
    "timestamp-may-be-future": "неопределённость часов допускает выход метки за границу будущего",
    "timestamp-stale": "возраст калиброванной метки в худшем случае превышает лимит",
    "clock-skew-exceeded": "перекос ног по калиброванным интервалам в худшем случае превышает лимит",
    "account-capital-missing": "нет подтверждённого капитала на счёте",
    "account-inventory-missing": "нет подтверждённого актива для продажи",
    "network-rebalance-missing": "нет данных сети, комиссий и доказательства ребалансировки",
    "borrow-evidence-missing": "нет подтверждённых объёма, ставки и срока займа",
    "funding-horizon-missing": "нет подтверждённого funding на всём горизонте",
    "derivative-margin-missing": "нет подтверждённых маржи и обеспечения",
    "convergence-evidence-missing": "нет доказательств схождения и стоимости выхода",
    "expiry-delivery-evidence-missing": "нет доказательств экспирации, закрытия или поставки"
  },
  kk: {
    "missing-instrument": "құралдың қалыпқа келтірілген деректері жоқ",
    "missing-top-book": "стакан төбесінің расталған дерегі жоқ",
    "feed-not-live": "ашық ағын live күйінде емес",
    "generation-mismatch": "стакан мен live ағын буындары сәйкес емес",
    "invalid-top-book": "стакан төбесінің сәйкестігі немесе мәндері қате",
    "unverified-continuity": "sequence/checksum үздіксіздігі расталмаған",
    "stale-top-book": "стакан төбесінің дерегі ескірген",
    "future-top-book": "стакан уақыты рұқсат етілген болашақ шегінен асты",
    "expiry-boundary": "мерзімді фьючерс экспирацияға жетті немесе одан өтті",
    "skewed-top-books": "аяқтарды қабылдау уақыттарының айырмасы тым үлкен",
    "quantity-unit-mismatch": "стакан мен құрал санының бірліктері сәйкес емес",
    "unsupported-quantity-precision": "сан дәлдігін нақты сәйкестендіру мүмкін емес",
    "no-common-quantity": "екі стаканда қадамдарға сай ортақ сан жоқ",
    "minimum-quantity": "көрінетін сан биржа минимумынан төмен",
    "minimum-notional": "көрінетін көлем биржа минимумынан төмен",
    "derived-arithmetic-invalid": "туынды кіру арифметикасы шекті емес немесе қауіпсіз шектен шықты",
    "economic-identity-not-yet-valid": "тексерілген экономикалық сәйкестік әлі күшіне енбеген",
    "economic-identity-expired": "тексерілген экономикалық сәйкестіктің мерзімі өтті",
    "economic-identity-invalid": "экономикалық сәйкестік дереккөзі қате немесе үйлесімсіз",
    "clock-unavailable": "биржа сағатының калибрлеуі қолжетімсіз",
    "clock-not-calibrated": "биржа сағатының калибрлеуі нашарлаған немесе мерзімі өткен",
    "timestamp-definitely-future": "калибрленген уақыт белгісі болашақ шегінен анық асып тұр",
    "timestamp-may-be-future": "сағат белгісіздігі уақыт белгісінің болашақ шегінен асуына жол береді",
    "timestamp-stale": "калибрленген уақыт белгісінің ең нашар жасы шектен асты",
    "clock-skew-exceeded": "калибрленген аралықтар бойынша аяқтардың ең нашар ығысуы шектен асты",
    "account-capital-missing": "шоттағы расталған капитал жоқ",
    "account-inventory-missing": "сатуға арналған расталған актив жоқ",
    "network-rebalance-missing": "желі, комиссия және қайта теңгеру дәлелі жоқ",
    "borrow-evidence-missing": "қарыз көлемі, мөлшерлемесі және мерзімі расталмаған",
    "funding-horizon-missing": "бүкіл мерзімдегі funding расталмаған",
    "derivative-margin-missing": "маржа мен кепіл расталмаған",
    "convergence-evidence-missing": "жақындасу мен шығу құны дәлелденбеген",
    "expiry-delivery-evidence-missing": "экспирация, жабу немесе жеткізу дәлелі жоқ"
  }
};

export function continuousBlockReasonText(locale: Locale, key: BlockReasonKey) {
  return blockReasonText[locale][key];
}
