import type { Locale } from "../i18n";

const en = {
  title: "Continuous WebSocket diagnostics",
  hint: "Read-only public-feed transport evidence. Protocol-ready means fresh same-generation book continuity only — not a route, economics, or execution permission.",
  table: "Continuous WebSocket diagnostics table",
  loading: "Loading WebSocket diagnostics…",
  error: "WebSocket diagnostics are unavailable",
  empty: "No operator-configured continuous stream is active.",
  streams: "Streams",
  healthyStreams: "Healthy",
  reconnecting: "Reconnecting",
  bookContinuityReady: "Protocol-ready books",
  source: "Source",
  market: "Market",
  transport: "Transport",
  generation: "Generation / reconnects",
  continuity: "Continuity proof",
  lastReceive: "Last receive",
  readiness: "Book continuity",
  reconnectScheduled: "reconnect scheduled",
  reconnectsObserved: "{value} observed restarts",
  sequence: "sequence {value}",
  checksum: "checksum {value}",
  noContinuity: "no book continuity proof",
  noReceive: "no market-data receive yet",
  receivedAgo: "{value} ms ago",
  currentGeneration: "current generation",
  staleGeneration: "generation mismatch",
  fresh: "fresh",
  stale: "stale",
  ready: "protocol-ready",
  notReady: "not protocol-ready",
  idle: "idle",
  healthy: "healthy",
  degraded: "degraded",
  unhealthy: "unhealthy"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  title: "Диагностика непрерывных WebSocket-потоков",
  hint: "Только чтение данных публичного транспорта. «Готов по протоколу» означает лишь свежую непрерывность стакана в текущем поколении, а не готовый маршрут, экономику или разрешение на исполнение.",
  table: "Таблица диагностики непрерывных WebSocket-потоков",
  loading: "Загрузка диагностики WebSocket…",
  error: "Диагностика WebSocket недоступна",
  empty: "Нет активных непрерывных потоков, настроенных оператором.",
  streams: "Потоки",
  healthyStreams: "Исправны",
  reconnecting: "Переподключаются",
  bookContinuityReady: "Стаканы готовы по протоколу",
  source: "Источник",
  market: "Рынок",
  transport: "Транспорт",
  generation: "Поколение / переподключения",
  continuity: "Доказательство непрерывности",
  lastReceive: "Последнее получение",
  readiness: "Непрерывность стакана",
  reconnectScheduled: "переподключение запланировано",
  reconnectsObserved: "зафиксировано перезапусков: {value}",
  sequence: "последовательность {value}",
  checksum: "контрольная сумма {value}",
  noContinuity: "нет доказательства непрерывности стакана",
  noReceive: "рыночные данные ещё не получены",
  receivedAgo: "{value} мс назад",
  currentGeneration: "текущее поколение",
  staleGeneration: "поколения не совпадают",
  fresh: "свежие данные",
  stale: "устаревшие данные",
  ready: "готов по протоколу",
  notReady: "не готов по протоколу",
  idle: "простаивает",
  healthy: "исправно",
  degraded: "частично доступно",
  unhealthy: "неисправно"
};

const kk: Record<Key, string> = {
  title: "Үздіксіз WebSocket ағындарының диагностикасы",
  hint: "Ашық тасымал дәлелдерін тек оқу. «Протокол бойынша дайын» тек ағымдағы буындағы жаңа стакан үздіксіздігін білдіреді; бұл дайын бағыт, экономика немесе орындау рұқсаты емес.",
  table: "Үздіксіз WebSocket ағындары диагностикасының кестесі",
  loading: "WebSocket диагностикасы жүктелуде…",
  error: "WebSocket диагностикасы қолжетімсіз",
  empty: "Оператор баптаған белсенді үздіксіз ағын жоқ.",
  streams: "Ағындар",
  healthyStreams: "Дұрыс",
  reconnecting: "Қайта қосылуда",
  bookContinuityReady: "Стакан протокол бойынша дайын",
  source: "Дереккөз",
  market: "Нарық",
  transport: "Тасымал",
  generation: "Буын / қайта қосылу",
  continuity: "Үздіксіздік дәлелі",
  lastReceive: "Соңғы қабылдау",
  readiness: "Стакан үздіксіздігі",
  reconnectScheduled: "қайта қосылу жоспарланған",
  reconnectsObserved: "байқалған қайта қосылу: {value}",
  sequence: "реттік нөмір {value}",
  checksum: "бақылау сомасы {value}",
  noContinuity: "стакан үздіксіздігінің дәлелі жоқ",
  noReceive: "нарық дерегі әлі қабылданбаған",
  receivedAgo: "{value} мс бұрын",
  currentGeneration: "ағымдағы буын",
  staleGeneration: "буындар сәйкес емес",
  fresh: "жаңа дерек",
  stale: "ескірген дерек",
  ready: "протокол бойынша дайын",
  notReady: "протокол бойынша дайын емес",
  idle: "бос",
  healthy: "дұрыс",
  degraded: "ішінара қолжетімді",
  unhealthy: "ақаулы"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function continuousFeedHealthText(locale: Locale, key: Key, values: Record<string, string> = {}) {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, value), messages[locale][key]);
}
