import type { Locale } from "../i18n";

const en = {
  mode: "Funding stress",
  eyebrow: "Public perpetual funding · point in time",
  title: "Funding curve scenario lab",
  description: "Projects verified discrete funding settlements for selected perpetuals and compares additive stress scenarios. It never reads an account or places an order.",
  universe: "Funding instruments",
  universeHint: "Choose fresh trading perpetuals from the server-owned funding adapter allowlist. Unsupported venues are never offered; a supported adapter can still reject an unverified schedule.",
  instrument: "Instrument {index}",
  chooseInstrument: "Choose a perpetual",
  addInstrument: "Add instrument",
  removeInstrument: "Remove instrument {index}",
  horizon: "Projection horizon",
  horizonHours: "hours",
  stress: "Stress per settlement",
  stressUnit: "bp",
  run: "Build funding curve",
  running: "Building curve…",
  loadingUniverse: "Loading the verified instrument registry…",
  universeUnavailable: "The public instrument registry is temporarily unavailable.",
  noFundingInstruments: "No fresh perpetual instruments with public funding capability are available.",
  requestUnavailable: "The funding curve is temporarily unavailable.",
  partialUniverse: "Some registry sources are unavailable; only verified fresh instruments are shown.",
  curveResults: "Point-in-time funding scenarios",
  route: "Venue / instrument",
  currentRate: "Current rate",
  interval: "Verified interval",
  settlements: "Settlements",
  baseScenario: "Base cumulative",
  downsideScenario: "Stress −{value} bp",
  upsideScenario: "Stress +{value} bp",
  freshness: "Source age",
  minutes: "min",
  milliseconds: "ms",
  clockCalibrated: "calibrated venue-time interval",
  clockFallback: "local receipt fallback · not cross-venue comparable",
  clockComparisonCalibrationBlocked: "Cross-venue funding-gap comparison is blocked: at least one venue clock is unavailable, degraded or expired.",
  clockComparisonSkewBlocked: "Cross-venue funding-gap comparison is blocked: worst-case calibrated timestamp skew exceeds the limit.",
  history: "history {count}",
  noCurves: "No selected instrument produced a verified discrete curve.",
  rejections: "Fail-closed results",
  retryable: "retryable",
  final: "final for this source",
  gapTitle: "Largest reviewed funding-rate gap",
  gapValue: "{value} bp over the selected horizon",
  gapRoute: "Long lower rate: {long} · short higher rate: {short}",
  gapHint: "This compares only instruments sharing an exact reviewed economic identity. It excludes entry/exit basis, fees, margin, liquidation, borrow and execution risk.",
  signConvention: "Positive funding means longs pay shorts.",
  boundary: "Read-only research. The curve persists the latest public estimate between known settlements; it is not a forecast or P&L. No credentials, balances, notional or orders are accepted."
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  mode: "Funding-сценарии",
  eyebrow: "Публичный funding perpetual · точка во времени",
  title: "Лаборатория funding-кривой",
  description: "Проецирует подтверждённые дискретные funding-расчёты выбранных perpetual и сравнивает аддитивные стресс-сценарии. Аккаунт не читается, ордера не отправляются.",
  universe: "Funding-инструменты",
  universeHint: "Выберите свежие торгуемые perpetual из серверного allowlist funding-адаптеров. Неподдерживаемые биржи не предлагаются; поддерживаемый адаптер всё равно отклонит неподтверждённое расписание.",
  instrument: "Инструмент {index}",
  chooseInstrument: "Выберите perpetual",
  addInstrument: "Добавить инструмент",
  removeInstrument: "Удалить инструмент {index}",
  horizon: "Горизонт расчёта",
  horizonHours: "часов",
  stress: "Стресс на один расчёт",
  stressUnit: "б.п.",
  run: "Построить funding-кривую",
  running: "Кривая строится…",
  loadingUniverse: "Загружается проверенный реестр инструментов…",
  universeUnavailable: "Публичный реестр инструментов временно недоступен.",
  noFundingInstruments: "Нет свежих perpetual-инструментов с публичной funding-возможностью.",
  requestUnavailable: "Funding-кривая временно недоступна.",
  partialUniverse: "Часть источников реестра недоступна; показаны только свежие подтверждённые инструменты.",
  curveResults: "Funding-сценарии в выбранной точке времени",
  route: "Биржа / инструмент",
  currentRate: "Текущая ставка",
  interval: "Подтверждённый интервал",
  settlements: "Расчётов",
  baseScenario: "Базовая сумма",
  downsideScenario: "Стресс −{value} б.п.",
  upsideScenario: "Стресс +{value} б.п.",
  freshness: "Возраст источника",
  minutes: "мин",
  milliseconds: "мс",
  clockCalibrated: "калиброванный интервал времени биржи",
  clockFallback: "fallback по локальному получению · межбиржевое сравнение запрещено",
  clockComparisonCalibrationBlocked: "Межбиржевое сравнение funding-разницы заблокировано: часы хотя бы одной биржи недоступны, ухудшены или просрочены.",
  clockComparisonSkewBlocked: "Межбиржевое сравнение funding-разницы заблокировано: худший перекос калиброванных меток превышает лимит.",
  history: "история {count}",
  noCurves: "Ни один выбранный инструмент не дал подтверждённую дискретную кривую.",
  rejections: "Fail-closed результаты",
  retryable: "можно повторить",
  final: "итог для этого источника",
  gapTitle: "Наибольшая разница funding по проверенной identity",
  gapValue: "{value} б.п. за выбранный горизонт",
  gapRoute: "Long с меньшей ставкой: {long} · short с большей: {short}",
  gapHint: "Сравниваются только инструменты с одной точной проверенной economic identity. Не учтены basis входа/выхода, комиссии, маржа, ликвидация, borrow и риск исполнения.",
  signConvention: "Положительный funding означает: long платит short.",
  boundary: "Только read-only исследование. Между известными расчётами сохраняется последняя публичная оценка; это не прогноз и не P&L. Ключи, балансы, notional и ордера не принимаются."
};

const kk: Record<Key, string> = {
  mode: "Funding сценарийлері",
  eyebrow: "Ашық perpetual funding · уақыт нүктесі",
  title: "Funding curve сценарий зертханасы",
  description: "Таңдалған perpetual үшін расталған discrete funding settlement-терін жобалап, additive stress сценарийлерін салыстырады. Account оқымайды және order жібермейді.",
  universe: "Funding құралдары",
  universeHint: "Сервердің funding adapter allowlist-індегі fresh trading perpetual құралдарын таңдаңыз. Қолдау жоқ биржалар ұсынылмайды; schedule расталмаса, қолдаулы adapter оны қабылдамайды.",
  instrument: "{index}-құрал",
  chooseInstrument: "Perpetual таңдаңыз",
  addInstrument: "Құрал қосу",
  removeInstrument: "{index}-құралды өшіру",
  horizon: "Есеп көкжиегі",
  horizonHours: "сағат",
  stress: "Әр settlement stress-і",
  stressUnit: "б.п.",
  run: "Funding curve құру",
  running: "Curve құрылуда…",
  loadingUniverse: "Тексерілген құралдар реестрі жүктелуде…",
  universeUnavailable: "Ашық құралдар реестрі уақытша қолжетімсіз.",
  noFundingInstruments: "Public funding мүмкіндігі бар fresh perpetual құралдары жоқ.",
  requestUnavailable: "Funding curve уақытша қолжетімсіз.",
  partialUniverse: "Реестрдің кейбір source-тары қолжетімсіз; тек fresh тексерілген құралдар көрсетілді.",
  curveResults: "Уақыт нүктесіндегі funding сценарийлері",
  route: "Биржа / құрал",
  currentRate: "Қазіргі мөлшерлеме",
  interval: "Расталған аралық",
  settlements: "Settlement саны",
  baseScenario: "Base жиынтығы",
  downsideScenario: "Stress −{value} б.п.",
  upsideScenario: "Stress +{value} б.п.",
  freshness: "Source жасы",
  minutes: "мин",
  milliseconds: "мс",
  clockCalibrated: "биржа уақытының калибрленген аралығы",
  clockFallback: "жергілікті қабылдау fallback-ы · биржааралық салыстыруға болмайды",
  clockComparisonCalibrationBlocked: "Биржааралық funding айырмасын салыстыру бұғатталды: кемінде бір биржа сағаты қолжетімсіз, нашарлаған немесе мерзімі өткен.",
  clockComparisonSkewBlocked: "Биржааралық funding айырмасын салыстыру бұғатталды: калибрленген уақыт белгілерінің ең нашар ығысуы шектен асты.",
  history: "history {count}",
  noCurves: "Таңдалған құралдардың ешқайсысы расталған discrete curve бермеді.",
  rejections: "Fail-closed нәтижелер",
  retryable: "қайталауға болады",
  final: "осы source үшін соңғы",
  gapTitle: "Расталған identity бойынша ең үлкен funding айырмасы",
  gapValue: "таңдалған көкжиекте {value} б.п.",
  gapRoute: "Төмен мөлшерлемелі long: {long} · жоғары мөлшерлемелі short: {short}",
  gapHint: "Тек exact reviewed economic identity бірдей құралдар салыстырылады. Entry/exit basis, комиссия, margin, liquidation, borrow және execution тәуекелі кірмейді.",
  signConvention: "Оң funding кезінде long short-қа төлейді.",
  boundary: "Тек read-only зерттеу. Белгілі settlement аралығында соңғы public estimate сақталады; бұл forecast немесе P&L емес. Key, balance, notional және order қабылданбайды."
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function fundingCurveText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}
