import type { Locale } from "../i18n";

const en = {
  mode: "Bybit native spreads",
  eyebrow: "Bybit · Spread Trading · public API",
  title: "Bybit venue-native spread book",
  description: "Reads Bybit's own two-leg combination instruments and executable top of book. Quotes are venue-native, read-only and are not presented as guaranteed profit.",
  product: "Combination type",
  allProducts: "All types",
  baseCoin: "Base asset",
  anyBase: "Any",
  minimumSize: "Minimum size",
  ranking: "Ranking",
  capacity: "Available size",
  tightness: "Tightest book",
  freshness: "Freshest quote",
  candidates: "Max books",
  scan: "Read books",
  scanning: "Reading…",
  scannerUnavailable: "The native spread scanner is temporarily unavailable.",
  instruments: "Instruments",
  eligible: "Eligible",
  checked: "Books checked",
  healthy: "Healthy books",
  results: "Venue-native two-leg combination quotes",
  updated: "Updated",
  combination: "Combination",
  legs: "Legs",
  bid: "Best bid",
  ask: "Best ask",
  width: "Book width",
  size: "Two-sided size",
  rules: "Venue rules",
  quality: "Quality",
  charts: "Charts",
  actions: "Actions",
  chart: "Open {symbol} chart",
  age: "age {value} ms",
  relativeWidth: "{value} bp",
  step: "step {value}",
  minimum: "min {value}",
  restTopBook: "REST top book",
  noResults: "No fresh two-sided spread books match these filters.",
  noResultsHint: "An empty result means the scanner refused stale, one-sided or malformed data.",
  partial: "Only part of the eligible instrument universe was queried. Increase the book limit to widen coverage.",
  sourceErrors: "Some books were rejected ({count}).",
  sourceErrorItem: "Rejected source book {index}.",
  staleHandoff: "Refresh this stale native spread quote before transferring it.",
  riskTitle: "Native book is not guaranteed profit",
  risk: "Bid and ask are prices of Bybit's combination instrument, not a precomputed ROI. Fees, collateral, account eligibility, price movement and partial fills still matter. Revalidate the instrument and book immediately before any order.",
  FundingRateArb: "Perpetual + spot",
  CarryTrade: "Dated future + spot",
  FutureSpread: "Calendar futures",
  PerpBasis: "Future + perpetual",
  LinearPerpetual: "perpetual",
  LinearFutures: "future",
  Spot: "spot"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  mode: "Нативные спреды Bybit",
  eyebrow: "Bybit · спред-торговля · публичный API",
  title: "Нативный стакан спредов Bybit",
  description: "Читает собственные двухногие комбинации Bybit и исполнимый top of book. Котировки биржевые, только для чтения и не выдаются за гарантированную прибыль.",
  product: "Тип комбинации",
  allProducts: "Все типы",
  baseCoin: "Базовый актив",
  anyBase: "Любой",
  minimumSize: "Минимальный размер",
  ranking: "Сортировка",
  capacity: "Доступный объём",
  tightness: "Узкий стакан",
  freshness: "Свежая котировка",
  candidates: "Макс. стаканов",
  scan: "Прочитать стаканы",
  scanning: "Чтение…",
  scannerUnavailable: "Скринер нативных спредов временно недоступен.",
  instruments: "Инструментов",
  eligible: "Подходит",
  checked: "Проверено стаканов",
  healthy: "Корректных стаканов",
  results: "Биржевые котировки двухногих комбинаций",
  updated: "Обновлено",
  combination: "Комбинация",
  legs: "Ноги",
  bid: "Лучший bid",
  ask: "Лучший ask",
  width: "Ширина стакана",
  size: "Двусторонний объём",
  rules: "Правила биржи",
  quality: "Качество",
  charts: "Графики",
  actions: "Действия",
  chart: "Открыть график {symbol}",
  age: "возраст {value} мс",
  relativeWidth: "{value} б.п.",
  step: "шаг {value}",
  minimum: "мин. {value}",
  restTopBook: "REST: лучшая цена",
  noResults: "По фильтрам нет свежих двусторонних стаканов.",
  noResultsHint: "Пустой результат означает, что скринер отбросил устаревшие, односторонние или некорректные данные.",
  partial: "Запрошена только часть подходящих инструментов. Увеличьте лимит стаканов для более широкого покрытия.",
  sourceErrors: "Часть стаканов отклонена ({count}).",
  sourceErrorItem: "Отклонён исходный стакан {index}.",
  staleHandoff: "Обновите устаревшую котировку нативного спреда перед передачей.",
  riskTitle: "Нативный стакан не равен гарантированной прибыли",
  risk: "Bid и ask — цены комбинированного инструмента Bybit, а не рассчитанный ROI. Важны комиссии, обеспечение, доступность аккаунту, движение цены и частичное исполнение. Перед ордером перепроверьте инструмент и стакан.",
  FundingRateArb: "Perpetual + спот",
  CarryTrade: "Срочный фьючерс + спот",
  FutureSpread: "Календарные фьючерсы",
  PerpBasis: "Фьючерс + perpetual",
  LinearPerpetual: "perpetual",
  LinearFutures: "фьючерс",
  Spot: "спот"
};

const kk: Record<Key, string> = {
  mode: "Bybit нативті спредтері",
  eyebrow: "Bybit · спред саудасы · ашық API",
  title: "Bybit нативті спред стаканы",
  description: "Bybit-тің екі аяқты комбинацияларын және орындалатын top of book дерегін оқиды. Котировкалар биржадан алынады, тек оқу режимінде және кепілді пайда ретінде көрсетілмейді.",
  product: "Комбинация түрі",
  allProducts: "Барлық түрі",
  baseCoin: "Базалық актив",
  anyBase: "Кез келген",
  minimumSize: "Минималды көлем",
  ranking: "Сұрыптау",
  capacity: "Қолжетімді көлем",
  tightness: "Тар стакан",
  freshness: "Жаңа котировка",
  candidates: "Макс. стакан",
  scan: "Стакандарды оқу",
  scanning: "Оқылуда…",
  scannerUnavailable: "Нативті спред скринері уақытша қолжетімсіз.",
  instruments: "Құрал саны",
  eligible: "Сәйкес",
  checked: "Тексерілген стакан",
  healthy: "Дұрыс стакан",
  results: "Екі аяқты комбинацияның биржалық котировкалары",
  updated: "Жаңартылды",
  combination: "Комбинация",
  legs: "Аяқтар",
  bid: "Үздік bid",
  ask: "Үздік ask",
  width: "Стакан ені",
  size: "Екіжақты көлем",
  rules: "Биржа ережелері",
  quality: "Сапа",
  charts: "Графиктер",
  actions: "Әрекеттер",
  chart: "{symbol} графигін ашу",
  age: "жасы {value} мс",
  relativeWidth: "{value} б.п.",
  step: "қадам {value}",
  minimum: "мин. {value}",
  restTopBook: "REST: үздік баға",
  noResults: "Сүзгілерге сай жаңа екіжақты стакан табылмады.",
  noResultsHint: "Бос нәтиже скринердің ескірген, біржақты немесе қате деректі қабылдамағанын білдіреді.",
  partial: "Сәйкес құралдардың тек бір бөлігі сұралды. Қамтуды кеңейту үшін стакан лимитін арттырыңыз.",
  sourceErrors: "Кейбір стакандар қабылданбады ({count}).",
  sourceErrorItem: "{index}-дереккөз стаканы қабылданбады.",
  staleHandoff: "Беруден бұрын ескірген нативті спред котировкасын жаңартыңыз.",
  riskTitle: "Нативті стакан — кепілді пайда емес",
  risk: "Bid және ask — есептелген ROI емес, Bybit комбинация құралының бағалары. Комиссия, кепіл, аккаунт қолжетімділігі, баға қозғалысы және жартылай орындалу маңызды. Order алдында құрал мен стаканды қайта тексеріңіз.",
  FundingRateArb: "Perpetual + spot",
  CarryTrade: "Мерзімді futures + spot",
  FutureSpread: "Күнтізбелік futures",
  PerpBasis: "Futures + perpetual",
  LinearPerpetual: "perpetual",
  LinearFutures: "futures",
  Spot: "spot"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function nativeSpreadText(locale: Locale, key: Key, values: Record<string, string> = {}) {
  return Object.entries(values).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, replacement), messages[locale][key]);
}
