import { localized, type Locale } from "../i18n";

const en = {
  mode: "Options parity",
  title: "European options parity lab",
  description: "Test caller-supplied call, put and underlying depth against put-call parity, conversion, reversal and synthetic-forward shapes.",
  safety: "Visible-depth research only · no account · no orders",
  identity: "Identity and expiry",
  prices: "Visible top-book prices",
  economics: "Quantity and assumptions",
  underlyingAsset: "Underlying asset",
  valuationAsset: "Valuation / settlement asset",
  strikePrice: "Strike price",
  expiryHours: "Hours to expiry",
  callBid: "Call bid",
  callAsk: "Call ask",
  putBid: "Put bid",
  putAsk: "Put ask",
  underlyingBid: "Underlying bid",
  underlyingAsk: "Underlying ask",
  targetQuantity: "Target base quantity",
  shortCapacity: "Verified scenario short capacity",
  riskFree: "Risk-free rate, % annual",
  dividend: "Dividend yield, % annual",
  borrow: "Underlying borrow, % annual",
  optionFee: "Option fee, bps",
  underlyingFee: "Underlying fee, bps",
  evaluate: "Evaluate scenario",
  evaluating: "Evaluating…",
  results: "Research candidates",
  noCandidates: "No positive candidate passed every stated assumption.",
  rejections: "Rejected shapes",
  strategy: "Strategy",
  direction: "Direction",
  netEdge: "Net edge",
  grossEdge: "Gross edge",
  fees: "Fees",
  edgeBps: "Edge / reference",
  quantity: "Quantity",
  expiry: "Expiry",
  legs: "Visible-depth legs",
  side: "Side",
  average: "Average price",
  scenarioNotice: "All capacity, borrow, margin, fee and settlement values are explicit scenario assumptions—not live account or venue evidence.",
  unavailable: "Options-parity evaluation failed"
} as const;

type Key = keyof typeof en;
const ru: Record<Key, string> = {
  mode: "Паритет опционов",
  title: "Лаборатория паритета европейских опционов",
  description: "Проверьте заданные call, put и базовый актив на put-call parity, conversion, reversal и synthetic-forward.",
  safety: "Только исследование видимой глубины · без аккаунта · без ордеров",
  identity: "Идентичность и экспирация",
  prices: "Цены видимого стакана",
  economics: "Количество и допущения",
  underlyingAsset: "Базовый актив",
  valuationAsset: "Актив оценки / расчёта",
  strikePrice: "Страйк",
  expiryHours: "Часов до экспирации",
  callBid: "Call bid",
  callAsk: "Call ask",
  putBid: "Put bid",
  putAsk: "Put ask",
  underlyingBid: "Bid базового актива",
  underlyingAsk: "Ask базового актива",
  targetQuantity: "Целевое количество базы",
  shortCapacity: "Подтверждённая ёмкость short-сценария",
  riskFree: "Безрисковая ставка, % годовых",
  dividend: "Дивидендная доходность, % годовых",
  borrow: "Займ базового актива, % годовых",
  optionFee: "Комиссия опциона, bps",
  underlyingFee: "Комиссия базы, bps",
  evaluate: "Рассчитать сценарий",
  evaluating: "Расчёт…",
  results: "Исследовательские кандидаты",
  noCandidates: "Ни один положительный кандидат не прошёл все заданные допущения.",
  rejections: "Отклонённые конструкции",
  strategy: "Стратегия",
  direction: "Направление",
  netEdge: "Чистое преимущество",
  grossEdge: "Валовое преимущество",
  fees: "Комиссии",
  edgeBps: "Преимущество / база",
  quantity: "Количество",
  expiry: "Экспирация",
  legs: "Ноги по видимой глубине",
  side: "Сторона",
  average: "Средняя цена",
  scenarioNotice: "Ёмкость, займ, маржа, комиссии и расчёт — явные допущения сценария, а не живые данные аккаунта или биржи.",
  unavailable: "Не удалось рассчитать паритет опционов"
};

const kk: Record<Key, string> = {
  mode: "Опцион паритеті",
  title: "Еуропалық опцион паритеті зертханасы",
  description: "Берілген call, put және базалық активті put-call parity, conversion, reversal және synthetic-forward бойынша тексеріңіз.",
  safety: "Тек көрінетін тереңдік зерттеуі · аккаунтсыз · ордерсіз",
  identity: "Identity және expiry",
  prices: "Көрінетін стакан бағалары",
  economics: "Мөлшер және assumptions",
  underlyingAsset: "Базалық актив",
  valuationAsset: "Бағалау / settlement активі",
  strikePrice: "Strike бағасы",
  expiryHours: "Expiry-ге дейінгі сағат",
  callBid: "Call bid",
  callAsk: "Call ask",
  putBid: "Put bid",
  putAsk: "Put ask",
  underlyingBid: "Базалық актив bid",
  underlyingAsk: "Базалық актив ask",
  targetQuantity: "Мақсатты base quantity",
  shortCapacity: "Расталған short scenario capacity",
  riskFree: "Risk-free rate, жылдық %",
  dividend: "Dividend yield, жылдық %",
  borrow: "Underlying borrow, жылдық %",
  optionFee: "Option fee, bps",
  underlyingFee: "Underlying fee, bps",
  evaluate: "Scenario есептеу",
  evaluating: "Есептелуде…",
  results: "Зерттеу кандидаттары",
  noCandidates: "Барлық assumption талабынан өткен оң кандидат жоқ.",
  rejections: "Қабылданбаған құрылымдар",
  strategy: "Стратегия",
  direction: "Бағыт",
  netEdge: "Таза артықшылық",
  grossEdge: "Жалпы артықшылық",
  fees: "Комиссиялар",
  edgeBps: "Edge / reference",
  quantity: "Мөлшер",
  expiry: "Expiry",
  legs: "Көрінетін тереңдік legs",
  side: "Тарап",
  average: "Орташа баға",
  scenarioNotice: "Capacity, borrow, margin, fee және settlement — live account немесе venue evidence емес, scenario assumption.",
  unavailable: "Опцион паритетін есептеу сәтсіз аяқталды"
};

export function optionsParityText(locale: Locale, key: Key): string {
  return localized(locale, { en, ru, kk })[key];
}
