import type { Locale } from "../i18n";

const en = {
  mode: "Order-book ML",
  eyebrow: "Admin · ephemeral research · upload-only",
  title: "Anonymous order-book pattern lab",
  description: "Upload verified sequenced L2 captures, train a bounded ridge baseline and inspect out-of-sample diagnostics.",
  safetyTitle: "Scope boundary",
  safetyAnonymous: "Patterns describe anonymous aggregate liquidity; participant identity is never inferred.",
  safetyNoProbability: "A predicted return is neither a probability nor a trading signal.",
  safetyNoExecution: "Research only: paper and live orders are disabled.",
  safetyUploadOnly: "Online capture is unavailable. Only caller-supplied reconstructed sequenced L2 is accepted.",
  refresh: "Refresh status",
  loading: "Loading research registry…",
  statusUnavailable: "Research status is unavailable.",
  adminRequired: "Admin access is required for order-book ML research.",
  authRequired: "Sign in with an admin session to use this lab.",
  invalidInput: "The supplied configuration or snapshot JSON is invalid.",
  operationFailed: "The research operation failed.",
  serviceStatus: "Ephemeral registry",
  sessions: "Sessions",
  snapshots: "Snapshots",
  models: "Models",
  limit: "Limits: {sessions} sessions · {snapshots} snapshots/session · {models} models/session · {ttl} min TTL",
  storage: "Bounded in-memory storage · raw data is not persisted",
  sessionManager: "Research sessions",
  createSession: "Create session",
  name: "Session name (optional)",
  nameHint: "A local research label; do not include credentials or personal data.",
  labelPolicy: "Future-label policy",
  horizons: "Horizons (ms, comma-separated)",
  horizonsHint: "1–3 strictly increasing horizons, each ≤ 300000 ms.",
  alignment: "Maximum alignment delay (ms)",
  qualityPolicy: "Capture quality policy",
  maximumAge: "Maximum age for inference (ms)",
  futureSkew: "Maximum future skew (ms)",
  inputDepth: "Maximum input depth",
  normalizedDepth: "Normalized depth",
  create: "Create research session",
  creating: "Creating…",
  selectSession: "Active session",
  chooseSession: "Choose a session",
  noSessions: "No ephemeral research sessions exist.",
  expires: "Expires {time}",
  delete: "Delete session",
  deletePrompt: "Delete this session and its ephemeral models?",
  confirmDelete: "Confirm deletion",
  cancel: "Cancel",
  deleting: "Deleting…",
  createdNotice: "Research session created.",
  deletedNotice: "Session and {count} ephemeral model(s) deleted.",
  sessionDetails: "Session evidence",
  provenance: "Capture provenance",
  noProvenance: "No accepted snapshots; provenance is not established.",
  venueMarket: "Venue / market",
  instrument: "Instrument",
  sequenceRange: "Sequence range",
  captureWindow: "Capture window",
  normalizer: "Normalizer",
  checksum: "Checksum verified for every snapshot",
  yes: "yes",
  no: "no",
  qualityCounters: "Quality counters",
  submitted: "Submitted",
  accepted: "Accepted",
  rejected: "Rejected",
  discarded: "Discarded atomically",
  acceptedBatches: "Accepted batches",
  rejectedBatches: "Rejected batches",
  issueCodes: "Quality issue codes",
  none: "none",
  uploadTitle: "Upload sequenced L2 capture",
  uploadHint: 'Paste a JSON array or {"snapshots":[…]}. Batch: 1–250; each side: 10–100 levels. The service validates atomic continuity and capture-time quality.',
  snapshotJson: "Sequenced L2 snapshots (JSON)",
  upload: "Validate and upload",
  uploading: "Uploading…",
  uploadedNotice: "Accepted {count} snapshots; session total is {total}.",
  trainTitle: "Train ridge baseline",
  trainingConfig: "Chronological training configuration",
  horizon: "Label horizon",
  ridgeLambda: "Ridge lambda",
  trainFraction: "Training fraction",
  validationFraction: "Validation fraction",
  minimumRows: "Minimum rows per split",
  flatThreshold: "Flat threshold (bps)",
  oodThreshold: "OOD z-score threshold",
  trainModel: "Train model",
  training: "Training…",
  trainedNotice: "Model trained with chronological purged splits.",
  modelList: "Ephemeral models",
  noModels: "No models have been trained in this session.",
  chooseModel: "Use model {id}",
  modelId: "Model ID",
  anchorScope: "Anchor scope",
  anchorSequence: "Anchor sequence",
  anchorTime: "Anchor exchange time",
  trainedAt: "Trained",
  dataset: "Dataset rows",
  splitMetrics: "Out-of-sample split metrics",
  split: "Split",
  train: "Train",
  validation: "Validation",
  test: "Test",
  rows: "Rows",
  mae: "MAE (bps)",
  rmse: "RMSE (bps)",
  directionalAccuracy: "Directional accuracy",
  correlation: "Correlation",
  purgedRows: "Purged at boundaries: train {train} · validation {validation}",
  predictionTitle: "Fresh-snapshot inference",
  predictionHint: "Paste 1–2 current snapshots matching the selected model scope. Freshness is evaluated against server time; historical captures are rejected.",
  inferenceJson: "Fresh sequenced L2 snapshots (JSON)",
  predict: "Run research inference",
  predicting: "Evaluating…",
  predictionNotice: "Research inference completed; no order action was created.",
  predictionResult: "Research prediction",
  predictedReturn: "Predicted return",
  direction: "Direction",
  signalToNoise: "Magnitude / validation RMSE",
  up: "up",
  down: "down",
  flat: "flat",
  distribution: "Training-range check",
  withinRange: "within training range",
  outOfDistribution: "out of distribution",
  maxZScore: "Maximum |z| {value} · threshold {threshold}",
  contributions: "Largest linear contributions",
  feature: "Feature",
  standardizedValue: "Standardized value",
  contribution: "Contribution (bps)",
  inferenceProvenance: "Inference provenance",
  inferenceEvidence: "{count} caller-uploaded fresh snapshot(s) · {schema} · normalizer {normalizer} · quality evaluated {time}",
  noProbability: "No probability is produced. This output must not drive paper or live execution.",
  busy: "Research operation in progress…"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  mode: "ML стакана",
  eyebrow: "Админ · временное исследование · только загрузка",
  title: "Лаборатория анонимных паттернов стакана",
  description: "Загрузите проверенные последовательные L2-снимки, обучите ограниченный ridge-baseline и изучите out-of-sample диагностику.",
  safetyTitle: "Граница применимости",
  safetyAnonymous: "Паттерны описывают анонимную агрегированную ликвидность; личности участников не определяются.",
  safetyNoProbability: "Прогноз доходности — не вероятность и не торговый сигнал.",
  safetyNoExecution: "Только исследование: paper- и live-ордера запрещены.",
  safetyUploadOnly: "Онлайн-сбор отсутствует. Принимаются только загруженные восстановленные последовательные L2-данные.",
  refresh: "Обновить статус",
  loading: "Загружается реестр исследований…",
  statusUnavailable: "Статус исследований недоступен.",
  adminRequired: "Для ML-исследования стакана нужен доступ администратора.",
  authRequired: "Войдите в админ-сессию, чтобы использовать лабораторию.",
  invalidInput: "Конфигурация или JSON снимков некорректны.",
  operationFailed: "Операция исследования завершилась ошибкой.",
  serviceStatus: "Временный реестр",
  sessions: "Сессии",
  snapshots: "Снимки",
  models: "Модели",
  limit: "Лимиты: {sessions} сессии · {snapshots} снимков/сессию · {models} модели/сессию · TTL {ttl} мин",
  storage: "Ограниченное хранение в памяти · сырые данные не сохраняются",
  sessionManager: "Исследовательские сессии",
  createSession: "Создать сессию",
  name: "Название сессии (необязательно)",
  nameHint: "Локальная исследовательская метка; не добавляйте ключи или персональные данные.",
  labelPolicy: "Политика будущих меток",
  horizons: "Горизонты (мс, через запятую)",
  horizonsHint: "1–3 строго возрастающих горизонта, каждый ≤ 300000 мс.",
  alignment: "Максимальная задержка выравнивания (мс)",
  qualityPolicy: "Политика качества захвата",
  maximumAge: "Максимальный возраст для инференса (мс)",
  futureSkew: "Максимальный сдвиг в будущее (мс)",
  inputDepth: "Максимальная глубина входа",
  normalizedDepth: "Нормализованная глубина",
  create: "Создать исследовательскую сессию",
  creating: "Создание…",
  selectSession: "Активная сессия",
  chooseSession: "Выберите сессию",
  noSessions: "Временных исследовательских сессий нет.",
  expires: "Истекает {time}",
  delete: "Удалить сессию",
  deletePrompt: "Удалить сессию и её временные модели?",
  confirmDelete: "Подтвердить удаление",
  cancel: "Отмена",
  deleting: "Удаление…",
  createdNotice: "Исследовательская сессия создана.",
  deletedNotice: "Сессия и временные модели ({count}) удалены.",
  sessionDetails: "Доказательства сессии",
  provenance: "Происхождение захвата",
  noProvenance: "Принятых снимков нет; происхождение ещё не установлено.",
  venueMarket: "Биржа / рынок",
  instrument: "Инструмент",
  sequenceRange: "Диапазон последовательности",
  captureWindow: "Окно захвата",
  normalizer: "Нормализатор",
  checksum: "Checksum подтверждён для каждого снимка",
  yes: "да",
  no: "нет",
  qualityCounters: "Счётчики качества",
  submitted: "Отправлено",
  accepted: "Принято",
  rejected: "Отклонено",
  discarded: "Атомарно отброшено",
  acceptedBatches: "Принятые пакеты",
  rejectedBatches: "Отклонённые пакеты",
  issueCodes: "Коды проблем качества",
  none: "нет",
  uploadTitle: "Загрузка последовательного L2-захвата",
  uploadHint: 'Вставьте JSON-массив или {"snapshots":[…]}. Пакет: 1–250; каждая сторона: 10–100 уровней. Сервис атомарно проверяет непрерывность и качество на момент захвата.',
  snapshotJson: "Последовательные L2-снимки (JSON)",
  upload: "Проверить и загрузить",
  uploading: "Загрузка…",
  uploadedNotice: "Принято снимков: {count}; всего в сессии: {total}.",
  trainTitle: "Обучение ridge-baseline",
  trainingConfig: "Конфигурация хронологического обучения",
  horizon: "Горизонт метки",
  ridgeLambda: "Ridge lambda",
  trainFraction: "Доля обучения",
  validationFraction: "Доля валидации",
  minimumRows: "Минимум строк в split",
  flatThreshold: "Порог flat (б.п.)",
  oodThreshold: "Порог OOD z-score",
  trainModel: "Обучить модель",
  training: "Обучение…",
  trainedNotice: "Модель обучена на хронологических split с purging.",
  modelList: "Временные модели",
  noModels: "В этой сессии моделей пока нет.",
  chooseModel: "Использовать модель {id}",
  modelId: "ID модели",
  anchorScope: "Область anchor",
  anchorSequence: "Последовательность anchor",
  anchorTime: "Биржевое время anchor",
  trainedAt: "Обучена",
  dataset: "Строки датасета",
  splitMetrics: "Метрики out-of-sample split",
  split: "Split",
  train: "Обучение",
  validation: "Валидация",
  test: "Тест",
  rows: "Строки",
  mae: "MAE (б.п.)",
  rmse: "RMSE (б.п.)",
  directionalAccuracy: "Точность направления",
  correlation: "Корреляция",
  purgedRows: "Удалено на границах: обучение {train} · валидация {validation}",
  predictionTitle: "Инференс по свежему снимку",
  predictionHint: "Вставьте 1–2 текущих снимка в области выбранной модели. Свежесть проверяется по времени сервера; исторические снимки отклоняются.",
  inferenceJson: "Свежие последовательные L2-снимки (JSON)",
  predict: "Запустить исследовательский инференс",
  predicting: "Оценка…",
  predictionNotice: "Исследовательский инференс завершён; ордер не создан.",
  predictionResult: "Исследовательский прогноз",
  predictedReturn: "Прогноз доходности",
  direction: "Направление",
  signalToNoise: "Модуль / validation RMSE",
  up: "вверх",
  down: "вниз",
  flat: "без направления",
  distribution: "Проверка диапазона обучения",
  withinRange: "в диапазоне обучения",
  outOfDistribution: "вне распределения",
  maxZScore: "Максимум |z| {value} · порог {threshold}",
  contributions: "Крупнейшие линейные вклады",
  feature: "Признак",
  standardizedValue: "Стандартизированное значение",
  contribution: "Вклад (б.п.)",
  inferenceProvenance: "Происхождение инференса",
  inferenceEvidence: "Загружено свежих снимков: {count} · {schema} · нормализатор {normalizer} · качество проверено {time}",
  noProbability: "Вероятность не рассчитывается. Результат нельзя использовать для paper- или live-исполнения.",
  busy: "Выполняется исследовательская операция…"
};

const kk: Record<Key, string> = {
  mode: "Стакан ML",
  eyebrow: "Әкімші · уақытша зерттеу · тек жүктеу",
  title: "Анонимді стакан паттерндері зертханасы",
  description: "Расталған реттелген L2 snapshot-тарын жүктеп, шектеулі ridge baseline үйретіңіз және out-of-sample диагностиканы қараңыз.",
  safetyTitle: "Қолдану шекарасы",
  safetyAnonymous: "Паттерндер анонимді жиынтық өтімділікті сипаттайды; қатысушы тұлғасы анықталмайды.",
  safetyNoProbability: "Болжанған return — ықтималдық та, сауда сигналы да емес.",
  safetyNoExecution: "Тек зерттеу: paper және live order тыйым салынған.",
  safetyUploadOnly: "Online capture жоқ. Тек caller жүктеген қалпына келтірілген реттелген L2 қабылданады.",
  refresh: "Статусты жаңарту",
  loading: "Зерттеу реестрі жүктелуде…",
  statusUnavailable: "Зерттеу статусы қолжетімсіз.",
  adminRequired: "Стакан ML зерттеуі үшін әкімші рұқсаты қажет.",
  authRequired: "Зертхананы қолдану үшін admin session-ға кіріңіз.",
  invalidInput: "Конфигурация немесе snapshot JSON жарамсыз.",
  operationFailed: "Зерттеу операциясы сәтсіз аяқталды.",
  serviceStatus: "Уақытша реестр",
  sessions: "Сессиялар",
  snapshots: "Snapshot-тар",
  models: "Модельдер",
  limit: "Шектер: {sessions} сессия · {snapshots} snapshot/сессия · {models} модель/сессия · TTL {ttl} мин",
  storage: "Жадыдағы шектеулі сақтау · raw data сақталмайды",
  sessionManager: "Зерттеу сессиялары",
  createSession: "Сессия құру",
  name: "Сессия атауы (міндетті емес)",
  nameHint: "Жергілікті зерттеу белгісі; key немесе жеке дерек қоспаңыз.",
  labelPolicy: "Future label саясаты",
  horizons: "Көкжиектер (мс, үтірмен)",
  horizonsHint: "1–3 қатаң өсетін көкжиек, әрқайсысы ≤ 300000 мс.",
  alignment: "Ең үлкен alignment кешігуі (мс)",
  qualityPolicy: "Capture сапа саясаты",
  maximumAge: "Inference үшін ең үлкен жас (мс)",
  futureSkew: "Болашаққа ең үлкен ығысу (мс)",
  inputDepth: "Ең үлкен input depth",
  normalizedDepth: "Нормаланған depth",
  create: "Зерттеу сессиясын құру",
  creating: "Құрылуда…",
  selectSession: "Белсенді сессия",
  chooseSession: "Сессия таңдаңыз",
  noSessions: "Уақытша зерттеу сессиялары жоқ.",
  expires: "Аяқталуы {time}",
  delete: "Сессияны жою",
  deletePrompt: "Сессия мен уақытша модельдерін жою керек пе?",
  confirmDelete: "Жоюды растау",
  cancel: "Болдырмау",
  deleting: "Жойылуда…",
  createdNotice: "Зерттеу сессиясы құрылды.",
  deletedNotice: "Сессия және {count} уақытша модель жойылды.",
  sessionDetails: "Сессия дәлелдері",
  provenance: "Capture provenance",
  noProvenance: "Қабылданған snapshot жоқ; provenance анықталмаған.",
  venueMarket: "Биржа / нарық",
  instrument: "Құрал",
  sequenceRange: "Sequence аралығы",
  captureWindow: "Capture терезесі",
  normalizer: "Нормализатор",
  checksum: "Барлық snapshot checksum-ы расталған",
  yes: "иә",
  no: "жоқ",
  qualityCounters: "Сапа санағыштары",
  submitted: "Жіберілді",
  accepted: "Қабылданды",
  rejected: "Қабылданбады",
  discarded: "Атомды түрде тасталды",
  acceptedBatches: "Қабылданған batch",
  rejectedBatches: "Қабылданбаған batch",
  issueCodes: "Сапа issue code-тары",
  none: "жоқ",
  uploadTitle: "Реттелген L2 capture жүктеу",
  uploadHint: 'JSON array немесе {"snapshots":[…]} енгізіңіз. Batch: 1–250; әр side: 10–100 level. Service continuity мен capture-time сапасын атомды тексереді.',
  snapshotJson: "Реттелген L2 snapshot-тар (JSON)",
  upload: "Тексеру және жүктеу",
  uploading: "Жүктелуде…",
  uploadedNotice: "{count} snapshot қабылданды; сессияда барлығы {total}.",
  trainTitle: "Ridge baseline үйрету",
  trainingConfig: "Хронологиялық training конфигурациясы",
  horizon: "Label көкжиегі",
  ridgeLambda: "Ridge lambda",
  trainFraction: "Training үлесі",
  validationFraction: "Validation үлесі",
  minimumRows: "Әр split үшін ең аз row",
  flatThreshold: "Flat шегі (б.п.)",
  oodThreshold: "OOD z-score шегі",
  trainModel: "Модельді үйрету",
  training: "Үйретілуде…",
  trainedNotice: "Модель purged хронологиялық split арқылы үйретілді.",
  modelList: "Уақытша модельдер",
  noModels: "Бұл сессияда модель жоқ.",
  chooseModel: "{id} моделін қолдану",
  modelId: "Модель ID",
  anchorScope: "Anchor scope",
  anchorSequence: "Anchor sequence",
  anchorTime: "Anchor биржа уақыты",
  trainedAt: "Үйретілді",
  dataset: "Dataset row саны",
  splitMetrics: "Out-of-sample split метрикалары",
  split: "Split",
  train: "Train",
  validation: "Validation",
  test: "Test",
  rows: "Row",
  mae: "MAE (б.п.)",
  rmse: "RMSE (б.п.)",
  directionalAccuracy: "Бағыт дәлдігі",
  correlation: "Корреляция",
  purgedRows: "Шекарада purged: train {train} · validation {validation}",
  predictionTitle: "Fresh snapshot inference",
  predictionHint: "Таңдалған модель scope-ына сай 1–2 current snapshot енгізіңіз. Freshness server уақытымен тексеріледі; historical capture қабылданбайды.",
  inferenceJson: "Fresh реттелген L2 snapshot-тар (JSON)",
  predict: "Зерттеу inference-ын іске қосу",
  predicting: "Бағалануда…",
  predictionNotice: "Зерттеу inference аяқталды; order жасалмады.",
  predictionResult: "Зерттеу болжамы",
  predictedReturn: "Болжанған return",
  direction: "Бағыт",
  signalToNoise: "Модуль / validation RMSE",
  up: "жоғары",
  down: "төмен",
  flat: "flat",
  distribution: "Training range тексеруі",
  withinRange: "training range ішінде",
  outOfDistribution: "distribution сыртында",
  maxZScore: "Ең үлкен |z| {value} · шек {threshold}",
  contributions: "Ең үлкен linear contribution-дар",
  feature: "Feature",
  standardizedValue: "Стандартталған мән",
  contribution: "Contribution (б.п.)",
  inferenceProvenance: "Inference provenance",
  inferenceEvidence: "Caller жүктеген fresh snapshot: {count} · {schema} · normalizer {normalizer} · сапа {time} тексерілді",
  noProbability: "Ықтималдық есептелмейді. Нәтижені paper немесе live execution үшін қолдануға болмайды.",
  busy: "Зерттеу операциясы орындалуда…"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function orderBookMlResearchText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, value), messages[locale][key]);
}
