import type { Locale } from "../i18n";

const en = {
  workspace: "Scanner workspace",
  workspaceHint: "Save bounded local presets, choose columns and switch between the table and snapshot visualizations.",
  presetName: "Preset name",
  presetNamePlaceholder: "My research view",
  savePreset: "Save preset",
  savedPresets: "Saved presets",
  choosePreset: "Choose a preset",
  deletePreset: "Delete selected preset",
  resetLayout: "Reset layout",
  columns: "Visible table columns",
  requiredColumn: "required",
  view: "Results view",
  tableView: "Table",
  heatmapView: "Heatmap",
  compareView: "Route compare",
  presetSaved: "Preset saved locally.",
  presetDeleted: "Preset deleted.",
  presetLimit: "Only the 12 most recent presets are kept.",
  heatmapTitle: "Opportunity heatmap",
  heatmapHint: "Relative intensity ranks the current snapshot only; exact values remain visible and color is not the only signal.",
  compareTitle: "Route graph and candidate comparison",
  compareHint: "Compares current research candidates. It does not predict execution or guarantee profit.",
  candidateA: "Candidate A",
  candidateB: "Candidate B",
  chooseCandidate: "Choose a candidate",
  graphTitle: "Route graph for {route}",
  graphCaption: "Ordered legs for the selected candidate.",
  compareCaption: "Current snapshot comparison",
  metric: "Metric",
  noCandidates: "No candidates are available for this visualization.",
  rank: "Rank {rank}",
  primaryMetric: "Primary metric",
  secondaryMetric: "Secondary metric",
  capacityMetric: "Capacity",
  freshnessMetric: "Freshness",
  basisRoute: "Buy spot → short perpetual",
  triangularRoute: "Three spot conversions",
  nativeRoute: "Venue-native combination",
  routeColumn: "Route",
  spotColumn: "Spot leg",
  perpetualColumn: "Perpetual leg",
  grossColumn: "Gross spread",
  netColumn: "Projected edge",
  profitColumn: "Projected P&L",
  capacityColumn: "Capacity",
  fundingColumn: "Funding",
  actionsColumn: "Actions",
  leg1Column: "Leg 1",
  leg2Column: "Leg 2",
  leg3Column: "Leg 3",
  resultColumn: "Result",
  qualityColumn: "Quality",
  legsColumn: "Legs",
  bidColumn: "Bid",
  askColumn: "Ask",
  widthColumn: "Book width",
  rulesColumn: "Venue rules",
  lifecycleTitle: "Opportunity lifecycle",
  lifecycleReadOnly: "read-only research state",
  lifecycleFirstSeen: "First seen",
  lifecycleConfirmed: "Confirmed",
  lifecycleDecaying: "Decaying",
  lifecycleActionable: "Actionable",
  lifecycleUnavailable: "Lifecycle status is unavailable",
  lifecycleRefresh: "Refresh lifecycle status",
  lifecycleUpdated: "Updated {time}"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  workspace: "Рабочее пространство скринера",
  workspaceHint: "Сохраняйте ограниченные локальные пресеты, выбирайте столбцы и переключайтесь между таблицей и визуализациями снимка.",
  presetName: "Название пресета",
  presetNamePlaceholder: "Мой исследовательский вид",
  savePreset: "Сохранить пресет",
  savedPresets: "Сохранённые пресеты",
  choosePreset: "Выберите пресет",
  deletePreset: "Удалить выбранный пресет",
  resetLayout: "Сбросить вид",
  columns: "Видимые столбцы таблицы",
  requiredColumn: "обязательно",
  view: "Представление результатов",
  tableView: "Таблица",
  heatmapView: "Тепловая карта",
  compareView: "Сравнение маршрутов",
  presetSaved: "Пресет сохранён локально.",
  presetDeleted: "Пресет удалён.",
  presetLimit: "Хранятся только 12 последних пресетов.",
  heatmapTitle: "Тепловая карта возможностей",
  heatmapHint: "Интенсивность ранжирует только текущий снимок; точные значения видны, а цвет не является единственным признаком.",
  compareTitle: "Граф маршрута и сравнение кандидатов",
  compareHint: "Сравниваются текущие исследовательские кандидаты. Это не прогноз исполнения и не гарантия прибыли.",
  candidateA: "Кандидат A",
  candidateB: "Кандидат B",
  chooseCandidate: "Выберите кандидата",
  graphTitle: "Граф маршрута {route}",
  graphCaption: "Последовательность ног выбранного кандидата.",
  compareCaption: "Сравнение текущего снимка",
  metric: "Метрика",
  noCandidates: "Для этой визуализации нет доступных кандидатов.",
  rank: "Место {rank}",
  primaryMetric: "Основная метрика",
  secondaryMetric: "Дополнительная метрика",
  capacityMetric: "Ёмкость",
  freshnessMetric: "Свежесть",
  basisRoute: "Купить спот → открыть шорт perpetual",
  triangularRoute: "Три спот-конвертации",
  nativeRoute: "Нативная комбинация биржи",
  routeColumn: "Маршрут",
  spotColumn: "Спот-нога",
  perpetualColumn: "Perpetual-нога",
  grossColumn: "Грязный спред",
  netColumn: "Прогнозный спред",
  profitColumn: "Прогнозный P&L",
  capacityColumn: "Ёмкость",
  fundingColumn: "Funding",
  actionsColumn: "Действия",
  leg1Column: "Нога 1",
  leg2Column: "Нога 2",
  leg3Column: "Нога 3",
  resultColumn: "Результат",
  qualityColumn: "Качество",
  legsColumn: "Ноги",
  bidColumn: "Bid",
  askColumn: "Ask",
  widthColumn: "Ширина стакана",
  rulesColumn: "Правила биржи",
  lifecycleTitle: "Жизненный цикл возможностей",
  lifecycleReadOnly: "исследовательское состояние только для чтения",
  lifecycleFirstSeen: "Впервые замечено",
  lifecycleConfirmed: "Подтверждено",
  lifecycleDecaying: "Затухает",
  lifecycleActionable: "Прошло условия",
  lifecycleUnavailable: "Статус жизненного цикла недоступен",
  lifecycleRefresh: "Обновить статус жизненного цикла",
  lifecycleUpdated: "Обновлено {time}"
};

const kk: Record<Key, string> = {
  workspace: "Скринердің жұмыс кеңістігі",
  workspaceHint: "Шектелген жергілікті preset-терді сақтаңыз, бағандарды таңдаңыз және кесте мен snapshot визуализацияларын ауыстырыңыз.",
  presetName: "Preset атауы",
  presetNamePlaceholder: "Менің зерттеу көрінісім",
  savePreset: "Preset сақтау",
  savedPresets: "Сақталған preset-тер",
  choosePreset: "Preset таңдаңыз",
  deletePreset: "Таңдалған preset-ті жою",
  resetLayout: "Көріністі қалпына келтіру",
  columns: "Кестенің көрінетін бағандары",
  requiredColumn: "міндетті",
  view: "Нәтиже көрінісі",
  tableView: "Кесте",
  heatmapView: "Жылу картасы",
  compareView: "Бағыттарды салыстыру",
  presetSaved: "Preset жергілікті сақталды.",
  presetDeleted: "Preset жойылды.",
  presetLimit: "Тек соңғы 12 preset сақталады.",
  heatmapTitle: "Мүмкіндіктердің жылу картасы",
  heatmapHint: "Қарқын тек ағымдағы snapshot-ты бағалайды; нақты мәндер көрінеді және түс жалғыз белгі емес.",
  compareTitle: "Бағыт графы және кандидаттарды салыстыру",
  compareHint: "Ағымдағы зерттеу кандидаттары салыстырылады. Бұл орындалу болжамы немесе пайда кепілдігі емес.",
  candidateA: "A кандидаты",
  candidateB: "B кандидаты",
  chooseCandidate: "Кандидатты таңдаңыз",
  graphTitle: "{route} бағытының графы",
  graphCaption: "Таңдалған кандидат аяқтарының реті.",
  compareCaption: "Ағымдағы snapshot салыстыруы",
  metric: "Метрика",
  noCandidates: "Бұл визуализация үшін кандидат жоқ.",
  rank: "{rank}-орын",
  primaryMetric: "Негізгі метрика",
  secondaryMetric: "Қосымша метрика",
  capacityMetric: "Сыйымдылық",
  freshnessMetric: "Жаңалығы",
  basisRoute: "Spot сатып алу → perpetual short",
  triangularRoute: "Үш spot конверсиясы",
  nativeRoute: "Биржаның нативті комбинациясы",
  routeColumn: "Бағыт",
  spotColumn: "Spot аяғы",
  perpetualColumn: "Perpetual аяғы",
  grossColumn: "Жалпы айырма",
  netColumn: "Болжамды айырма",
  profitColumn: "Болжамды P&L",
  capacityColumn: "Сыйымдылық",
  fundingColumn: "Funding",
  actionsColumn: "Әрекеттер",
  leg1Column: "1-аяқ",
  leg2Column: "2-аяқ",
  leg3Column: "3-аяқ",
  resultColumn: "Нәтиже",
  qualityColumn: "Сапа",
  legsColumn: "Аяқтар",
  bidColumn: "Bid",
  askColumn: "Ask",
  widthColumn: "Стакан ені",
  rulesColumn: "Биржа ережелері",
  lifecycleTitle: "Мүмкіндіктердің өмірлік циклі",
  lifecycleReadOnly: "тек оқуға арналған зерттеу күйі",
  lifecycleFirstSeen: "Алғаш байқалды",
  lifecycleConfirmed: "Расталды",
  lifecycleDecaying: "Әлсіреуде",
  lifecycleActionable: "Шарттан өтті",
  lifecycleUnavailable: "Өмірлік цикл күйі қолжетімсіз",
  lifecycleRefresh: "Өмірлік цикл күйін жаңарту",
  lifecycleUpdated: "{time} жаңартылды"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function scannerUxText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}

export type ScannerUxTextKey = Key;
