import type { Locale } from "../i18n";

const en = {
  title: "Spot/perpetual arbitrage screener",
  description: "Compares observed spot asks with perpetual bids on the same or another exchange. Every row discloses timing quality; no orders are placed.",
  search: "Search pair",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Minimum projected edge",
  minCapacity: "Minimum top-book capacity",
  costs: "Estimated total costs",
  costsHint: "Entry/exit fees, slippage, verified funding schedule, financing and configured rebalancing costs.",
  refreshEvery: "Auto refresh",
  off: "Off",
  seconds: "seconds",
  refresh: "Refresh quotes",
  updating: "Updating",
  updated: "Updated",
  stale: "Showing a recent cached snapshot because one or more sources are unavailable.",
  truncated: "The server returned only part of the matching universe. Tighten server-side filters before relying on ranking.",
  scanned: "Pairs scanned",
  matching: "Routes shown",
  bestEdge: "Best projected edge",
  sourceHealth: "Market-data sources",
  clockHealth: "Venue clock calibration",
  clockCalibrated: "clock calibrated",
  clockDegraded: "clock confidence low",
  clockExpired: "clock sample expired",
  clockUnavailable: "clock unavailable",
  clockMetrics: "offset {offset} ms ± {uncertainty} ms · RTT {rtt} ms",
  clockWarning: "Cross-venue clock calibration is incomplete. Timing comparisons remain research-only until every required venue is calibrated.",
  clockRequestFailed: "Venue clock diagnostics are temporarily unavailable.",
  spot: "spot",
  perpetual: "perpetual",
  connected: "connected",
  unavailable: "unavailable",
  results: "Same-venue and cross-venue spot/perpetual research candidates",
  signalQualityFresh: "fresh timing",
  signalQualityStale: "stale timing",
  signalQualitySkewed: "skewed timing",
  signalQualityUnverified: "unverified timing",
  pair: "Pair",
  buySpot: "Buy spot",
  shortPerpetual: "Short perpetual",
  grossSpread: "Gross spread",
  netEdge: "Projected edge",
  expectedProfit: "Projected P&L",
  capacity: "Top-book capacity",
  funding: "Funding rate",
  action: "Chart",
  openChart: "Open chart for {symbol}",
  openSpotChart: "Open {venue} spot chart for {symbol}",
  openPerpetualChart: "Open {venue} perpetual chart for {symbol}",
  noResults: "No routes match the current filters.",
  noResultsHint: "Lower the minimum edge or capacity. A positive quote is not guaranteed profit.",
  riskTitle: "Execution risks",
  risk: "Prices are asynchronous snapshots. Fees, slippage, funding, transfer time, borrow availability, position limits and liquidation risk can remove the apparent edge. Both legs must be managed independently.",
  buyAt: "Buy at",
  sellAt: "Short at",
  advancedSettings: "Fees, alerts and simulation",
  feeProfile: "Fee profile",
  feeProfileHint: "Your taker fees per leg. The route estimate includes entry and exit.",
  binanceSpotFee: "Binance spot",
  binancePerpetualFee: "Binance perpetual",
  bybitSpotFee: "Bybit spot",
  bybitPerpetualFee: "Bybit perpetual",
  slippageReserve: "Round-trip slippage reserve",
  basisPointUnit: "bp",
  hourUnit: "h",
  holdingHours: "Expected holding time (hours)",
  annualBorrowRate: "Annual financing / borrow rate",
  transferCost: "Fixed transfer cost",
  costModelHint: "Net edge also estimates funding, financing and a fixed transfer cost for the selected notional.",
  alertSettings: "Opportunity alert",
  alertHint: "Fires only when a route crosses the threshold. Telegram delivery requires a paper-trade session.",
  enableAlerts: "Desktop and Telegram alerts",
  alertThreshold: "Alert threshold",
  simulation: "Depth and paper simulation",
  simulationHint: "Order books are fetched only on request and never place an order.",
  notional: "Test notional",
  connecting: "Connecting",
  live: "Live stream",
  fallback: "REST fallback",
  paused: "Paused in background",
  marketDataUnavailable: "Arbitrage market data is temporarily unavailable.",
  actions: "Research actions",
  notificationRoute: "{spotVenue} {spotMarket} → {futuresVenue} {perpetualMarket}",
  analyzeDepth: "Analyze order-book depth for {symbol}",
  openPaper: "Open paper two-leg position for {symbol}",
  paperRequiresFreshSignal: "This candidate is not fresh. Depth and paper gates will fail closed unless both books provide fresh verified timing.",
  loadingDepth: "Loading both order books…",
  depthUnavailable: "Order-book depth is temporarily unavailable.",
  exitDepthUnavailable: "Exit order-book depth is temporarily unavailable.",
  depthResult: "Depth estimate for ${amount}",
  spotVwap: "Spot buy VWAP",
  perpetualVwap: "Perpetual short VWAP",
  depthNet: "Depth-adjusted net edge",
  depthTiming: "Book age {age} ms · receive skew {skew} ms",
  depthExchangeSkew: "Venue timestamp skew {skew} ms",
  depthExchangePartial: "One or both venue timestamps are unavailable; age uses independent local receipt times.",
  depthQualityFresh: "Book timing is within the safety window",
  depthQualityStale: "Book snapshot is stale",
  depthQualitySkewed: "Book timestamps are too far apart",
  depthQualityUnverified: "Book timing could not be verified",
  levels: "levels",
  depthComplete: "Both legs have enough visible depth",
  depthIncomplete: "Visible depth is insufficient — paper entry blocked",
  paperPositions: "Paper arbitrage positions",
  paperOnly: "Local research ledger. It is not an exchange account and sends no orders.",
  clearClosed: "Clear closed",
  closePaper: "Close paper",
  closed: "Closed",
  paperDepthBlocked: "Paper entry was blocked because one or both books lack visible depth.",
  paperExitBlocked: "Paper close was blocked because the exact open quantity is not executable in both exit books.",
  paperOpened: "Paper position opened for {symbol}.",
  paperClosed: "Paper position closed from exit-depth VWAP for {symbol}.",
  recordFunding: "Record confirmed funding",
  recordFundingHint: "Enter a settlement confirmed by venue history or your account statement. The current ticker estimate is not filled automatically.",
  fundingSettlementTime: "Settlement time",
  fundingRateInput: "Settled rate (%)",
  fundingReferencePrice: "Settlement reference price (USD)",
  recordConfirmedFunding: "Append funding event",
  paperFundingRecorded: "Confirmed manual funding event recorded for {symbol}.",
  fundingRecordFailed: "The confirmed funding event could not be recorded.",
  paperFundingTotal: "Funding events: {amount}",
  alertFired: "Arbitrage threshold crossed on {count} route(s).",
  persistentAlerts: "Persistent Telegram rule",
  persistentAlertHint: "Runs on the server while the browser is closed. It only sends a notification and never places orders.",
  saveServerAlert: "Save server rule",
  signInForPersistent: "Sign in on the Trade tab with paper-trade access to save server rules.",
  savedRules: "Saved rules",
  deleteRule: "Delete persistent alert rule",
  ruleSaved: "Persistent rule saved.",
  dismissNotice: "Dismiss notice",
  opportunityHistory: "24-hour opportunity history",
  historyEmpty: "History starts accumulating once the server feed is active.",
  previousPage: "Previous page",
  nextPage: "Next page",
  pageStatus: "Showing {from}–{to} of {total}",
  paperRealized: "Realized P&L",
  paperUnrealized: "Open P&L",
  paperPartialPnl: "Partial {amount}",
  paperPnlCoverage: "Priced open positions: {known}/{total}",
  paperWinRate: "Closed win rate",
  paperAverage: "Average closed P&L"
} as const;

export type ArbitrageTextKey = keyof typeof en;
type Key = ArbitrageTextKey;

const ru: Record<Key, string> = {
  title: "Арбитражный скринер спот/фьючерс",
  description: "Сравнивает наблюдаемый spot ask с bid бессрочного фьючерса той же или другой биржи. Для каждой строки показано качество времени; ордера не отправляются.",
  search: "Поиск пары",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минимальный прогнозный спред",
  minCapacity: "Минимальный объём в лучшей цене",
  costs: "Оценка общих издержек",
  costsHint: "Комиссии входа/выхода, проскальзывание, подтверждённое расписание funding, финансирование и заданная стоимость ребалансировки.",
  refreshEvery: "Автообновление",
  off: "Выкл.",
  seconds: "секунд",
  refresh: "Обновить котировки",
  updating: "Обновление",
  updated: "Обновлено",
  stale: "Показан недавний кэш: один или несколько источников сейчас недоступны.",
  truncated: "Сервер вернул только часть подходящих маршрутов. Перед оценкой рейтинга уточните серверные фильтры.",
  scanned: "Проверено пар",
  matching: "Показано маршрутов",
  bestEdge: "Лучший прогнозный спред",
  sourceHealth: "Источники рыночных данных",
  clockHealth: "Калибровка часов бирж",
  clockCalibrated: "часы откалиброваны",
  clockDegraded: "низкая точность часов",
  clockExpired: "замер часов устарел",
  clockUnavailable: "часы недоступны",
  clockMetrics: "смещение {offset} мс ± {uncertainty} мс · RTT {rtt} мс",
  clockWarning: "Калибровка межбиржевого времени неполна. Сравнение времени остаётся исследовательским, пока не откалиброваны все нужные биржи.",
  clockRequestFailed: "Диагностика часов бирж временно недоступна.",
  spot: "спот",
  perpetual: "бессрочный фьючерс",
  connected: "подключён",
  unavailable: "недоступен",
  results: "Исследовательские внутрибиржевые и межбиржевые кандидаты спот/фьючерс",
  signalQualityFresh: "время подтверждено",
  signalQualityStale: "устаревшее время",
  signalQualitySkewed: "время рассинхронизировано",
  signalQualityUnverified: "время не подтверждено",
  pair: "Пара",
  buySpot: "Купить спот",
  shortPerpetual: "Шорт фьючерса",
  grossSpread: "Грязный спред",
  netEdge: "Прогнозный спред",
  expectedProfit: "Прогнозный P&L",
  capacity: "Объём в лучшей цене",
  funding: "Ставка funding",
  action: "График",
  openChart: "Открыть график {symbol}",
  openSpotChart: "Открыть спот-график {symbol} на {venue}",
  openPerpetualChart: "Открыть perpetual-график {symbol} на {venue}",
  noResults: "Под текущие фильтры маршруты не найдены.",
  noResultsHint: "Уменьшите минимальный спред или объём. Положительная котировка не гарантирует прибыль.",
  riskTitle: "Риски исполнения",
  risk: "Цены получены асинхронно. Комиссии, проскальзывание, funding, время перевода, доступность займа, лимиты позиции и ликвидация могут полностью убрать найденную разницу. Обе позиции необходимо контролировать отдельно.",
  buyAt: "Покупка по",
  sellAt: "Шорт по",
  advancedSettings: "Комиссии, алерты и симуляция",
  feeProfile: "Профиль комиссий",
  feeProfileHint: "Ваши taker-комиссии по каждой ноге. Расчёт учитывает вход и выход.",
  binanceSpotFee: "Binance — спот",
  binancePerpetualFee: "Binance — бессрочный фьючерс",
  bybitSpotFee: "Bybit — спот",
  bybitPerpetualFee: "Bybit — бессрочный фьючерс",
  slippageReserve: "Запас на проскальзывание туда-обратно",
  basisPointUnit: "б.п.",
  hourUnit: "ч",
  holdingHours: "Ожидаемое удержание (часы)",
  annualBorrowRate: "Годовая ставка финансирования / займа",
  transferCost: "Фиксированная стоимость перевода",
  costModelHint: "Чистый спред также оценивает funding, финансирование и фиксированный перевод для выбранной суммы.",
  alertSettings: "Алерт возможности",
  alertHint: "Срабатывает только при пересечении порога. Для Telegram нужна paper-trade сессия.",
  enableAlerts: "Алерты на рабочий стол и в Telegram",
  alertThreshold: "Порог чистого спреда для алерта",
  simulation: "Глубина и paper-симуляция",
  simulationHint: "Стаканы загружаются только по запросу, ордера никогда не отправляются.",
  notional: "Тестовая сумма",
  connecting: "Подключение",
  live: "Поток в реальном времени",
  fallback: "Резервный REST",
  paused: "Пауза в фоне",
  marketDataUnavailable: "Рыночные данные для арбитража временно недоступны.",
  actions: "Инструменты исследования",
  notificationRoute: "{spotVenue} {spotMarket} → {futuresVenue} {perpetualMarket}",
  analyzeDepth: "Проверить глубину стакана для {symbol}",
  openPaper: "Открыть paper-позицию из двух ног для {symbol}",
  paperRequiresFreshSignal: "Кандидат не является свежим. Глубина и paper fail closed, пока обе книги не дадут свежее подтверждённое время.",
  loadingDepth: "Загрузка двух стаканов…",
  depthUnavailable: "Глубина стаканов временно недоступна.",
  exitDepthUnavailable: "Глубина стаканов для выхода временно недоступна.",
  depthResult: "Оценка глубины для ${amount}",
  spotVwap: "VWAP покупки спота",
  perpetualVwap: "VWAP шорта фьючерса",
  depthNet: "Чистый спред с учётом глубины",
  depthTiming: "Возраст стаканов {age} мс · разброс получения {skew} мс",
  depthExchangeSkew: "Разброс времени бирж {skew} мс",
  depthExchangePartial: "Время одной или обеих бирж недоступно; возраст рассчитан по независимому локальному времени получения.",
  depthQualityFresh: "Время стаканов находится в безопасном диапазоне",
  depthQualityStale: "Снимок стаканов устарел",
  depthQualitySkewed: "Время стаканов слишком сильно различается",
  depthQualityUnverified: "Не удалось проверить время стаканов",
  levels: "уровней",
  depthComplete: "В обеих ногах достаточно видимой ликвидности",
  depthIncomplete: "Видимой глубины недостаточно — paper-вход заблокирован",
  paperPositions: "Paper-позиции арбитража",
  paperOnly: "Локальный исследовательский журнал. Это не биржевой счёт, ордера не отправляются.",
  clearClosed: "Удалить закрытые",
  closePaper: "Закрыть paper",
  closed: "Закрыта",
  paperDepthBlocked: "Paper-вход заблокирован: в одном или обоих стаканах недостаточно видимой глубины.",
  paperExitBlocked: "Paper-закрытие заблокировано: точный открытый объём нельзя исполнить в обоих выходных стаканах.",
  paperOpened: "Paper-позиция по {symbol} открыта.",
  paperClosed: "Paper-позиция по {symbol} закрыта по VWAP выходных стаканов.",
  recordFunding: "Записать подтверждённый funding",
  recordFundingHint: "Введите расчёт, подтверждённый историей биржи или выпиской счёта. Текущий прогноз тикера автоматически не подставляется.",
  fundingSettlementTime: "Время расчёта",
  fundingRateInput: "Расчётная ставка (%)",
  fundingReferencePrice: "Расчётная цена (USD)",
  recordConfirmedFunding: "Добавить событие funding",
  paperFundingRecorded: "Для {symbol} записано вручную подтверждённое событие funding.",
  fundingRecordFailed: "Не удалось записать подтверждённое событие funding.",
  paperFundingTotal: "События funding: {amount}",
  alertFired: "Порог арбитража пересечён на маршрутах: {count}.",
  persistentAlerts: "Постоянное Telegram-правило",
  persistentAlertHint: "Работает на сервере при закрытом браузере. Только отправляет уведомление и никогда не создаёт ордера.",
  saveServerAlert: "Сохранить серверное правило",
  signInForPersistent: "Войдите во вкладке «Торговля» с доступом paper-trade, чтобы сохранять серверные правила.",
  savedRules: "Сохранённые правила",
  deleteRule: "Удалить постоянное правило алерта",
  ruleSaved: "Постоянное правило сохранено.",
  dismissNotice: "Закрыть уведомление",
  opportunityHistory: "История возможности за 24 часа",
  historyEmpty: "История начнёт накапливаться после запуска серверного потока.",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  pageStatus: "Показано {from}–{to} из {total}",
  paperRealized: "Реализованный P&L",
  paperUnrealized: "P&L открытых",
  paperPartialPnl: "Частично: {amount}",
  paperPnlCoverage: "Покрытие котировками: {known}/{total} открытых позиций",
  paperWinRate: "Доля прибыльных закрытых",
  paperAverage: "Средний P&L закрытых"
};

const kk: Record<Key, string> = {
  title: "Spot/perpetual арбитраж скринері",
  description: "Бақыланатын spot ask бағасын сол немесе басқа биржадағы perpetual bid бағасымен салыстырады. Әр жол уақыт сапасын көрсетеді; order жіберілмейді.",
  search: "Жұпты іздеу",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минималды болжамды айырма",
  minCapacity: "Үздік бағадағы минималды көлем",
  costs: "Жалпы шығын бағасы",
  costsHint: "Кіру/шығу комиссиялары, slippage, расталған funding кестесі, қаржыландыру және көрсетілген қайта теңгеру құны.",
  refreshEvery: "Автоматты жаңарту",
  off: "Өшірулі",
  seconds: "секунд",
  refresh: "Бағаларды жаңарту",
  updating: "Жаңартылуда",
  updated: "Жаңартылды",
  stale: "Бір немесе бірнеше дереккөз қолжетімсіз болғандықтан жуырдағы кэш көрсетілді.",
  truncated: "Сервер сәйкес бағыттардың тек бір бөлігін қайтарды. Рейтингке сүйенбес бұрын сервер сүзгілерін нақтылаңыз.",
  scanned: "Тексерілген жұп",
  matching: "Көрсетілген бағыт",
  bestEdge: "Үздік болжамды айырма",
  sourceHealth: "Нарық деректерінің көздері",
  clockHealth: "Биржа сағатын калибрлеу",
  clockCalibrated: "сағат калибрленген",
  clockDegraded: "сағат дәлдігі төмен",
  clockExpired: "сағат өлшемі ескірген",
  clockUnavailable: "сағат қолжетімсіз",
  clockMetrics: "ығысу {offset} мс ± {uncertainty} мс · RTT {rtt} мс",
  clockWarning: "Биржааралық уақыт калибрлеуі толық емес. Барлық қажетті биржа калибрленгенше уақыт салыстыруы зерттеу режимінде қалады.",
  clockRequestFailed: "Биржа сағатының диагностикасы уақытша қолжетімсіз.",
  spot: "spot",
  perpetual: "мерзімсіз фьючерс",
  connected: "қосылған",
  unavailable: "қолжетімсіз",
  results: "Биржаішілік және биржааралық spot/perpetual зерттеу кандидаттары",
  signalQualityFresh: "уақыты расталған",
  signalQualityStale: "уақыты ескірген",
  signalQualitySkewed: "уақыты сәйкес емес",
  signalQualityUnverified: "уақыты расталмаған",
  pair: "Жұп",
  buySpot: "Spot сатып алу",
  shortPerpetual: "Perpetual short",
  grossSpread: "Жалпы айырма",
  netEdge: "Болжамды айырма",
  expectedProfit: "Болжамды P&L",
  capacity: "Үздік бағадағы көлем",
  funding: "Funding мөлшерлемесі",
  action: "График",
  openChart: "{symbol} графигін ашу",
  openSpotChart: "{venue} биржасында {symbol} spot графигін ашу",
  openPerpetualChart: "{venue} биржасында {symbol} perpetual графигін ашу",
  noResults: "Ағымдағы сүзгілерге сәйкес бағыт жоқ.",
  noResultsHint: "Минималды айырманы немесе көлемді азайтыңыз. Оң баға пайдаға кепілдік бермейді.",
  riskTitle: "Орындау тәуекелдері",
  risk: "Бағалар асинхронды snapshot болып табылады. Комиссия, slippage, funding, аударым уақыты, қарыз қолжетімділігі, позиция лимиттері және ликвидация көрінген айырманы жоюы мүмкін. Екі позицияны бөлек бақылау керек.",
  buyAt: "Сатып алу",
  sellAt: "Short бағасы",
  advancedSettings: "Комиссиялар, alert және симуляция",
  feeProfile: "Комиссия профилі",
  feeProfileHint: "Әр аяққа арналған taker комиссиялары. Баға кіру мен шығуды қамтиды.",
  binanceSpotFee: "Binance — спот",
  binancePerpetualFee: "Binance — мерзімсіз фьючерс",
  bybitSpotFee: "Bybit — спот",
  bybitPerpetualFee: "Bybit — мерзімсіз фьючерс",
  slippageReserve: "Екі бағыттағы slippage қоры",
  basisPointUnit: "б.п.",
  hourUnit: "сағ",
  holdingHours: "Күтілетін ұстау уақыты (сағат)",
  annualBorrowRate: "Жылдық қаржыландыру / қарыз мөлшерлемесі",
  transferCost: "Тұрақты аударым құны",
  costModelHint: "Таза айырма таңдалған сома үшін funding, қаржыландыру және тұрақты аударым құнын да бағалайды.",
  alertSettings: "Мүмкіндік alert-і",
  alertHint: "Бағыт шекті кесіп өткенде ғана іске қосылады. Telegram үшін paper-trade сессиясы керек.",
  enableAlerts: "Жұмыс үстелі және Telegram alert-тері",
  alertThreshold: "Таза айырма alert шегі",
  simulation: "Тереңдік және paper симуляциясы",
  simulationHint: "Стакандар тек сұрау бойынша алынады, order жіберілмейді.",
  notional: "Сынақ сомасы",
  connecting: "Қосылуда",
  live: "Нақты уақыт ағыны",
  fallback: "Қосалқы REST",
  paused: "Фонда тоқтатылды",
  marketDataUnavailable: "Арбитражға арналған нарық деректері уақытша қолжетімсіз.",
  actions: "Зерттеу әрекеттері",
  notificationRoute: "{spotVenue} {spotMarket} → {futuresVenue} {perpetualMarket}",
  analyzeDepth: "{symbol} стаканының тереңдігін талдау",
  openPaper: "{symbol} үшін екі аяқты paper позициясын ашу",
  paperRequiresFreshSignal: "Кандидат fresh емес. Екі кітап та жаңа расталған уақыт бермейінше depth және paper fail closed болады.",
  loadingDepth: "Екі стакан жүктелуде…",
  depthUnavailable: "Стакан тереңдігі уақытша қолжетімсіз.",
  exitDepthUnavailable: "Шығу стакандарының тереңдігі уақытша қолжетімсіз.",
  depthResult: "${amount} үшін тереңдік бағасы",
  spotVwap: "Spot сатып алу VWAP",
  perpetualVwap: "Perpetual short VWAP",
  depthNet: "Тереңдік ескерілген таза айырма",
  depthTiming: "Стакан жасы {age} мс · қабылдау айырмасы {skew} мс",
  depthExchangeSkew: "Биржа уақытының айырмасы {skew} мс",
  depthExchangePartial: "Бір немесе екі биржаның уақыты жоқ; жас тәуелсіз жергілікті қабылдау уақытымен есептелді.",
  depthQualityFresh: "Стакан уақыты қауіпсіз аралықта",
  depthQualityStale: "Стакан snapshot-ы ескірген",
  depthQualitySkewed: "Стакан уақыттарының айырмасы тым үлкен",
  depthQualityUnverified: "Стакан уақытын тексеру мүмкін болмады",
  levels: "деңгей",
  depthComplete: "Екі аяқта да көрінетін өтімділік жеткілікті",
  depthIncomplete: "Көрінетін тереңдік жеткіліксіз — paper кіру бұғатталды",
  paperPositions: "Арбитраж paper позициялары",
  paperOnly: "Жергілікті зерттеу журналы. Бұл биржа шоты емес және order жібермейді.",
  clearClosed: "Жабылғандарды тазалау",
  closePaper: "Paper жабу",
  closed: "Жабық",
  paperDepthBlocked: "Бір немесе екі стаканда тереңдік жеткіліксіз болғандықтан paper кіру бұғатталды.",
  paperExitBlocked: "Ашық quantity екі шығу стаканында да толық орындалмайтындықтан paper жабу бұғатталды.",
  paperOpened: "{symbol} paper позициясы ашылды.",
  paperClosed: "{symbol} paper позициясы шығу стакандарының VWAP бағасымен жабылды.",
  recordFunding: "Расталған funding-ті жазу",
  recordFundingHint: "Биржа тарихы немесе account statement растаған settlement-ті енгізіңіз. Ағымдағы ticker estimate автоматты түрде қолданылмайды.",
  fundingSettlementTime: "Settlement уақыты",
  fundingRateInput: "Settled rate (%)",
  fundingReferencePrice: "Settlement reference price (USD)",
  recordConfirmedFunding: "Funding event қосу",
  paperFundingRecorded: "{symbol} үшін қолмен расталған funding event жазылды.",
  fundingRecordFailed: "Расталған funding оқиғасын жазу мүмкін болмады.",
  paperFundingTotal: "Funding event-тері: {amount}",
  alertFired: "Арбитраж шегі {count} бағытта кесілді.",
  persistentAlerts: "Тұрақты Telegram ережесі",
  persistentAlertHint: "Браузер жабық кезде серверде жұмыс істейді. Тек хабарлама жібереді және order жасамайды.",
  saveServerAlert: "Сервер ережесін сақтау",
  signInForPersistent: "Сервер ережелерін сақтау үшін «Сауда» қойындысында paper-trade рұқсатымен кіріңіз.",
  savedRules: "Сақталған ережелер",
  deleteRule: "Тұрақты alert ережесін жою",
  ruleSaved: "Тұрақты ереже сақталды.",
  dismissNotice: "Хабарламаны жабу",
  opportunityHistory: "24 сағаттық мүмкіндік тарихы",
  historyEmpty: "Тарих сервер ағыны іске қосылғаннан кейін жинала бастайды.",
  previousPage: "Алдыңғы бет",
  nextPage: "Келесі бет",
  pageStatus: "{total} ішінен {from}–{to} көрсетілді",
  paperRealized: "Іске асқан P&L",
  paperUnrealized: "Ашық P&L",
  paperPartialPnl: "Ішінара: {amount}",
  paperPnlCoverage: "Бағаланған ашық позициялар: {known}/{total}",
  paperWinRate: "Жабылған ұтыс үлесі",
  paperAverage: "Жабылған орташа P&L"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function arbitrageText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}
