import type { Locale } from "../i18n";

const en = {
  title: "Cross-exchange arbitrage screener",
  description: "Compares executable spot asks with perpetual bids on another exchange. Read-only market research — no orders are placed.",
  search: "Search pair",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Minimum net edge",
  minCapacity: "Minimum top-book capacity",
  costs: "Estimated total costs",
  costsHint: "Entry and exit fees plus a slippage reserve. Funding and transfers are not included.",
  refreshEvery: "Auto refresh",
  off: "Off",
  seconds: "seconds",
  refresh: "Refresh quotes",
  updating: "Updating",
  updated: "Updated",
  stale: "Showing a recent cached snapshot because one or more sources are unavailable.",
  scanned: "Pairs scanned",
  matching: "Routes shown",
  bestEdge: "Best net edge",
  sourceHealth: "Market-data sources",
  spot: "spot",
  perpetual: "perpetual",
  connected: "connected",
  unavailable: "unavailable",
  results: "Executable cross-exchange spot/perpetual routes",
  pair: "Pair",
  buySpot: "Buy spot",
  shortPerpetual: "Short perpetual",
  grossSpread: "Gross spread",
  netEdge: "Net edge",
  capacity: "Top-book capacity",
  funding: "Funding rate",
  action: "Chart",
  openChart: "Open chart for {symbol}",
  noResults: "No routes match the current filters.",
  noResultsHint: "Lower the minimum edge or capacity. A positive quote is not guaranteed profit.",
  riskTitle: "Execution risks",
  risk: "Prices are asynchronous snapshots. Fees, slippage, funding, transfer time, borrow availability, position limits and liquidation risk can remove the apparent edge. Both legs must be managed independently.",
  buyAt: "Buy at",
  sellAt: "Short at",
  advancedSettings: "Fees, alerts and simulation",
  feeProfile: "Fee profile",
  feeProfileHint: "Your taker fees per leg. The route estimate includes entry and exit.",
  slippageReserve: "Round-trip slippage reserve",
  holdingHours: "Expected holding time (hours)",
  annualBorrowRate: "Annual financing / borrow rate",
  transferCost: "Fixed transfer cost",
  costModelHint: "Net edge also estimates funding, financing and a fixed transfer cost for the selected notional.",
  alertSettings: "Opportunity alert",
  alertHint: "Fires only when a route crosses the threshold. Telegram delivery requires a paper-trade session.",
  enableAlerts: "Desktop and Telegram alerts",
  alertThreshold: "Alert threshold",
  simulation: "Depth and paper simulation",
  simulationHint: "Order books are fetched only on request and never place an order.",
  notional: "Test notional",
  connecting: "Connecting",
  live: "Live stream",
  fallback: "REST fallback",
  paused: "Paused in background",
  actions: "Research actions",
  analyzeDepth: "Analyze order-book depth for {symbol}",
  openPaper: "Open paper two-leg position for {symbol}",
  loadingDepth: "Loading both order books…",
  depthResult: "Depth estimate for ${amount}",
  spotVwap: "Spot buy VWAP",
  perpetualVwap: "Perpetual short VWAP",
  depthNet: "Depth-adjusted net edge",
  levels: "levels",
  depthComplete: "Both legs have enough visible depth",
  depthIncomplete: "Visible depth is insufficient — paper entry blocked",
  paperPositions: "Paper arbitrage positions",
  paperOnly: "Local research ledger. It is not an exchange account and sends no orders.",
  clearClosed: "Clear closed",
  closePaper: "Close paper",
  closed: "Closed",
  paperDepthBlocked: "Paper entry was blocked because one or both books lack visible depth.",
  paperOpened: "Paper position opened for {symbol}.",
  alertFired: "Arbitrage threshold crossed on {count} route(s).",
  persistentAlerts: "Persistent Telegram rule",
  persistentAlertHint: "Runs on the server while the browser is closed. It only sends a notification and never places orders.",
  saveServerAlert: "Save server rule",
  signInForPersistent: "Sign in on the Trade tab with paper-trade access to save server rules.",
  savedRules: "Saved rules",
  deleteRule: "Delete persistent alert rule",
  ruleSaved: "Persistent rule saved.",
  opportunityHistory: "24-hour opportunity history",
  historyEmpty: "History starts accumulating once the server feed is active.",
  previousPage: "Previous page",
  nextPage: "Next page",
  pageStatus: "Showing {from}–{to} of {total}",
  paperRealized: "Realized P&L",
  paperUnrealized: "Open P&L",
  paperWinRate: "Closed win rate",
  paperAverage: "Average closed P&L"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  title: "Межбиржевой арбитражный скринер",
  description: "Сравнивает исполнимую цену покупки на споте с bid бессрочного фьючерса другой биржи. Только исследование рынка — ордера не отправляются.",
  search: "Поиск пары",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минимальный чистый спред",
  minCapacity: "Минимальный объём в лучшей цене",
  costs: "Оценка общих издержек",
  costsHint: "Комиссии входа и выхода плюс запас на проскальзывание. Funding и переводы не включены.",
  refreshEvery: "Автообновление",
  off: "Выкл.",
  seconds: "секунд",
  refresh: "Обновить котировки",
  updating: "Обновление",
  updated: "Обновлено",
  stale: "Показан недавний кэш: один или несколько источников сейчас недоступны.",
  scanned: "Проверено пар",
  matching: "Показано маршрутов",
  bestEdge: "Лучший чистый спред",
  sourceHealth: "Источники рыночных данных",
  spot: "спот",
  perpetual: "бессрочный фьючерс",
  connected: "подключён",
  unavailable: "недоступен",
  results: "Исполнимые межбиржевые маршруты спот/фьючерс",
  pair: "Пара",
  buySpot: "Купить спот",
  shortPerpetual: "Шорт фьючерса",
  grossSpread: "Грязный спред",
  netEdge: "Чистый спред",
  capacity: "Объём в лучшей цене",
  funding: "Ставка funding",
  action: "График",
  openChart: "Открыть график {symbol}",
  noResults: "Под текущие фильтры маршруты не найдены.",
  noResultsHint: "Уменьшите минимальный спред или объём. Положительная котировка не гарантирует прибыль.",
  riskTitle: "Риски исполнения",
  risk: "Цены получены асинхронно. Комиссии, проскальзывание, funding, время перевода, доступность займа, лимиты позиции и ликвидация могут полностью убрать найденную разницу. Обе позиции необходимо контролировать отдельно.",
  buyAt: "Покупка по",
  sellAt: "Шорт по",
  advancedSettings: "Комиссии, алерты и симуляция",
  feeProfile: "Профиль комиссий",
  feeProfileHint: "Ваши taker-комиссии по каждой ноге. Расчёт учитывает вход и выход.",
  slippageReserve: "Запас на проскальзывание туда-обратно",
  holdingHours: "Ожидаемое удержание (часы)",
  annualBorrowRate: "Годовая ставка финансирования / займа",
  transferCost: "Фиксированная стоимость перевода",
  costModelHint: "Чистый спред также оценивает funding, финансирование и фиксированный перевод для выбранной суммы.",
  alertSettings: "Алерт возможности",
  alertHint: "Срабатывает только при пересечении порога. Для Telegram нужна paper-trade сессия.",
  enableAlerts: "Алерты на рабочий стол и в Telegram",
  alertThreshold: "Порог чистого спреда для алерта",
  simulation: "Глубина и paper-симуляция",
  simulationHint: "Стаканы загружаются только по запросу, ордера никогда не отправляются.",
  notional: "Тестовая сумма",
  connecting: "Подключение",
  live: "Поток в реальном времени",
  fallback: "Резервный REST",
  paused: "Пауза в фоне",
  actions: "Инструменты исследования",
  analyzeDepth: "Проверить глубину стакана для {symbol}",
  openPaper: "Открыть paper-позицию из двух ног для {symbol}",
  loadingDepth: "Загрузка двух стаканов…",
  depthResult: "Оценка глубины для ${amount}",
  spotVwap: "VWAP покупки спота",
  perpetualVwap: "VWAP шорта фьючерса",
  depthNet: "Чистый спред с учётом глубины",
  levels: "уровней",
  depthComplete: "В обеих ногах достаточно видимой ликвидности",
  depthIncomplete: "Видимой глубины недостаточно — paper-вход заблокирован",
  paperPositions: "Paper-позиции арбитража",
  paperOnly: "Локальный исследовательский журнал. Это не биржевой счёт, ордера не отправляются.",
  clearClosed: "Удалить закрытые",
  closePaper: "Закрыть paper",
  closed: "Закрыта",
  paperDepthBlocked: "Paper-вход заблокирован: в одном или обоих стаканах недостаточно видимой глубины.",
  paperOpened: "Paper-позиция по {symbol} открыта.",
  alertFired: "Порог арбитража пересечён на маршрутах: {count}.",
  persistentAlerts: "Постоянное Telegram-правило",
  persistentAlertHint: "Работает на сервере при закрытом браузере. Только отправляет уведомление и никогда не создаёт ордера.",
  saveServerAlert: "Сохранить серверное правило",
  signInForPersistent: "Войдите во вкладке «Торговля» с доступом paper-trade, чтобы сохранять серверные правила.",
  savedRules: "Сохранённые правила",
  deleteRule: "Удалить постоянное правило алерта",
  ruleSaved: "Постоянное правило сохранено.",
  opportunityHistory: "История возможности за 24 часа",
  historyEmpty: "История начнёт накапливаться после запуска серверного потока.",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  pageStatus: "Показано {from}–{to} из {total}",
  paperRealized: "Реализованный P&L",
  paperUnrealized: "P&L открытых",
  paperWinRate: "Доля прибыльных закрытых",
  paperAverage: "Средний P&L закрытых"
};

const kk: Record<Key, string> = {
  title: "Биржааралық арбитраж скринері",
  description: "Бір биржадағы орындалатын spot ask бағасын басқа биржадағы perpetual bid бағасымен салыстырады. Тек нарықты зерттеу — order жіберілмейді.",
  search: "Жұпты іздеу",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минималды таза айырма",
  minCapacity: "Үздік бағадағы минималды көлем",
  costs: "Жалпы шығын бағасы",
  costsHint: "Кіру және шығу комиссиялары мен slippage қоры. Funding және аударымдар кірмейді.",
  refreshEvery: "Автоматты жаңарту",
  off: "Өшірулі",
  seconds: "секунд",
  refresh: "Бағаларды жаңарту",
  updating: "Жаңартылуда",
  updated: "Жаңартылды",
  stale: "Бір немесе бірнеше дереккөз қолжетімсіз болғандықтан жуырдағы кэш көрсетілді.",
  scanned: "Тексерілген жұп",
  matching: "Көрсетілген бағыт",
  bestEdge: "Үздік таза айырма",
  sourceHealth: "Нарық деректерінің көздері",
  spot: "spot",
  perpetual: "мерзімсіз фьючерс",
  connected: "қосылған",
  unavailable: "қолжетімсіз",
  results: "Орындалатын биржааралық spot/perpetual бағыттары",
  pair: "Жұп",
  buySpot: "Spot сатып алу",
  shortPerpetual: "Perpetual short",
  grossSpread: "Жалпы айырма",
  netEdge: "Таза айырма",
  capacity: "Үздік бағадағы көлем",
  funding: "Funding мөлшерлемесі",
  action: "График",
  openChart: "{symbol} графигін ашу",
  noResults: "Ағымдағы сүзгілерге сәйкес бағыт жоқ.",
  noResultsHint: "Минималды айырманы немесе көлемді азайтыңыз. Оң баға пайдаға кепілдік бермейді.",
  riskTitle: "Орындау тәуекелдері",
  risk: "Бағалар асинхронды snapshot болып табылады. Комиссия, slippage, funding, аударым уақыты, қарыз қолжетімділігі, позиция лимиттері және ликвидация көрінген айырманы жоюы мүмкін. Екі позицияны бөлек бақылау керек.",
  buyAt: "Сатып алу",
  sellAt: "Short бағасы",
  advancedSettings: "Комиссиялар, alert және симуляция",
  feeProfile: "Комиссия профилі",
  feeProfileHint: "Әр аяққа арналған taker комиссиялары. Баға кіру мен шығуды қамтиды.",
  slippageReserve: "Екі бағыттағы slippage қоры",
  holdingHours: "Күтілетін ұстау уақыты (сағат)",
  annualBorrowRate: "Жылдық қаржыландыру / қарыз мөлшерлемесі",
  transferCost: "Тұрақты аударым құны",
  costModelHint: "Таза айырма таңдалған сома үшін funding, қаржыландыру және тұрақты аударым құнын да бағалайды.",
  alertSettings: "Мүмкіндік alert-і",
  alertHint: "Бағыт шекті кесіп өткенде ғана іске қосылады. Telegram үшін paper-trade сессиясы керек.",
  enableAlerts: "Жұмыс үстелі және Telegram alert-тері",
  alertThreshold: "Таза айырма alert шегі",
  simulation: "Тереңдік және paper симуляциясы",
  simulationHint: "Стакандар тек сұрау бойынша алынады, order жіберілмейді.",
  notional: "Сынақ сомасы",
  connecting: "Қосылуда",
  live: "Нақты уақыт ағыны",
  fallback: "Қосалқы REST",
  paused: "Фонда тоқтатылды",
  actions: "Зерттеу әрекеттері",
  analyzeDepth: "{symbol} стаканының тереңдігін талдау",
  openPaper: "{symbol} үшін екі аяқты paper позициясын ашу",
  loadingDepth: "Екі стакан жүктелуде…",
  depthResult: "${amount} үшін тереңдік бағасы",
  spotVwap: "Spot сатып алу VWAP",
  perpetualVwap: "Perpetual short VWAP",
  depthNet: "Тереңдік ескерілген таза айырма",
  levels: "деңгей",
  depthComplete: "Екі аяқта да көрінетін өтімділік жеткілікті",
  depthIncomplete: "Көрінетін тереңдік жеткіліксіз — paper кіру бұғатталды",
  paperPositions: "Арбитраж paper позициялары",
  paperOnly: "Жергілікті зерттеу журналы. Бұл биржа шоты емес және order жібермейді.",
  clearClosed: "Жабылғандарды тазалау",
  closePaper: "Paper жабу",
  closed: "Жабық",
  paperDepthBlocked: "Бір немесе екі стаканда тереңдік жеткіліксіз болғандықтан paper кіру бұғатталды.",
  paperOpened: "{symbol} paper позициясы ашылды.",
  alertFired: "Арбитраж шегі {count} бағытта кесілді.",
  persistentAlerts: "Тұрақты Telegram ережесі",
  persistentAlertHint: "Браузер жабық кезде серверде жұмыс істейді. Тек хабарлама жібереді және order жасамайды.",
  saveServerAlert: "Сервер ережесін сақтау",
  signInForPersistent: "Сервер ережелерін сақтау үшін «Сауда» қойындысында paper-trade рұқсатымен кіріңіз.",
  savedRules: "Сақталған ережелер",
  deleteRule: "Тұрақты alert ережесін жою",
  ruleSaved: "Тұрақты ереже сақталды.",
  opportunityHistory: "24 сағаттық мүмкіндік тарихы",
  historyEmpty: "Тарих сервер ағыны іске қосылғаннан кейін жинала бастайды.",
  previousPage: "Алдыңғы бет",
  nextPage: "Келесі бет",
  pageStatus: "{total} ішінен {from}–{to} көрсетілді",
  paperRealized: "Іске асқан P&L",
  paperUnrealized: "Ашық P&L",
  paperWinRate: "Жабылған ұтыс үлесі",
  paperAverage: "Жабылған орташа P&L"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function arbitrageText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}
