import type { Locale } from "../i18n";

const en = {
  title: "Cross-exchange arbitrage screener",
  description: "Compares executable spot asks with perpetual bids on another exchange. Read-only market research — no orders are placed.",
  search: "Search pair",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Minimum net edge",
  minCapacity: "Minimum top-book capacity",
  costs: "Estimated total costs",
  costsHint: "Entry and exit fees plus a slippage reserve. Funding and transfers are not included.",
  refreshEvery: "Auto refresh",
  off: "Off",
  seconds: "seconds",
  refresh: "Refresh quotes",
  updating: "Updating",
  updated: "Updated",
  stale: "Showing a recent cached snapshot because one or more sources are unavailable.",
  scanned: "Pairs scanned",
  matching: "Routes shown",
  bestEdge: "Best net edge",
  sourceHealth: "Market-data sources",
  spot: "spot",
  perpetual: "perpetual",
  connected: "connected",
  unavailable: "unavailable",
  results: "Executable cross-exchange spot/perpetual routes",
  pair: "Pair",
  buySpot: "Buy spot",
  shortPerpetual: "Short perpetual",
  grossSpread: "Gross spread",
  netEdge: "Net edge",
  capacity: "Top-book capacity",
  funding: "Funding rate",
  action: "Chart",
  openChart: "Open chart for {symbol}",
  noResults: "No routes match the current filters.",
  noResultsHint: "Lower the minimum edge or capacity. A positive quote is not guaranteed profit.",
  riskTitle: "Execution risks",
  risk: "Prices are asynchronous snapshots. Fees, slippage, funding, transfer time, borrow availability, position limits and liquidation risk can remove the apparent edge. Both legs must be managed independently.",
  buyAt: "Buy at",
  sellAt: "Short at"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  title: "Межбиржевой арбитражный скринер",
  description: "Сравнивает исполнимую цену покупки на споте с bid бессрочного фьючерса другой биржи. Только исследование рынка — ордера не отправляются.",
  search: "Поиск пары",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минимальный чистый спред",
  minCapacity: "Минимальный объём в лучшей цене",
  costs: "Оценка общих издержек",
  costsHint: "Комиссии входа и выхода плюс запас на проскальзывание. Funding и переводы не включены.",
  refreshEvery: "Автообновление",
  off: "Выкл.",
  seconds: "секунд",
  refresh: "Обновить котировки",
  updating: "Обновление",
  updated: "Обновлено",
  stale: "Показан недавний кэш: один или несколько источников сейчас недоступны.",
  scanned: "Проверено пар",
  matching: "Показано маршрутов",
  bestEdge: "Лучший чистый спред",
  sourceHealth: "Источники рыночных данных",
  spot: "спот",
  perpetual: "бессрочный фьючерс",
  connected: "подключён",
  unavailable: "недоступен",
  results: "Исполнимые межбиржевые маршруты спот/фьючерс",
  pair: "Пара",
  buySpot: "Купить спот",
  shortPerpetual: "Шорт фьючерса",
  grossSpread: "Грязный спред",
  netEdge: "Чистый спред",
  capacity: "Объём в лучшей цене",
  funding: "Ставка funding",
  action: "График",
  openChart: "Открыть график {symbol}",
  noResults: "Под текущие фильтры маршруты не найдены.",
  noResultsHint: "Уменьшите минимальный спред или объём. Положительная котировка не гарантирует прибыль.",
  riskTitle: "Риски исполнения",
  risk: "Цены получены асинхронно. Комиссии, проскальзывание, funding, время перевода, доступность займа, лимиты позиции и ликвидация могут полностью убрать найденную разницу. Обе позиции необходимо контролировать отдельно.",
  buyAt: "Покупка по",
  sellAt: "Шорт по"
};

const kk: Record<Key, string> = {
  title: "Биржааралық арбитраж скринері",
  description: "Бір биржадағы орындалатын spot ask бағасын басқа биржадағы perpetual bid бағасымен салыстырады. Тек нарықты зерттеу — order жіберілмейді.",
  search: "Жұпты іздеу",
  searchPlaceholder: "BTCUSDT",
  minEdge: "Минималды таза айырма",
  minCapacity: "Үздік бағадағы минималды көлем",
  costs: "Жалпы шығын бағасы",
  costsHint: "Кіру және шығу комиссиялары мен slippage қоры. Funding және аударымдар кірмейді.",
  refreshEvery: "Автоматты жаңарту",
  off: "Өшірулі",
  seconds: "секунд",
  refresh: "Бағаларды жаңарту",
  updating: "Жаңартылуда",
  updated: "Жаңартылды",
  stale: "Бір немесе бірнеше дереккөз қолжетімсіз болғандықтан жуырдағы кэш көрсетілді.",
  scanned: "Тексерілген жұп",
  matching: "Көрсетілген бағыт",
  bestEdge: "Үздік таза айырма",
  sourceHealth: "Нарық деректерінің көздері",
  spot: "spot",
  perpetual: "мерзімсіз фьючерс",
  connected: "қосылған",
  unavailable: "қолжетімсіз",
  results: "Орындалатын биржааралық spot/perpetual бағыттары",
  pair: "Жұп",
  buySpot: "Spot сатып алу",
  shortPerpetual: "Perpetual short",
  grossSpread: "Жалпы айырма",
  netEdge: "Таза айырма",
  capacity: "Үздік бағадағы көлем",
  funding: "Funding мөлшерлемесі",
  action: "График",
  openChart: "{symbol} графигін ашу",
  noResults: "Ағымдағы сүзгілерге сәйкес бағыт жоқ.",
  noResultsHint: "Минималды айырманы немесе көлемді азайтыңыз. Оң баға пайдаға кепілдік бермейді.",
  riskTitle: "Орындау тәуекелдері",
  risk: "Бағалар асинхронды snapshot болып табылады. Комиссия, slippage, funding, аударым уақыты, қарыз қолжетімділігі, позиция лимиттері және ликвидация көрінген айырманы жоюы мүмкін. Екі позицияны бөлек бақылау керек.",
  buyAt: "Сатып алу",
  sellAt: "Short бағасы"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function arbitrageText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}
