import type { Locale } from "../i18n";

const en = {
  scannerMode: "Arbitrage scanner mode",
  basisMode: "Spot ↔ perpetual",
  triangularMode: "Triangular",
  eyebrow: "{venue} · spot · 3 legs",
  title: "Triangular arbitrage screener",
  description: "Simulates three consecutive spot conversions from one venue-wide REST top-book snapshot, venue precision and fees. It is a candidate estimate and never places orders.",
  venue: "Exchange",
  startAsset: "Start asset",
  amount: "Start amount",
  fee: "Taker fee per leg",
  minimumReturn: "Minimum net return",
  scan: "Scan routes",
  scanning: "Scanning…",
  scannerUnavailable: "The triangular scanner is temporarily unavailable.",
  updated: "Updated",
  markets: "Markets used",
  cycles: "Cycles checked",
  opportunities: "Opportunities",
  bestReturn: "Best net return",
  results: "Three-leg top-book simulations",
  route: "Conversion route",
  leg: "Leg {index}",
  grossReturn: "Gross return",
  netReturn: "Net return",
  result: "Start → end",
  capacity: "Simulated top-book capacity",
  quality: "Data quality",
  action: "Actions",
  openChart: "Open {symbol} chart",
  verifyDepth: "Verify this route with sequence-reconstructed L2 depth",
  verifyingDepth: "Verifying this route with live L2 depth",
  verifyDepthShort: "Verify L2",
  verifyingDepthShort: "Verifying…",
  verificationRunningTitle: "Reconstructing all three order books",
  verificationRunningBody: "The server is bridging snapshots and WebSocket deltas, then checking depth, fees, lot steps, age and leg skew.",
  verificationFailedTitle: "L2 verification is temporarily unavailable",
  verificationFailedBody: "A book may be resynchronizing, rate-limited or no longer current. No optimistic result was retained; retry after the streams recover.",
  verificationPassedTitle: "Route passed sequence-verified depth simulation",
  verificationPassedBody: "All three current books passed continuity and depth checks. This is a stronger paper candidate, not an order or profit guarantee.",
  verificationRejectedTitle: "The top-book candidate did not survive depth verification",
  verificationRejectedBody: "The current reconstructed books fail profitability, capacity, freshness or synchronization requirements. The route remains rejected.",
  verifiedNetReturn: "Verified net return",
  verifiedCapacity: "Visible executable capacity",
  verifiedAge: "Oldest quote age",
  verifiedLevels: "Levels used by legs",
  verificationEvidence: "Sequence evidence",
  verificationBoundary: "Read-only research: no API keys, balances or orders are used. Sequence verification does not make three sequential orders atomic.",
  noResults: "No profitable three-leg routes match these settings.",
  noResultsHint: "Try another start asset or a realistic fee tier. An empty result is safer than an optimistic quote.",
  truncated: "Only the highest-ranked part of the result was returned.",
  riskTitle: "Sequential execution risk",
  risk: "The scan uses a REST top-of-book snapshot. Prices can change between all three orders; partial fills, fees, rounding, minimum order rules and inventory risk can turn the route negative. Revalidate every leg immediately before execution.",
  topBook: "top book",
  restSnapshot: "REST snapshot",
  nonExecutableCandidate: "research candidate · not sequence-verified",
  quoteAge: "age {value} ms",
  legSkew: "leg skew {value} ms",
  buy: "buy",
  sell: "sell"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  scannerMode: "Режим арбитражного скринера",
  basisMode: "Спот ↔ perpetual",
  triangularMode: "Треугольный",
  eyebrow: "{venue} · спот · 3 ноги",
  title: "Скринер треугольного арбитража",
  description: "Моделирует три последовательные спот-конвертации по одному общебиржевому REST-снимку лучших цен, правилам точности и комиссиям. Это оценка кандидата, ордера не отправляются.",
  venue: "Биржа",
  startAsset: "Стартовый актив",
  amount: "Стартовая сумма",
  fee: "Taker-комиссия за ногу",
  minimumReturn: "Минимальная чистая доходность",
  scan: "Проверить маршруты",
  scanning: "Проверка…",
  scannerUnavailable: "Скринер треугольного арбитража временно недоступен.",
  updated: "Обновлено",
  markets: "Использовано рынков",
  cycles: "Проверено циклов",
  opportunities: "Возможностей",
  bestReturn: "Лучшая чистая доходность",
  results: "Top-book симуляции маршрутов из трёх ног",
  route: "Маршрут конвертации",
  leg: "Нога {index}",
  grossReturn: "Грязная доходность",
  netReturn: "Чистая доходность",
  result: "Старт → результат",
  capacity: "Смоделированная ёмкость top-book",
  quality: "Качество данных",
  action: "Действия",
  openChart: "Открыть график {symbol}",
  verifyDepth: "Проверить маршрут по восстановленной sequence-verified глубине L2",
  verifyingDepth: "Маршрут проверяется по актуальной глубине L2",
  verifyDepthShort: "Проверить L2",
  verifyingDepthShort: "Проверка…",
  verificationRunningTitle: "Восстанавливаются все три стакана",
  verificationRunningBody: "Сервер связывает снимки с WebSocket-дельтами, затем проверяет глубину, комиссии, шаги количества, возраст и рассинхронизацию ног.",
  verificationFailedTitle: "Проверка L2 временно недоступна",
  verificationFailedBody: "Один из стаканов может пересинхронизироваться, быть ограничен rate limit или уже устареть. Оптимистичный результат не сохранён; повторите после восстановления потоков.",
  verificationPassedTitle: "Маршрут прошёл симуляцию по sequence-verified глубине",
  verificationPassedBody: "Все три актуальных стакана прошли проверку непрерывности и глубины. Это более сильный paper-кандидат, но не ордер и не гарантия прибыли.",
  verificationRejectedTitle: "Top-book кандидат не выдержал проверку глубины",
  verificationRejectedBody: "Текущие восстановленные стаканы не проходят требования доходности, ёмкости, свежести или синхронности. Маршрут отклонён.",
  verifiedNetReturn: "Проверенная чистая доходность",
  verifiedCapacity: "Исполнимая видимая ёмкость",
  verifiedAge: "Возраст самой старой котировки",
  verifiedLevels: "Использовано уровней по ногам",
  verificationEvidence: "Доказательство sequence",
  verificationBoundary: "Только read-only исследование: API-ключи, балансы и ордера не используются. Проверка sequence не делает три последовательных ордера атомарными.",
  noResults: "При этих параметрах прибыльных трёхногих маршрутов нет.",
  noResultsHint: "Попробуйте другой стартовый актив или реальный тариф комиссии. Пустой результат безопаснее оптимистичной котировки.",
  truncated: "Показана только верхняя часть рейтинга.",
  riskTitle: "Риск последовательного исполнения",
  risk: "Расчёт использует REST-снимок лучших цен. Между тремя ордерами цена может измениться; частичное исполнение, комиссии, округление, минимумы ордеров и остатки активов могут сделать маршрут убыточным. Каждую ногу нужно перепроверять непосредственно перед исполнением.",
  topBook: "лучшая цена",
  restSnapshot: "REST-снимок",
  nonExecutableCandidate: "исследовательский кандидат · без проверки sequence",
  quoteAge: "возраст {value} мс",
  legSkew: "рассинхронизация {value} мс",
  buy: "покупка",
  sell: "продажа"
};

const kk: Record<Key, string> = {
  scannerMode: "Арбитраж скринерінің режимі",
  basisMode: "Spot ↔ perpetual",
  triangularMode: "Үшбұрышты",
  eyebrow: "{venue} · спот · 3 аяқ",
  title: "Үшбұрышты арбитраж скринері",
  description: "Бір биржаның ортақ REST top-book snapshot-ы, precision ережелері және комиссиялары бойынша үш тізбекті spot конверсиясын модельдейді. Бұл candidate estimate, order жібермейді.",
  venue: "Биржа",
  startAsset: "Бастапқы актив",
  amount: "Бастапқы сома",
  fee: "Әр аяқтың taker комиссиясы",
  minimumReturn: "Минималды таза кіріс",
  scan: "Бағыттарды тексеру",
  scanning: "Тексерілуде…",
  scannerUnavailable: "Үшбұрышты арбитраж скринері уақытша қолжетімсіз.",
  updated: "Жаңартылды",
  markets: "Қолданылған нарық",
  cycles: "Тексерілген цикл",
  opportunities: "Мүмкіндік",
  bestReturn: "Үздік таза кіріс",
  results: "Үш аяқты top-book симуляциялары",
  route: "Конверсия бағыты",
  leg: "{index}-аяқ",
  grossReturn: "Жалпы кіріс",
  netReturn: "Таза кіріс",
  result: "Бастапқы → нәтиже",
  capacity: "Модельденген top-book сыйымдылығы",
  quality: "Дерек сапасы",
  action: "Әрекеттер",
  openChart: "{symbol} графигін ашу",
  verifyDepth: "Бағытты қалпына келтірілген sequence-verified L2 тереңдігімен тексеру",
  verifyingDepth: "Бағыт өзекті L2 тереңдігімен тексерілуде",
  verifyDepthShort: "L2 тексеру",
  verifyingDepthShort: "Тексерілуде…",
  verificationRunningTitle: "Үш order book та қалпына келтірілуде",
  verificationRunningBody: "Сервер snapshot пен WebSocket delta-ларын байланыстырып, тереңдікті, комиссияны, quantity қадамын, жасын және аяқтар ауытқуын тексереді.",
  verificationFailedTitle: "L2 тексеруі уақытша қолжетімсіз",
  verificationFailedBody: "Book қайта синхрондалып, rate limit-ке ұшырап немесе ескіріп қалуы мүмкін. Оптимистік нәтиже сақталмады; stream қалпына келгеннен кейін қайталаңыз.",
  verificationPassedTitle: "Бағыт sequence-verified тереңдік симуляциясынан өтті",
  verificationPassedBody: "Үш өзекті book та үздіксіздік және тереңдік тексеруінен өтті. Бұл күштірек paper candidate, бірақ order немесе пайда кепілдігі емес.",
  verificationRejectedTitle: "Top-book candidate тереңдік тексеруінен өтпеді",
  verificationRejectedBody: "Қазіргі қалпына келтірілген books кірістілік, сыйымдылық, freshness немесе synchronization талаптарына сай емес. Бағыт қабылданбады.",
  verifiedNetReturn: "Тексерілген таза кіріс",
  verifiedCapacity: "Орындалатын көрінетін сыйымдылық",
  verifiedAge: "Ең ескі бағаның жасы",
  verifiedLevels: "Аяқтар қолданған деңгейлер",
  verificationEvidence: "Sequence дәлелі",
  verificationBoundary: "Тек read-only зерттеу: API key, баланс немесе order қолданылмайды. Sequence тексеруі үш тізбекті order-ді атомдық етпейді.",
  noResults: "Осы параметрлерге сай пайдалы үш аяқты бағыт табылмады.",
  noResultsHint: "Басқа бастапқы активті немесе нақты комиссия тарифін қолданып көріңіз. Бос нәтиже тым оптимистік бағадан қауіпсіз.",
  truncated: "Рейтингтің тек жоғарғы бөлігі көрсетілді.",
  riskTitle: "Тізбекті орындау тәуекелі",
  risk: "Есеп үздік бағалардың REST snapshot-ын пайдаланады. Үш order арасында баға өзгеруі мүмкін; жартылай орындалу, комиссия, дөңгелектеу, order минимумдары және актив қалдығы бағытты шығынды етуі мүмкін. Әр аяқ орындалу алдында қайта тексерілуі тиіс.",
  topBook: "үздік баға",
  restSnapshot: "REST snapshot",
  nonExecutableCandidate: "зерттеу кандидаты · sequence расталмаған",
  quoteAge: "жасы {value} мс",
  legSkew: "аяқ ауытқуы {value} мс",
  buy: "сатып алу",
  sell: "сату"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function triangularText(locale: Locale, key: Key, values: Record<string, string> = {}): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), messages[locale][key]);
}
