export const CONTINUOUS_MARKET_ECONOMICS_ENGINE = "continuous-market-economics-v1";
export const CONTINUOUS_PUBLIC_TAKER_FEE_POLICY_VERSION = "continuous-public-taker-fee-v1";
export const CONTINUOUS_MARKET_BLOCK_CODES = [
    "missing-instrument",
    "missing-top-book",
    "feed-not-live",
    "generation-mismatch",
    "invalid-top-book",
    "unverified-continuity",
    "stale-top-book",
    "future-top-book",
    "expiry-boundary",
    "skewed-top-books",
    "quantity-unit-mismatch",
    "unsupported-quantity-precision",
    "no-common-quantity",
    "minimum-quantity",
    "minimum-notional",
    "derived-arithmetic-invalid",
    "economic-identity-invalid",
    "economic-identity-not-yet-valid",
    "economic-identity-expired",
    "clock-unavailable",
    "clock-not-calibrated",
    "timestamp-definitely-future",
    "timestamp-may-be-future",
    "timestamp-stale",
    "clock-skew-exceeded",
    "account-capital-missing",
    "account-inventory-missing",
    "network-rebalance-missing",
    "borrow-evidence-missing",
    "funding-horizon-missing",
    "derivative-margin-missing",
    "convergence-evidence-missing",
    "expiry-delivery-evidence-missing"
];
