import { randomBytes, timingSafeEqual } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { NextFunction, Request, Response } from "express";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "../data");
const tokenPath = path.join(dataDir, ".authtoken");

let cachedToken: string | null = null;
let autoGenerated = false;

/**
 * The access token that guards the trading API. Precedence:
 *   1. process.env.AUTH_TOKEN (operator-supplied, never persisted)
 *   2. backend/data/.authtoken (auto-generated on first run, git-ignored)
 * The token is required for every /api/trade route and the /trade-stream socket.
 */
export function getAuthToken(): string {
  if (cachedToken) return cachedToken;
  const fromEnv = process.env.AUTH_TOKEN?.trim();
  if (fromEnv) {
    cachedToken = fromEnv;
    autoGenerated = false;
    return cachedToken;
  }
  if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
  if (existsSync(tokenPath)) {
    const saved = readFileSync(tokenPath, "utf8").trim();
    if (saved) {
      cachedToken = saved;
      autoGenerated = true;
      return cachedToken;
    }
  }
  const generated = randomBytes(24).toString("base64url");
  writeFileSync(tokenPath, generated, { mode: 0o600 });
  cachedToken = generated;
  autoGenerated = true;
  return cachedToken;
}

export function isAutoGeneratedToken(): boolean {
  getAuthToken();
  return autoGenerated;
}

/** DEMO_MODE disables key storage + live trading and opens the read-only surface. */
export function isDemoMode(): boolean {
  return process.env.DEMO_MODE === "1" || process.env.DEMO_MODE === "true";
}

/** Constant-time token comparison — avoids leaking length/prefix via timing. */
export function verifyToken(candidate: string | undefined | null): boolean {
  if (!candidate) return false;
  const expected = Buffer.from(getAuthToken());
  const given = Buffer.from(candidate);
  if (expected.length !== given.length) return false;
  return timingSafeEqual(expected, given);
}

/** Extract a bearer token from an Authorization header or a `token`/`access_token` query param. */
export function extractToken(req: { headers: Record<string, unknown>; query?: Record<string, unknown> }): string | undefined {
  const header = req.headers["authorization"];
  if (typeof header === "string" && header.toLowerCase().startsWith("bearer ")) {
    return header.slice(7).trim();
  }
  const q = req.query?.token ?? req.query?.access_token;
  if (typeof q === "string") return q;
  return undefined;
}

/** Express middleware: 401 unless a valid token is presented. */
export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  if (verifyToken(extractToken(req))) {
    next();
    return;
  }
  res.status(401).json({ error: "Unauthorized — a valid access token is required." });
}

/** Validate a token carried in a WebSocket upgrade URL (query param). */
export function verifyWsToken(url: URL): boolean {
  return verifyToken(url.searchParams.get("token") ?? url.searchParams.get("access_token"));
}
