import { randomBytes, timingSafeEqual } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { NextFunction, Request, Response } from "express";
import type { AuthRole } from "./trading/types.js";
import { csrfFromRequest, principalFromRequest, readCookie, requestNeedsCsrf, sessionCookieName } from "./identity/http.js";
import { IdentityError, type IdentityService } from "./identity/service.js";
import type { IdentityPrincipal } from "./identity/types.js";
import { isPaperOnlyRuntime } from "./runtimeProfile.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "../data");
const tokenPath = path.join(dataDir, ".authtoken");

let cachedToken: string | null = null;
let autoGenerated = false;
let generatedThisRun = false;

const sessionCookie = "sbv2_session";
const sessionTtlMs = Number(process.env.AUTH_SESSION_TTL_MS ?? 12 * 60 * 60 * 1000);
const wsTicketTtlMs = Number(process.env.AUTH_WS_TICKET_TTL_MS ?? 30_000);

interface AuthSession {
  csrfToken: string;
  role: AuthRole;
  expiresAt: number;
}

const sessions = new Map<string, AuthSession>();
const wsTickets = new Map<string, number>();
let databaseIdentity: IdentityService | undefined;

export function configureIdentityAuth(service: IdentityService | undefined): void {
  databaseIdentity = service;
}

export function getIdentityAuth(): IdentityService | undefined {
  return databaseIdentity;
}

export function isDatabaseAuthMode(): boolean {
  return databaseIdentity !== undefined || process.env.AUTH_MODE === "database";
}

/**
 * Legacy/demo access token. Database-auth production never calls this path. Precedence:
 *   1. process.env.AUTH_TOKEN (operator-supplied, never persisted)
 *   2. backend/data/.authtoken (auto-generated on first run, git-ignored)
 * The token is required for every /api/trade route and the /trade-stream socket.
 */
export function getAuthToken(): string {
  if (cachedToken) return cachedToken;
  const fromEnv = process.env.AUTH_TOKEN?.trim();
  if (fromEnv) {
    cachedToken = fromEnv;
    autoGenerated = false;
    generatedThisRun = false;
    return cachedToken;
  }
  if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
  if (existsSync(tokenPath)) {
    const saved = readFileSync(tokenPath, "utf8").trim();
    if (saved) {
      cachedToken = saved;
      autoGenerated = true;
      generatedThisRun = false;
      return cachedToken;
    }
  }
  const generated = randomBytes(24).toString("base64url");
  writeFileSync(tokenPath, generated, { mode: 0o600 });
  cachedToken = generated;
  autoGenerated = true;
  generatedThisRun = true;
  return cachedToken;
}

export function isAutoGeneratedToken(): boolean {
  getAuthToken();
  return autoGenerated;
}

/** True only when this process created a new token file during startup. */
export function wasAuthTokenGeneratedThisRun(): boolean {
  getAuthToken();
  return generatedThisRun;
}

/** Compatibility facade for older clients. New code should use runtimeProfile. */
export function isDemoMode(): boolean {
  return isPaperOnlyRuntime();
}

/** Constant-time token comparison — avoids leaking length/prefix via timing. */
export function verifyToken(candidate: string | undefined | null): boolean {
  return roleForToken(candidate) !== undefined;
}

export function roleForToken(candidate: string | undefined | null): AuthRole | undefined {
  if (isDatabaseAuthMode()) return undefined;
  if (!candidate) return undefined;
  const candidates: Array<[AuthRole, string | undefined]> = [
    ["admin", getAuthToken()],
    ["live-trade", process.env.AUTH_LIVE_TRADE_TOKEN?.trim()],
    ["paper-trade", process.env.AUTH_PAPER_TRADE_TOKEN?.trim()],
    ["read-only", process.env.AUTH_READONLY_TOKEN?.trim()]
  ];
  for (const [role, token] of candidates) {
    if (constantTimeEqual(candidate, token)) return role;
  }
  return undefined;
}

export function roleAllows(actual: AuthRole | undefined, required: AuthRole): boolean {
  if (!actual) return false;
  return roleRank(actual) >= roleRank(required);
}

export function roleRank(role: AuthRole): number {
  switch (role) {
    case "admin":
      return 3;
    case "live-trade":
      return 2;
    case "paper-trade":
      return 1;
    case "read-only":
      return 0;
  }
}

export interface TradingAuthorizationLease {
  /** Must be called synchronously immediately before the protected mutation. */
  assertCurrent(): boolean;
}

/**
 * Revalidate database authorization after a request waited behind a lifecycle
 * lock. Legacy sessions are rechecked against their immutable request role.
 */
export async function revalidateTradingAuthorization(res: Response, required: AuthRole): Promise<TradingAuthorizationLease | undefined> {
  if (!databaseIdentity) {
    if (process.env.AUTH_MODE === "database") {
      res.status(503).json({ error: "Authentication database is unavailable.", code: "auth_unavailable" });
      return undefined;
    }
    return authorizationLease(res, () => roleAllows(res.locals.authRole as AuthRole | undefined, required));
  }
  const stale = res.locals.authPrincipal as IdentityPrincipal | undefined;
  const current = stale && (await databaseIdentity.revalidatePrincipal(stale));
  if (!current || current.user.id !== res.locals.authUserId) {
    res.status(401).json({ error: "Authentication changed while the request was queued.", code: "authorization_stale" });
    return undefined;
  }
  if (!roleAllows(current.effectiveTradingRole, required)) {
    res.status(403).json({ error: `Forbidden — requires ${required} access.`, code: "trading_not_allowed" });
    return undefined;
  }
  res.locals.authPrincipal = current;
  res.locals.appRole = current.user.appRole;
  res.locals.tradingRole = current.user.tradingRole;
  res.locals.authRole = current.effectiveTradingRole;
  return authorizationLease(res, () => databaseIdentity?.isAuthorizationCurrent(current) === true && roleAllows(current.effectiveTradingRole, required));
}

function authorizationLease(res: Response, current: () => boolean): TradingAuthorizationLease {
  return {
    assertCurrent() {
      if (current()) return true;
      if (!res.headersSent) res.status(401).json({ error: "Authentication changed while the request was queued.", code: "authorization_stale" });
      return false;
    }
  };
}

/** Extract a bearer token from an Authorization header. */
export function extractToken(req: { headers: Record<string, unknown>; query?: Record<string, unknown> }): string | undefined {
  const header = req.headers["authorization"];
  if (typeof header === "string" && header.toLowerCase().startsWith("bearer ")) {
    return header.slice(7).trim();
  }
  return undefined;
}

export function createAuthSession(res: Response, role: AuthRole): { csrfToken: string; role: AuthRole; expiresAt: number } {
  pruneSessions();
  const sessionId = randomBytes(32).toString("base64url");
  const session: AuthSession = {
    csrfToken: randomBytes(32).toString("base64url"),
    role,
    expiresAt: Date.now() + sessionTtlMs
  };
  sessions.set(sessionId, session);
  res.setHeader("Set-Cookie", formatSessionCookie(sessionId, Math.floor(sessionTtlMs / 1000)));
  return { csrfToken: session.csrfToken, role: session.role, expiresAt: session.expiresAt };
}

export function clearAuthSession(req: Request, res: Response): void | Promise<void> {
  if (databaseIdentity) return clearDatabaseSession(databaseIdentity, req, res);
  const sessionId = readCookie(req.headers.cookie, sessionCookie);
  if (sessionId) sessions.delete(sessionId);
  res.setHeader("Set-Cookie", formatSessionCookie("", 0));
}

export function requestCsrfToken(req: Request): string | undefined {
  return readSession(req)?.csrfToken;
}

export function issueWsTicket(): { ticket: string; expiresAt: number } {
  pruneWsTickets();
  const ticket = randomBytes(32).toString("base64url");
  const expiresAt = Date.now() + wsTicketTtlMs;
  wsTickets.set(ticket, expiresAt);
  return { ticket, expiresAt };
}

export async function issueWsTicketForRequest(req: Request, res: Response): Promise<{ ticket: string; expiresAt: number }> {
  if (!databaseIdentity) return issueWsTicket();
  const principal = res.locals.authPrincipal as IdentityPrincipal | undefined;
  if (!principal) throw new IdentityError(401, "not_authenticated", "Authentication is required.");
  const issued = await databaseIdentity.issueWsTicket(principal);
  return { ticket: issued.ticket, expiresAt: issued.expiresAt.getTime() };
}

/** Express middleware: 401 unless a valid token is presented. */
export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  if (databaseIdentity) {
    void requireDatabaseAuth(databaseIdentity, req, res, next, true);
    return;
  }
  if (process.env.AUTH_MODE === "database") {
    res.status(503).json({ error: "Authentication database is unavailable.", code: "auth_unavailable" });
    return;
  }
  const bearerRole = roleForToken(extractToken(req));
  if (bearerRole) {
    res.locals.authMode = "bearer";
    res.locals.authRole = bearerRole;
    next();
    return;
  }
  const session = readSession(req);
  if (session) {
    if (requiresCsrf(req) && req.headers["x-csrf-token"] !== session.csrfToken) {
      res.status(403).json({ error: "Forbidden — missing or invalid CSRF token." });
      return;
    }
    res.locals.authMode = "session";
    res.locals.csrfToken = session.csrfToken;
    res.locals.authRole = session.role;
    next();
    return;
  }
  res.status(401).json({ error: "Unauthorized — a valid access token is required." });
}

/** Require an active application account. Trading permission is checked separately. */
export function requireAppAuth(req: Request, res: Response, next: NextFunction): void {
  if (!isDatabaseAuthMode()) {
    next();
    return;
  }
  if (!databaseIdentity) {
    res.status(503).json({ error: "Authentication database is unavailable.", code: "auth_unavailable" });
    return;
  }
  void requireDatabaseAuth(databaseIdentity, req, res, next, false);
}

/** Validate a one-time websocket ticket, with bearer subprotocol as a legacy API fallback. */
export function verifyWsToken(url: URL, protocolHeader?: unknown): boolean {
  void url;
  const ticket = extractWsProtocolValue(protocolHeader, "sbv2.ticket.");
  if (ticket && consumeWsTicket(ticket)) return true;
  const protocolToken = extractWsProtocolValue(protocolHeader, "sbv2.auth.");
  if (protocolToken && roleForToken(protocolToken)) return true;
  return false;
}

export async function verifyTradeWsRequest(protocolHeader?: unknown): Promise<IdentityPrincipal | boolean> {
  if (!databaseIdentity) return verifyWsToken(new URL("http://localhost/trade-stream"), protocolHeader);
  const ticket = extractWsProtocolValue(protocolHeader, "sbv2.ticket.");
  if (!ticket) return false;
  return (await databaseIdentity.consumeWsTicket(ticket)) ?? false;
}

export async function verifyAppWsSession(cookieHeader?: string): Promise<boolean> {
  if (!databaseIdentity) return process.env.AUTH_MODE !== "database";
  const token = readCookie(cookieHeader, sessionCookieName);
  const principal = await databaseIdentity.authenticate(token);
  return Boolean(principal && !principal.user.mustChangePassword);
}

async function requireDatabaseAuth(
  service: IdentityService,
  req: Request,
  res: Response,
  next: NextFunction,
  requireTradingRole: boolean
): Promise<void> {
  try {
    const principal = await principalFromRequest(service, req);
    if (!principal) {
      res.status(401).json({ error: "Authentication is required.", code: "not_authenticated" });
      return;
    }
    if (principal.user.mustChangePassword) {
      res.status(403).json({ error: "Change the temporary password before using the application.", code: "password_change_required" });
      return;
    }
    if (requestNeedsCsrf(req) && !service.verifyCsrf(principal, csrfFromRequest(req))) {
      res.status(403).json({ error: "Missing or invalid CSRF token.", code: "invalid_csrf" });
      return;
    }
    if (requireTradingRole && !principal.effectiveTradingRole) {
      res.status(403).json({ error: "Trading access has not been granted.", code: "trading_not_allowed" });
      return;
    }
    res.locals.authMode = "database";
    res.locals.authPrincipal = principal;
    res.locals.authUserId = principal.user.id;
    res.locals.appRole = principal.user.appRole;
    res.locals.tradingRole = principal.user.tradingRole;
    res.locals.authRole = principal.effectiveTradingRole;
    next();
  } catch (error) {
    next(error);
  }
}

async function clearDatabaseSession(service: IdentityService, req: Request, res: Response): Promise<void> {
  const principal = await principalFromRequest(service, req);
  await service.logout(principal);
  const secure = process.env.COOKIE_SECURE === "1" || process.env.COOKIE_SECURE === "true";
  const attributes = `SameSite=Strict; Path=/; Max-Age=0${secure ? "; Secure" : ""}`;
  res.append("Set-Cookie", `${sessionCookieName}=; HttpOnly; ${attributes}`);
  res.append("Set-Cookie", `sbv2_csrf=; ${attributes}`);
}

function constantTimeEqual(candidate: string, expected: string | undefined): boolean {
  if (!expected) return false;
  const expectedBuffer = Buffer.from(expected);
  const givenBuffer = Buffer.from(candidate);
  if (expectedBuffer.length !== givenBuffer.length) return false;
  return timingSafeEqual(expectedBuffer, givenBuffer);
}

function extractWsProtocolValue(header: unknown, prefix: string): string | undefined {
  if (typeof header !== "string") return undefined;
  for (const item of header.split(",")) {
    const protocol = item.trim();
    if (!protocol.startsWith(prefix)) continue;
    const encoded = protocol.slice(prefix.length);
    try {
      return Buffer.from(encoded, "base64url").toString("utf8");
    } catch {
      return undefined;
    }
  }
  return undefined;
}

function readSession(req: Request): AuthSession | undefined {
  pruneSessions();
  const sessionId = readCookie(req.headers.cookie, sessionCookie);
  if (!sessionId) return undefined;
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  if (session.expiresAt <= Date.now()) {
    sessions.delete(sessionId);
    return undefined;
  }
  return session;
}

function consumeWsTicket(ticket: string): boolean {
  pruneWsTickets();
  const expiresAt = wsTickets.get(ticket);
  if (!expiresAt) return false;
  wsTickets.delete(ticket);
  return expiresAt > Date.now();
}

function requiresCsrf(req: Request): boolean {
  return !["GET", "HEAD", "OPTIONS"].includes(req.method.toUpperCase());
}

function pruneSessions() {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (session.expiresAt <= now) sessions.delete(id);
  }
}

function pruneWsTickets() {
  const now = Date.now();
  for (const [ticket, expiresAt] of wsTickets) {
    if (expiresAt <= now) wsTickets.delete(ticket);
  }
}

function formatSessionCookie(value: string, maxAge: number): string {
  const attrs = [`${sessionCookie}=${value}`, "HttpOnly", "SameSite=Strict", "Path=/", `Max-Age=${maxAge}`];
  if (process.env.COOKIE_SECURE === "1" || process.env.COOKIE_SECURE === "true") attrs.push("Secure");
  return attrs.join("; ");
}
