import { randomBytes, timingSafeEqual } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { NextFunction, Request, Response } from "express";
import type { AuthRole } from "./trading/types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "../data");
const tokenPath = path.join(dataDir, ".authtoken");

let cachedToken: string | null = null;
let autoGenerated = false;

const sessionCookie = "sbv2_session";
const sessionTtlMs = Number(process.env.AUTH_SESSION_TTL_MS ?? 12 * 60 * 60 * 1000);
const wsTicketTtlMs = Number(process.env.AUTH_WS_TICKET_TTL_MS ?? 30_000);

interface AuthSession {
  csrfToken: string;
  role: AuthRole;
  expiresAt: number;
}

const sessions = new Map<string, AuthSession>();
const wsTickets = new Map<string, number>();

/**
 * The access token that guards the trading API. Precedence:
 *   1. process.env.AUTH_TOKEN (operator-supplied, never persisted)
 *   2. backend/data/.authtoken (auto-generated on first run, git-ignored)
 * The token is required for every /api/trade route and the /trade-stream socket.
 */
export function getAuthToken(): string {
  if (cachedToken) return cachedToken;
  const fromEnv = process.env.AUTH_TOKEN?.trim();
  if (fromEnv) {
    cachedToken = fromEnv;
    autoGenerated = false;
    return cachedToken;
  }
  if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });
  if (existsSync(tokenPath)) {
    const saved = readFileSync(tokenPath, "utf8").trim();
    if (saved) {
      cachedToken = saved;
      autoGenerated = true;
      return cachedToken;
    }
  }
  const generated = randomBytes(24).toString("base64url");
  writeFileSync(tokenPath, generated, { mode: 0o600 });
  cachedToken = generated;
  autoGenerated = true;
  return cachedToken;
}

export function isAutoGeneratedToken(): boolean {
  getAuthToken();
  return autoGenerated;
}

/** DEMO_MODE disables key storage + live trading and opens the read-only surface. */
export function isDemoMode(): boolean {
  return process.env.DEMO_MODE === "1" || process.env.DEMO_MODE === "true";
}

/** Constant-time token comparison — avoids leaking length/prefix via timing. */
export function verifyToken(candidate: string | undefined | null): boolean {
  return roleForToken(candidate) !== undefined;
}

export function roleForToken(candidate: string | undefined | null): AuthRole | undefined {
  if (!candidate) return undefined;
  const candidates: Array<[AuthRole, string | undefined]> = [
    ["admin", getAuthToken()],
    ["live-trade", process.env.AUTH_LIVE_TRADE_TOKEN?.trim()],
    ["paper-trade", process.env.AUTH_PAPER_TRADE_TOKEN?.trim()],
    ["read-only", process.env.AUTH_READONLY_TOKEN?.trim()]
  ];
  for (const [role, token] of candidates) {
    if (constantTimeEqual(candidate, token)) return role;
  }
  return undefined;
}

export function roleAllows(actual: AuthRole | undefined, required: AuthRole): boolean {
  if (!actual) return false;
  return roleRank(actual) >= roleRank(required);
}

export function roleRank(role: AuthRole): number {
  switch (role) {
    case "admin":
      return 3;
    case "live-trade":
      return 2;
    case "paper-trade":
      return 1;
    case "read-only":
      return 0;
  }
}

/** Extract a bearer token from an Authorization header. */
export function extractToken(req: { headers: Record<string, unknown>; query?: Record<string, unknown> }): string | undefined {
  const header = req.headers["authorization"];
  if (typeof header === "string" && header.toLowerCase().startsWith("bearer ")) {
    return header.slice(7).trim();
  }
  return undefined;
}

export function createAuthSession(res: Response, role: AuthRole): { csrfToken: string; role: AuthRole; expiresAt: number } {
  pruneSessions();
  const sessionId = randomBytes(32).toString("base64url");
  const session: AuthSession = {
    csrfToken: randomBytes(32).toString("base64url"),
    role,
    expiresAt: Date.now() + sessionTtlMs
  };
  sessions.set(sessionId, session);
  res.setHeader("Set-Cookie", formatSessionCookie(sessionId, Math.floor(sessionTtlMs / 1000)));
  return { csrfToken: session.csrfToken, role: session.role, expiresAt: session.expiresAt };
}

export function clearAuthSession(req: Request, res: Response): void {
  const sessionId = readCookie(req.headers.cookie, sessionCookie);
  if (sessionId) sessions.delete(sessionId);
  res.setHeader("Set-Cookie", formatSessionCookie("", 0));
}

export function requestCsrfToken(req: Request): string | undefined {
  return readSession(req)?.csrfToken;
}

export function issueWsTicket(): { ticket: string; expiresAt: number } {
  pruneWsTickets();
  const ticket = randomBytes(32).toString("base64url");
  const expiresAt = Date.now() + wsTicketTtlMs;
  wsTickets.set(ticket, expiresAt);
  return { ticket, expiresAt };
}

/** Express middleware: 401 unless a valid token is presented. */
export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const bearerRole = roleForToken(extractToken(req));
  if (bearerRole) {
    res.locals.authMode = "bearer";
    res.locals.authRole = bearerRole;
    next();
    return;
  }
  const session = readSession(req);
  if (session) {
    if (requiresCsrf(req) && req.headers["x-csrf-token"] !== session.csrfToken) {
      res.status(403).json({ error: "Forbidden — missing or invalid CSRF token." });
      return;
    }
    res.locals.authMode = "session";
    res.locals.csrfToken = session.csrfToken;
    res.locals.authRole = session.role;
    next();
    return;
  }
  res.status(401).json({ error: "Unauthorized — a valid access token is required." });
}

/** Validate a one-time websocket ticket, with bearer subprotocol as a legacy API fallback. */
export function verifyWsToken(url: URL, protocolHeader?: unknown): boolean {
  void url;
  const ticket = extractWsProtocolValue(protocolHeader, "sbv2.ticket.");
  if (ticket && consumeWsTicket(ticket)) return true;
  const protocolToken = extractWsProtocolValue(protocolHeader, "sbv2.auth.");
  if (protocolToken && roleForToken(protocolToken)) return true;
  return false;
}

function constantTimeEqual(candidate: string, expected: string | undefined): boolean {
  if (!expected) return false;
  const expectedBuffer = Buffer.from(expected);
  const givenBuffer = Buffer.from(candidate);
  if (expectedBuffer.length !== givenBuffer.length) return false;
  return timingSafeEqual(expectedBuffer, givenBuffer);
}

function extractWsProtocolValue(header: unknown, prefix: string): string | undefined {
  if (typeof header !== "string") return undefined;
  for (const item of header.split(",")) {
    const protocol = item.trim();
    if (!protocol.startsWith(prefix)) continue;
    const encoded = protocol.slice(prefix.length);
    try {
      return Buffer.from(encoded, "base64url").toString("utf8");
    } catch {
      return undefined;
    }
  }
  return undefined;
}

function readSession(req: Request): AuthSession | undefined {
  pruneSessions();
  const sessionId = readCookie(req.headers.cookie, sessionCookie);
  if (!sessionId) return undefined;
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  if (session.expiresAt <= Date.now()) {
    sessions.delete(sessionId);
    return undefined;
  }
  return session;
}

function consumeWsTicket(ticket: string): boolean {
  pruneWsTickets();
  const expiresAt = wsTickets.get(ticket);
  if (!expiresAt) return false;
  wsTickets.delete(ticket);
  return expiresAt > Date.now();
}

function requiresCsrf(req: Request): boolean {
  return !["GET", "HEAD", "OPTIONS"].includes(req.method.toUpperCase());
}

function pruneSessions() {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (session.expiresAt <= now) sessions.delete(id);
  }
}

function pruneWsTickets() {
  const now = Date.now();
  for (const [ticket, expiresAt] of wsTickets) {
    if (expiresAt <= now) wsTickets.delete(ticket);
  }
}

function formatSessionCookie(value: string, maxAge: number): string {
  const attrs = [`${sessionCookie}=${value}`, "HttpOnly", "SameSite=Strict", "Path=/", `Max-Age=${maxAge}`];
  if (process.env.COOKIE_SECURE === "1" || process.env.COOKIE_SECURE === "true") attrs.push("Secure");
  return attrs.join("; ");
}

function readCookie(header: string | undefined, name: string): string | undefined {
  if (!header) return undefined;
  for (const part of header.split(";")) {
    const index = part.indexOf("=");
    if (index === -1) continue;
    const key = part.slice(0, index).trim();
    if (key !== name) continue;
    return decodeURIComponent(part.slice(index + 1).trim());
  }
  return undefined;
}
