import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

const CACHE_PREFIX = "saltanat-shell-";

export function pwaPlugin({ entryHtml, publicDir }: { entryHtml: string; publicDir: string }): Plugin {
  return {
    name: "saltanat-safe-offline-shell",
    apply: "build",
    generateBundle(_options, bundle) {
      const outputs = Object.values(bundle).sort((left, right) => left.fileName.localeCompare(right.fileName));
      const publicFiles = walkFiles(publicDir);
      const fingerprint = createHash("sha256");
      fingerprint.update(readFileSync(entryHtml));

      for (const output of outputs) {
        fingerprint.update(output.fileName);
        fingerprint.update(output.type === "chunk" ? output.code : output.source);
      }
      for (const file of publicFiles) {
        fingerprint.update(file.relative);
        fingerprint.update(readFileSync(file.absolute));
      }

      const precache = new Set<string>(["/"]);
      for (const fileName of initialShellOutputs(bundle)) precache.add(`/${fileName}`);
      for (const file of publicFiles) {
        if (file.relative !== "manifest.webmanifest" && !file.relative.startsWith("blockly-media/")) precache.add(`/${file.relative}`);
      }

      const version = fingerprint.digest("hex").slice(0, 16);
      this.emitFile({
        type: "asset",
        fileName: "service-worker.js",
        source: serviceWorkerSource(`${CACHE_PREFIX}${version}`, [...precache].sort())
      });
    }
  };
}

function initialShellOutputs(bundle: Parameters<NonNullable<Plugin["generateBundle"]>>[1]) {
  const files = new Set<string>();
  const visit = (fileName: string) => {
    if (files.has(fileName)) return;
    const output = bundle[fileName];
    if (!output || output.fileName.endsWith(".map")) return;
    files.add(fileName);
    if (output.type === "chunk") for (const imported of output.imports) visit(imported);
  };
  for (const output of Object.values(bundle)) {
    if (output.type === "chunk" && output.isEntry) visit(output.fileName);
    if (output.type === "asset" && output.fileName.endsWith(".css")) files.add(output.fileName);
  }
  return [...files].sort();
}

function walkFiles(root: string) {
  const files: Array<{ absolute: string; relative: string }> = [];
  const visit = (directory: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(absolute);
      else if (entry.isFile()) files.push({ absolute, relative: path.relative(root, absolute).split(path.sep).join("/") });
    }
  };
  visit(root);
  return files.sort((left, right) => left.relative.localeCompare(right.relative));
}

function serviceWorkerSource(cacheName: string, precache: string[]) {
  return `/* Generated by frontend/build/pwaPlugin.ts. Do not edit. */
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache)};
const PRECACHE_PATHS = new Set(PRECACHE);
const NETWORK_ONLY_PREFIXES = ["/api/", "/stream", "/quotes", "/orderbook", "/trade-flow", "/trade-stream"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NETWORK_ONLY_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))) return;
  if (request.mode === "navigate") {
    respondWithNetworkFirstNavigation(event);
    return;
  }
  if (PRECACHE_PATHS.has(url.pathname)) event.respondWith(cacheFirst(request, url.pathname));
});

function respondWithNetworkFirstNavigation(event) {
  const network = fetch(event.request);
  event.respondWith(network.catch(async () => (await (await caches.open(CACHE_NAME)).match("/")) || Response.error()));
}

async function cacheFirst(request, path) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(path);
  if (cached) return cached;
  return fetch(request);
}
`;
}
