import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

const CACHE_PREFIX = "saltanat-shell-";

export function pwaPlugin({ entryHtml, publicDir }: { entryHtml: string; publicDir: string }): Plugin {
  return {
    name: "saltanat-safe-offline-shell",
    apply: "build",
    generateBundle(_options, bundle) {
      const outputs = Object.values(bundle).sort((left, right) => left.fileName.localeCompare(right.fileName));
      const publicFiles = walkFiles(publicDir);
      const fingerprint = createHash("sha256");
      fingerprint.update(readFileSync(entryHtml));

      for (const output of outputs) {
        fingerprint.update(output.fileName);
        fingerprint.update(output.type === "chunk" ? output.code : output.source);
      }
      for (const file of publicFiles) {
        fingerprint.update(file.relative);
        fingerprint.update(readFileSync(file.absolute));
      }

      const precache = new Set<string>(["/"]);
      for (const fileName of initialShellOutputs(bundle)) precache.add(`/${fileName}`);
      for (const file of publicFiles) {
        if (file.relative !== "manifest.webmanifest" && !file.relative.startsWith("blockly-media/")) precache.add(`/${file.relative}`);
      }

      const research = researchOutputs(bundle, publicFiles, precache);
      const version = fingerprint.digest("hex").slice(0, 16);
      this.emitFile({
        type: "asset",
        fileName: "service-worker.js",
        source: serviceWorkerSource(`${CACHE_PREFIX}${version}`, [...precache].sort(), research.files, research.bytes)
      });
    }
  };
}

function researchOutputs(bundle: Parameters<NonNullable<Plugin["generateBundle"]>>[1], publicFiles: Array<{ absolute: string; relative: string }>, shellFiles: ReadonlySet<string>) {
  const files = new Set<string>();
  const roots = Object.values(bundle).filter((output) => output.type === "chunk" && output.facadeModuleId?.endsWith("/components/StrategyLab.tsx"));
  const visit = (fileName: string) => {
    if (files.has(fileName)) return;
    const output = bundle[fileName];
    if (!output || output.fileName.endsWith(".map")) return;
    files.add(fileName);
    if (output.type === "chunk") {
      const dynamicImports = output.isEntry ? [] : output.dynamicImports;
      for (const dependency of [...output.imports, ...dynamicImports, ...(output.referencedFiles ?? [])]) visit(dependency);
    }
  };
  for (const root of roots) visit(root.fileName);
  for (const output of Object.values(bundle)) if (output.fileName.includes("optimizer.worker")) visit(output.fileName);
  for (const file of publicFiles) if (file.relative.startsWith("blockly-media/")) files.add(file.relative);
  const sorted = [...files].filter((fileName) => !shellFiles.has(`/${fileName}`)).sort();
  const bytes = sorted.reduce((total, fileName) => {
    const output = bundle[fileName];
    if (output?.type === "chunk") return total + Buffer.byteLength(output.code);
    if (output?.type === "asset") return total + (typeof output.source === "string" ? Buffer.byteLength(output.source) : output.source.byteLength);
    const publicFile = publicFiles.find((file) => file.relative === fileName);
    return total + (publicFile ? readFileSync(publicFile.absolute).byteLength : 0);
  }, 0);
  return { files: sorted.map((file) => `/${file}`), bytes };
}

function initialShellOutputs(bundle: Parameters<NonNullable<Plugin["generateBundle"]>>[1]) {
  const files = new Set<string>();
  const visit = (fileName: string) => {
    if (files.has(fileName)) return;
    const output = bundle[fileName];
    if (!output || output.fileName.endsWith(".map")) return;
    files.add(fileName);
    if (output.type === "chunk") for (const imported of output.imports) visit(imported);
  };
  for (const output of Object.values(bundle)) {
    if (output.type === "chunk" && output.isEntry) visit(output.fileName);
    if (output.type === "asset" && output.fileName.endsWith(".css")) files.add(output.fileName);
  }
  return [...files].sort();
}

function walkFiles(root: string) {
  const files: Array<{ absolute: string; relative: string }> = [];
  const visit = (directory: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(absolute);
      else if (entry.isFile()) files.push({ absolute, relative: path.relative(root, absolute).split(path.sep).join("/") });
    }
  };
  visit(root);
  return files.sort((left, right) => left.relative.localeCompare(right.relative));
}

function serviceWorkerSource(cacheName: string, precache: string[], researchFiles: string[], researchBytes: number) {
  return `/* Generated by frontend/build/pwaPlugin.ts. Do not edit. */
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const CACHE_NAME = ${JSON.stringify(cacheName)};
const RESEARCH_CACHE_NAME = CACHE_NAME + "-research";
const PRECACHE = ${JSON.stringify(precache)};
const PRECACHE_PATHS = new Set(PRECACHE);
const RESEARCH_FILES = ${JSON.stringify(researchFiles)};
const RESEARCH_PATHS = new Set(RESEARCH_FILES);
const RESEARCH_BYTES = ${researchBytes};
const NETWORK_ONLY_PREFIXES = ["/api/", "/stream", "/quotes", "/orderbook", "/trade-flow", "/trade-stream"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME && name !== RESEARCH_CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NETWORK_ONLY_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))) return;
  if (request.mode === "navigate") {
    respondWithNetworkFirstNavigation(event);
    return;
  }
  if (RESEARCH_PATHS.has(url.pathname)) {
    event.respondWith(researchCacheFirst(request, url.pathname));
    return;
  }
  if (PRECACHE_PATHS.has(url.pathname)) event.respondWith(cacheFirst(request, url.pathname));
});

self.addEventListener("message", (event) => {
  const port = event.ports[0];
  if (!port || typeof event.data?.type !== "string") return;
  event.waitUntil(handleResearchMessage(event.data.type).then((result) => port.postMessage(result)).catch(() => port.postMessage({ ok: false, installed: false, files: RESEARCH_FILES.length, bytes: RESEARCH_BYTES })));
});

function respondWithNetworkFirstNavigation(event) {
  const network = fetch(event.request);
  event.respondWith(network.catch(async () => (await (await caches.open(CACHE_NAME)).match("/")) || Response.error()));
}

async function cacheFirst(request, path) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(path);
  if (cached) return cached;
  return fetch(request);
}

async function researchCacheFirst(request, path) {
  if (!(await caches.has(RESEARCH_CACHE_NAME))) return fetch(request);
  const cache = await caches.open(RESEARCH_CACHE_NAME);
  return (await cache.match(path)) || fetch(request);
}

async function handleResearchMessage(type) {
  if (type === "saltanat:offline-research:install") {
    await caches.delete(RESEARCH_CACHE_NAME);
    const cache = await caches.open(RESEARCH_CACHE_NAME);
    try { await cache.addAll(RESEARCH_FILES); }
    catch (error) { await caches.delete(RESEARCH_CACHE_NAME); throw error; }
  } else if (type === "saltanat:offline-research:remove") {
    await caches.delete(RESEARCH_CACHE_NAME);
    return { ok: true, installed: false, files: RESEARCH_FILES.length, bytes: RESEARCH_BYTES };
  } else if (type !== "saltanat:offline-research:status") {
    return { ok: false, installed: false, files: RESEARCH_FILES.length, bytes: RESEARCH_BYTES };
  }
  if (!(await caches.has(RESEARCH_CACHE_NAME))) return { ok: true, installed: false, files: RESEARCH_FILES.length, bytes: RESEARCH_BYTES };
  const cache = await caches.open(RESEARCH_CACHE_NAME);
  const keys = await cache.keys();
  const installed = RESEARCH_FILES.length > 0 && RESEARCH_FILES.every((path) => keys.some((request) => new URL(request.url).pathname === path));
  return { ok: true, installed, files: RESEARCH_FILES.length, bytes: RESEARCH_BYTES };
}
`;
}
