import type { Locale } from "../i18n";

/** Localized copy for the versioned strategy gallery (R9.3): feed, own management, publish and import flows. */

const en = {
  open: "Community",
  openHelp: "Browse, publish and import versioned strategy artifacts with provenance and ratings",
  title: "Strategy gallery",
  close: "Close strategy gallery",
  intro: "Published artifacts are sanitized on the server (no owner, workspace or run identifiers), frozen at the SQL level and hash-verified by both the server and this browser at import.",
  signIn: "Sign in to browse and publish gallery artifacts.",
  tabFeed: "Public feed",
  tabOwn: "My publications",
  refresh: "Refresh",
  loading: "Loading gallery…",
  loadFailed: "Gallery request failed",
  feedEmpty: "No public artifacts have been published yet.",
  ownEmpty: "You have not published anything yet.",
  publish: "Publish…",
  importAction: "Import",
  importing: "Importing…",
  importFailed: "Import failed",
  hashMismatch: "The artifact content does not match its published hash; the import was refused.",
  entryRevoked: "This publication was revoked and can no longer be imported.",
  activeBadge: "Active",
  revokedBadge: "Revoked",
  revokedReason: "Revocation reason",
  visibility: "Visibility",
  visibilityPrivate: "Private",
  visibilityUnlisted: "Unlisted",
  visibilityPublic: "Public",
  visibilityUpdated: "Visibility updated.",
  revoke: "Revoke",
  revokeTitle: "Revoke publication",
  revokeWarning: "Revocation refuses new imports of every version but never rewrites published content; importers keep their existing copies.",
  revokeReasonLabel: "Reason (shown to viewers)",
  revokeConfirm: "Revoke publication",
  revoked: "Publication revoked.",
  publishedAt: "Published",
  version: "Version",
  metricsGaOos: "Server-evaluated out-of-sample evidence",
  metricsSelfReported: "Self-reported metrics — not verified by the server",
  engine: "Engine",
  generator: "Generator",
  dataset: "Dataset",
  seed: "Seed",
  complexity: "Complexity",
  markets: "Markets",
  limitations: "Limitations",
  inSample: "In-sample",
  outOfSample: "Out-of-sample",
  oosGap: "OOS gap",
  overfit: "overfit",
  unstable: "unstable",
  rating: "Rating",
  ratingBreakdown: "Rating breakdown",
  ratingOosStability: "OOS stability",
  ratingDrawdown: "Drawdown",
  ratingReproducibility: "Reproducibility",
  ratingComplexity: "Complexity",
  ratingFreshness: "Evidence freshness",
  evidenceAge: "Evidence age",
  days: "days",
  ratingNote: "Composite quality score — never a net-profit-only ranking.",
  noRating: "No rating recorded.",
  importReviewTitle: "Review gallery import",
  importReviewHelp: "The sha256 of this bundle was re-verified by the server and again in this browser. Review the evidence before creating a local copy.",
  importVerifiedHash: "Content hash verified on the server and in this browser.",
  importCopyNote: "Import creates an independent editable copy in your library only. It never starts a robot.",
  importGateNote: "Paper start stays locked for the copy until a local validation and backtest complete.",
  importConfirm: "Import as local copy",
  imported: "Copy added to the library — run a local validation and backtest to unlock paper start.",
  publishTitle: "Publish to gallery",
  publishHelp: "The server re-sanitizes and freezes the published content; only the whitelisted document below ever leaves this browser.",
  sourceLabel: "Publication source",
  sourceLibrary: "Library artifact",
  sourceGa: "Promoted GA candidate",
  selectArtifact: "Strategy artifact",
  selectRun: "Evolution run",
  selectCandidate: "Promoted candidate",
  loadRuns: "Load runs",
  noRuns: "No evolution runs found.",
  noPromotedCandidates: "This run has no promoted candidates. Promote a clean candidate first.",
  candidateLoadFailed: "Could not load the candidate detail",
  compileFailed: "The artifact does not compile",
  previewTitle: "Sanitization preview",
  previewHelp: "Exactly this canonical document is hashed and published — verbatim, nothing more.",
  previewBytes: "bytes",
  previewTooLarge: "The sanitized bundle exceeds the 256 KiB gallery bound.",
  previewUnavailable: "Publication preview unavailable",
  consent: "I reviewed the exact sanitized content above and consent to publishing it.",
  titleLabel: "Title",
  summaryLabel: "Summary",
  publishAction: "Publish",
  publishing: "Publishing…",
  published: "Published",
  publishFailed: "Publish failed",
  revalidationBadge: "Revalidation required",
  paperStartLocked: "This strategy was imported from the gallery. Run a local validation and backtest of this copy before starting a robot.",
  revalidationDone: "Local validation and backtest completed — paper start unlocked."
} as const;

export type GalleryMessageKey = keyof typeof en;

const ru: Record<GalleryMessageKey, string> = {
  open: "Сообщество",
  openHelp: "Просматривать, публиковать и импортировать версионированные артефакты стратегий с происхождением и рейтингом",
  title: "Галерея стратегий",
  close: "Закрыть галерею стратегий",
  intro: "Публикуемые артефакты санитизируются на сервере (без идентификаторов владельца, workspace и запусков), замораживаются на уровне SQL и проверяются по hash сервером и этим браузером при импорте.",
  signIn: "Войдите, чтобы просматривать и публиковать артефакты галереи.",
  tabFeed: "Публичная лента",
  tabOwn: "Мои публикации",
  refresh: "Обновить",
  loading: "Загрузка галереи…",
  loadFailed: "Запрос к галерее не удался",
  feedEmpty: "Публичных артефактов пока нет.",
  ownEmpty: "Вы пока ничего не публиковали.",
  publish: "Опубликовать…",
  importAction: "Импортировать",
  importing: "Импорт…",
  importFailed: "Импорт не удался",
  hashMismatch: "Содержимое артефакта не совпадает с опубликованным hash; импорт отклонён.",
  entryRevoked: "Публикация отозвана и больше не может быть импортирована.",
  activeBadge: "Активна",
  revokedBadge: "Отозвана",
  revokedReason: "Причина отзыва",
  visibility: "Видимость",
  visibilityPrivate: "Приватная",
  visibilityUnlisted: "По ссылке",
  visibilityPublic: "Публичная",
  visibilityUpdated: "Видимость обновлена.",
  revoke: "Отозвать",
  revokeTitle: "Отзыв публикации",
  revokeWarning: "Отзыв запрещает новые импорты всех версий, но никогда не переписывает опубликованное содержимое; существующие копии остаются у импортеров.",
  revokeReasonLabel: "Причина (видна пользователям)",
  revokeConfirm: "Отозвать публикацию",
  revoked: "Публикация отозвана.",
  publishedAt: "Опубликовано",
  version: "Версия",
  metricsGaOos: "Серверные out-of-sample свидетельства",
  metricsSelfReported: "Метрики заявлены автором и не проверены сервером",
  engine: "Движок",
  generator: "Генератор",
  dataset: "Датасет",
  seed: "Seed",
  complexity: "Сложность",
  markets: "Рынки",
  limitations: "Ограничения",
  inSample: "In-sample",
  outOfSample: "Out-of-sample",
  oosGap: "OOS-разрыв",
  overfit: "переобучение",
  unstable: "нестабильно",
  rating: "Рейтинг",
  ratingBreakdown: "Состав рейтинга",
  ratingOosStability: "Стабильность OOS",
  ratingDrawdown: "Просадка",
  ratingReproducibility: "Воспроизводимость",
  ratingComplexity: "Сложность",
  ratingFreshness: "Свежесть свидетельств",
  evidenceAge: "Возраст свидетельств",
  days: "дн.",
  ratingNote: "Композитная оценка качества — никогда не рейтинг только по прибыли.",
  noRating: "Рейтинг не записан.",
  importReviewTitle: "Проверка импорта из галереи",
  importReviewHelp: "SHA-256 этого бандла перепроверен сервером и повторно этим браузером. Проверьте свидетельства перед созданием локальной копии.",
  importVerifiedHash: "Hash содержимого проверен на сервере и в этом браузере.",
  importCopyNote: "Импорт создаёт только независимую редактируемую копию в вашей библиотеке. Он никогда не запускает робота.",
  importGateNote: "Paper-запуск для копии остаётся заблокированным до завершения локальной проверки и бэктеста.",
  importConfirm: "Импортировать как локальную копию",
  imported: "Копия добавлена в библиотеку — выполните локальную проверку и бэктест, чтобы разблокировать paper-запуск.",
  publishTitle: "Публикация в галерею",
  publishHelp: "Сервер повторно санитизирует и замораживает публикуемое содержимое; браузер отправляет только показанный ниже документ из белого списка.",
  sourceLabel: "Источник публикации",
  sourceLibrary: "Артефакт библиотеки",
  sourceGa: "Продвинутый GA-кандидат",
  selectArtifact: "Артефакт стратегии",
  selectRun: "Запуск эволюции",
  selectCandidate: "Продвинутый кандидат",
  loadRuns: "Загрузить запуски",
  noRuns: "Запуски эволюции не найдены.",
  noPromotedCandidates: "В этом запуске нет продвинутых кандидатов. Сначала продвиньте чистого кандидата.",
  candidateLoadFailed: "Не удалось загрузить детали кандидата",
  compileFailed: "Артефакт не компилируется",
  previewTitle: "Предпросмотр санитизации",
  previewHelp: "Публикуется и хэшируется ровно этот канонический документ — дословно и ничего больше.",
  previewBytes: "байт",
  previewTooLarge: "Санитизированный бандл превышает лимит галереи 256 КиБ.",
  previewUnavailable: "Предпросмотр публикации недоступен",
  consent: "Я просмотрел(а) точное санитизированное содержимое выше и согласен(на) его опубликовать.",
  titleLabel: "Название",
  summaryLabel: "Описание",
  publishAction: "Опубликовать",
  publishing: "Публикация…",
  published: "Опубликовано",
  publishFailed: "Публикация не удалась",
  revalidationBadge: "Требуется перепроверка",
  paperStartLocked: "Эта стратегия импортирована из галереи. Выполните локальную проверку и бэктест этой копии перед запуском робота.",
  revalidationDone: "Локальная проверка и бэктест завершены — paper-запуск разблокирован."
};

const kk: Record<GalleryMessageKey, string> = {
  open: "Қауымдастық",
  openHelp: "Шығу тегі және рейтингі бар версияланған стратегия артефактілерін қарау, жариялау және импорттау",
  title: "Стратегиялар галереясы",
  close: "Стратегиялар галереясын жабу",
  intro: "Жарияланатын артефактілер серверде тазартылады (иесінің, workspace және запусктардың идентификаторларынсыз), SQL деңгейінде қатырылады және импорт кезінде hash арқылы серверде де, осы браузерде де тексеріледі.",
  signIn: "Галерея артефактілерін қарау және жариялау үшін жүйеге кіріңіз.",
  tabFeed: "Жалпы лента",
  tabOwn: "Менің жарияланымдарым",
  refresh: "Жаңарту",
  loading: "Галерея жүктелуде…",
  loadFailed: "Галерея сұрауы сәтсіз аяқталды",
  feedEmpty: "Жалпыға ашық артефактілер әлі жарияланбаған.",
  ownEmpty: "Сіз әлі ештеңе жарияламадыңыз.",
  publish: "Жариялау…",
  importAction: "Импорттау",
  importing: "Импортталуда…",
  importFailed: "Импорт сәтсіз аяқталды",
  hashMismatch: "Артефакт мазмұны жарияланған hash-пен сәйкес келмейді; импорт қабылданбады.",
  entryRevoked: "Жарияланым кері қайтарылған және енді импортталмайды.",
  activeBadge: "Белсенді",
  revokedBadge: "Кері қайтарылған",
  revokedReason: "Кері қайтару себебі",
  visibility: "Көріну",
  visibilityPrivate: "Жеке",
  visibilityUnlisted: "Сілтеме бойынша",
  visibilityPublic: "Жалпыға ашық",
  visibilityUpdated: "Көріну жаңартылды.",
  revoke: "Кері қайтару",
  revokeTitle: "Жарияланымды кері қайтару",
  revokeWarning: "Кері қайтару барлық версиялардың жаңа импорттарына тыйым салады, бірақ жарияланған мазмұнды ешқашан қайта жазбайды; бұрынғы көшірмелер импорттаушыларда қалады.",
  revokeReasonLabel: "Себебі (қараушыларға көрсетіледі)",
  revokeConfirm: "Жарияланымды кері қайтару",
  revoked: "Жарияланым кері қайтарылды.",
  publishedAt: "Жарияланды",
  version: "Версия",
  metricsGaOos: "Сервердегі out-of-sample дәлелдер",
  metricsSelfReported: "Метрикаларды автор өзі мәлімдеген және сервер тексермеген",
  engine: "Қозғалтқыш",
  generator: "Генератор",
  dataset: "Датасет",
  seed: "Seed",
  complexity: "Күрделілік",
  markets: "Нарықтар",
  limitations: "Шектеулер",
  inSample: "In-sample",
  outOfSample: "Out-of-sample",
  oosGap: "OOS алшақтығы",
  overfit: "қайта оқыту",
  unstable: "тұрақсыз",
  rating: "Рейтинг",
  ratingBreakdown: "Рейтинг құрамы",
  ratingOosStability: "OOS тұрақтылығы",
  ratingDrawdown: "Кему",
  ratingReproducibility: "Қайта өндірілу",
  ratingComplexity: "Күрделілік",
  ratingFreshness: "Дәлелдер жаңалығы",
  evidenceAge: "Дәлелдер жасы",
  days: "күн",
  ratingNote: "Құрама сапа бағасы — ешқашан тек пайда бойынша рейтинг емес.",
  noRating: "Рейтинг жазылмаған.",
  importReviewTitle: "Галерея импортын тексеру",
  importReviewHelp: "Бұл бандлдың SHA-256 мәні сервермен және қайтадан осы браузермен тексерілді. Жергілікті көшірме жасамас бұрын дәлелдерді қараңыз.",
  importVerifiedHash: "Мазмұн hash-і серверде және осы браузерде тексерілді.",
  importCopyNote: "Импорт тек кітапханаңызда тәуелсіз өңделетін көшірме жасайды. Ол ешқашан робот іске қоспайды.",
  importGateNote: "Жергілікті тексеру мен бэктест аяқталғанша көшірме үшін paper-іске қосу бұғатталған күйде қалады.",
  importConfirm: "Жергілікті көшірме ретінде импорттау",
  imported: "Көшірме кітапханаға қосылды — paper-іске қосуды ашу үшін жергілікті тексеру мен бэктест жүргізіңіз.",
  publishTitle: "Галереяға жариялау",
  publishHelp: "Сервер жарияланатын мазмұнды қайта тазартып, қатырады; браузерден тек төменде көрсетілген ақ тізімдегі құжат қана жіберіледі.",
  sourceLabel: "Жарияланым көзі",
  sourceLibrary: "Кітапхана артефактісі",
  sourceGa: "Жоғарылатылған GA-кандидат",
  selectArtifact: "Стратегия артефактісі",
  selectRun: "Эволюция запускі",
  selectCandidate: "Жоғарылатылған кандидат",
  loadRuns: "Запусктарды жүктеу",
  noRuns: "Эволюция запусктары табылмады.",
  noPromotedCandidates: "Бұл запускте жоғарылатылған кандидаттар жоқ. Алдымен таза кандидатты жоғарылатыңыз.",
  candidateLoadFailed: "Кандидат мәліметін жүктеу мүмкін болмады",
  compileFailed: "Артефакт компиляцияланбайды",
  previewTitle: "Тазарту алдын ала көрінісі",
  previewHelp: "Дәл осы канондық құжат хэштеліп жарияланады — сөзбе-сөз, артық ештеңе жоқ.",
  previewBytes: "байт",
  previewTooLarge: "Тазартылған бандл галереяның 256 КиБ шегінен асады.",
  previewUnavailable: "Жарияланымның алдын ала көрінісі қолжетімсіз",
  consent: "Жоғарыдағы нақты тазартылған мазмұнды қарап шықтым және оны жариялауға келісемін.",
  titleLabel: "Атауы",
  summaryLabel: "Сипаттама",
  publishAction: "Жариялау",
  publishing: "Жариялануда…",
  published: "Жарияланды",
  publishFailed: "Жариялау сәтсіз аяқталды",
  revalidationBadge: "Қайта тексеру қажет",
  paperStartLocked: "Бұл стратегия галереядан импортталған. Робот іске қоспас бұрын осы көшірмеге жергілікті тексеру мен бэктест жүргізіңіз.",
  revalidationDone: "Жергілікті тексеру мен бэктест аяқталды — paper-іске қосу ашылды."
};

const messages: Record<Locale, Record<GalleryMessageKey, string>> = { en, ru, kk };

export function galleryText(locale: Locale, key: GalleryMessageKey): string {
  return messages[locale][key] ?? en[key];
}
