import type { Locale } from "../i18n";

const messages = {
  en: {
    title: "Trading account registry",
    description: "Non-secret account metadata used to group strategies and robots.",
    boundary: "Credentials are still shared once per exchange. New rows are metadata-only and cannot execute live orders independently. Margin and borrowing data are not provided by this registry.",
    secureOrigin: "Creating or changing accounts requires HTTPS or localhost.",
    loading: "Loading accounts…",
    loadFailed: "Account registry is unavailable",
    empty: "No trading accounts are registered.",
    createTitle: "Add account metadata",
    label: "Account label",
    exchange: "Exchange",
    ownership: "Ownership",
    own: "Own",
    managed: "Managed",
    enabled: "Enabled",
    create: "Add account",
    creating: "Adding…",
    edit: "Edit",
    save: "Save changes",
    cancel: "Cancel",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    status: "Status",
    ready: "Ready with shared credentials",
    credentialsMissing: "Shared credentials missing",
    metadataOnly: "Metadata only",
    disabled: "Disabled",
    accountId: "Account ID",
    robots: "Bound robots",
    none: "None",
    sharedCredentials: "Shared exchange credentials",
    unsupportedCredentials: "Independent credentials unsupported",
    configuredCredentials: "Configured",
    missingCredentials: "Missing",
    inUse: "Disable and delete are blocked while robots are bound to this account.",
    created: "Account metadata added.",
    updated: "Account metadata updated.",
    enabledDone: "Account enabled.",
    disabledDone: "Account disabled.",
    deleted: "Account metadata deleted.",
    operationFailed: "Account operation failed",
    disableConfirm: "Disable this account? New robot starts using it will be blocked.",
    deleteConfirm: "Delete this account metadata? This cannot be undone."
  },
  ru: {
    title: "Реестр торговых аккаунтов",
    description: "Несекретные метаданные аккаунтов для группировки стратегий и роботов.",
    boundary: "Ключи по-прежнему общие для каждой биржи. Новые записи работают только как метаданные и не могут независимо исполнять live-ордера. Этот реестр не возвращает данные о марже и заимствованиях.",
    secureOrigin: "Создание и изменение аккаунтов доступно только через HTTPS или localhost.",
    loading: "Загрузка аккаунтов…",
    loadFailed: "Реестр аккаунтов недоступен",
    empty: "Торговые аккаунты ещё не зарегистрированы.",
    createTitle: "Добавить метаданные аккаунта",
    label: "Название аккаунта",
    exchange: "Биржа",
    ownership: "Принадлежность",
    own: "Свой",
    managed: "Под управлением",
    enabled: "Включён",
    create: "Добавить аккаунт",
    creating: "Добавление…",
    edit: "Изменить",
    save: "Сохранить изменения",
    cancel: "Отмена",
    enable: "Включить",
    disable: "Отключить",
    delete: "Удалить",
    status: "Статус",
    ready: "Готов с общими ключами",
    credentialsMissing: "Общие ключи не настроены",
    metadataOnly: "Только метаданные",
    disabled: "Отключён",
    accountId: "ID аккаунта",
    robots: "Привязанные роботы",
    none: "Нет",
    sharedCredentials: "Общие ключи биржи",
    unsupportedCredentials: "Отдельные ключи не поддерживаются",
    configuredCredentials: "Настроены",
    missingCredentials: "Не настроены",
    inUse: "Отключение и удаление заблокированы, пока к аккаунту привязаны роботы.",
    created: "Метаданные аккаунта добавлены.",
    updated: "Метаданные аккаунта обновлены.",
    enabledDone: "Аккаунт включён.",
    disabledDone: "Аккаунт отключён.",
    deleted: "Метаданные аккаунта удалены.",
    operationFailed: "Не удалось выполнить операцию с аккаунтом",
    disableConfirm: "Отключить этот аккаунт? Запуск новых роботов на нём будет заблокирован.",
    deleteConfirm: "Удалить метаданные этого аккаунта? Действие нельзя отменить."
  },
  kk: {
    title: "Сауда аккаунттарының тізілімі",
    description: "Стратегиялар мен роботтарды топтауға арналған құпия емес аккаунт метадеректері.",
    boundary: "Кілттер әр биржа үшін әлі де ортақ. Жаңа жазбалар тек метадерек ретінде жұмыс істейді және live ордерлерді дербес орындай алмайды. Бұл тізілім маржа мен қарыз алу деректерін бермейді.",
    secureOrigin: "Аккаунттарды жасау және өзгерту үшін HTTPS немесе localhost қажет.",
    loading: "Аккаунттар жүктелуде…",
    loadFailed: "Аккаунттар тізілімі қолжетімсіз",
    empty: "Сауда аккаунттары әлі тіркелмеген.",
    createTitle: "Аккаунт метадеректерін қосу",
    label: "Аккаунт атауы",
    exchange: "Биржа",
    ownership: "Тиесілігі",
    own: "Өзімдікі",
    managed: "Басқарудағы",
    enabled: "Қосылған",
    create: "Аккаунт қосу",
    creating: "Қосылуда…",
    edit: "Өзгерту",
    save: "Өзгерістерді сақтау",
    cancel: "Бас тарту",
    enable: "Қосу",
    disable: "Өшіру",
    delete: "Жою",
    status: "Күйі",
    ready: "Ортақ кілттермен дайын",
    credentialsMissing: "Ортақ кілттер бапталмаған",
    metadataOnly: "Тек метадеректер",
    disabled: "Өшірілген",
    accountId: "Аккаунт ID",
    robots: "Байланған роботтар",
    none: "Жоқ",
    sharedCredentials: "Биржаның ортақ кілттері",
    unsupportedCredentials: "Бөлек кілттерге қолдау жоқ",
    configuredCredentials: "Бапталған",
    missingCredentials: "Бапталмаған",
    inUse: "Аккаунтқа роботтар байланған кезде оны өшіру және жою бұғатталады.",
    created: "Аккаунт метадеректері қосылды.",
    updated: "Аккаунт метадеректері жаңартылды.",
    enabledDone: "Аккаунт қосылды.",
    disabledDone: "Аккаунт өшірілді.",
    deleted: "Аккаунт метадеректері жойылды.",
    operationFailed: "Аккаунт әрекеті орындалмады",
    disableConfirm: "Бұл аккаунтты өшіру керек пе? Онда жаңа роботтарды іске қосу бұғатталады.",
    deleteConfirm: "Бұл аккаунт метадеректерін жою керек пе? Әрекетті қайтару мүмкін емес."
  }
} as const;

export type AccountRegistryTextKey = keyof typeof messages.en;

export function accountRegistryText(locale: Locale, key: AccountRegistryTextKey): string {
  return messages[locale][key];
}
