import type { Locale } from "../i18n";

const messages = {
  en: {
    title: "Trading account registry",
    description: "Your exchange accounts, their credentials status and bound robots.",
    boundary: "Every account uses its own encrypted credentials. The server returns only configured or missing status; API keys and secrets are never returned to the browser.",
    secureOrigin: "Creating or changing accounts requires HTTPS or localhost.",
    loading: "Loading accounts…",
    loadFailed: "Account registry is unavailable",
    empty: "No trading accounts are registered.",
    createTitle: "Add trading account",
    label: "Account label",
    exchange: "Exchange",
    ownership: "Ownership",
    own: "Own",
    managed: "Managed",
    enabled: "Enabled",
    create: "Add account",
    creating: "Adding…",
    edit: "Edit",
    save: "Save changes",
    cancel: "Cancel",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    status: "Status",
    ready: "Ready for live execution",
    credentialsMissing: "Credentials not configured",
    disabled: "Disabled",
    accountId: "Account ID",
    robots: "Bound robots",
    none: "None",
    accountCredentials: "Account credentials",
    configuredCredentials: "Configured",
    missingCredentials: "Missing",
    apiKey: "API key",
    apiSecret: "API secret",
    setCredentials: "Set credentials",
    rotateCredentials: "Rotate credentials",
    savingCredentials: "Saving…",
    deleteCredentials: "Remove credentials",
    credentialsHint: "Both values are sent over the protected session and stored encrypted for this account. They are never read back into the browser.",
    credentialsSaved: "Account credentials saved.",
    credentialsRotated: "Account credentials rotated.",
    credentialsDeleted: "Account credentials removed.",
    credentialsDeleteConfirm: "Remove this account's exchange credentials? Live execution will be unavailable until new credentials are set.",
    inUse: "Disable and delete are blocked while robots are bound to this account.",
    created: "Trading account added.",
    updated: "Trading account updated.",
    enabledDone: "Account enabled.",
    disabledDone: "Account disabled.",
    deleted: "Trading account deleted.",
    operationFailed: "Account operation failed",
    disableConfirm: "Disable this account? New robot starts using it will be blocked.",
    deleteConfirm: "Delete this trading account? This cannot be undone."
  },
  ru: {
    title: "Реестр торговых аккаунтов",
    description: "Ваши биржевые аккаунты, состояние их ключей и привязанные роботы.",
    boundary: "У каждого аккаунта собственные зашифрованные ключи. Сервер возвращает только состояние «настроены» или «не настроены»; API key и secret никогда не возвращаются в браузер.",
    secureOrigin: "Создание и изменение аккаунтов доступно только через HTTPS или localhost.",
    loading: "Загрузка аккаунтов…",
    loadFailed: "Реестр аккаунтов недоступен",
    empty: "Торговые аккаунты ещё не зарегистрированы.",
    createTitle: "Добавить торговый аккаунт",
    label: "Название аккаунта",
    exchange: "Биржа",
    ownership: "Принадлежность",
    own: "Свой",
    managed: "Под управлением",
    enabled: "Включён",
    create: "Добавить аккаунт",
    creating: "Добавление…",
    edit: "Изменить",
    save: "Сохранить изменения",
    cancel: "Отмена",
    enable: "Включить",
    disable: "Отключить",
    delete: "Удалить",
    status: "Статус",
    ready: "Готов к live-исполнению",
    credentialsMissing: "Ключи не настроены",
    disabled: "Отключён",
    accountId: "ID аккаунта",
    robots: "Привязанные роботы",
    none: "Нет",
    accountCredentials: "Ключи аккаунта",
    configuredCredentials: "Настроены",
    missingCredentials: "Не настроены",
    apiKey: "API key",
    apiSecret: "API secret",
    setCredentials: "Установить ключи",
    rotateCredentials: "Заменить ключи",
    savingCredentials: "Сохранение…",
    deleteCredentials: "Удалить ключи",
    credentialsHint: "Оба значения передаются через защищённую сессию и хранятся зашифрованными для этого аккаунта. Браузер никогда не получает их обратно.",
    credentialsSaved: "Ключи аккаунта сохранены.",
    credentialsRotated: "Ключи аккаунта заменены.",
    credentialsDeleted: "Ключи аккаунта удалены.",
    credentialsDeleteConfirm: "Удалить биржевые ключи этого аккаунта? Live-исполнение будет недоступно, пока не установлены новые ключи.",
    inUse: "Отключение и удаление заблокированы, пока к аккаунту привязаны роботы.",
    created: "Торговый аккаунт добавлен.",
    updated: "Торговый аккаунт обновлён.",
    enabledDone: "Аккаунт включён.",
    disabledDone: "Аккаунт отключён.",
    deleted: "Торговый аккаунт удалён.",
    operationFailed: "Не удалось выполнить операцию с аккаунтом",
    disableConfirm: "Отключить этот аккаунт? Запуск новых роботов на нём будет заблокирован.",
    deleteConfirm: "Удалить этот торговый аккаунт? Действие нельзя отменить."
  },
  kk: {
    title: "Сауда аккаунттарының тізілімі",
    description: "Биржа аккаунттарыңыз, олардың кілт күйі және байланған роботтар.",
    boundary: "Әр аккаунттың жеке шифрланған кілттері бар. Сервер тек бапталған немесе жоқ күйін қайтарады; API key және secret браузерге ешқашан қайтарылмайды.",
    secureOrigin: "Аккаунттарды жасау және өзгерту үшін HTTPS немесе localhost қажет.",
    loading: "Аккаунттар жүктелуде…",
    loadFailed: "Аккаунттар тізілімі қолжетімсіз",
    empty: "Сауда аккаунттары әлі тіркелмеген.",
    createTitle: "Сауда аккаунтын қосу",
    label: "Аккаунт атауы",
    exchange: "Биржа",
    ownership: "Тиесілігі",
    own: "Өзімдікі",
    managed: "Басқарудағы",
    enabled: "Қосылған",
    create: "Аккаунт қосу",
    creating: "Қосылуда…",
    edit: "Өзгерту",
    save: "Өзгерістерді сақтау",
    cancel: "Бас тарту",
    enable: "Қосу",
    disable: "Өшіру",
    delete: "Жою",
    status: "Күйі",
    ready: "Live орындауға дайын",
    credentialsMissing: "Кілттер бапталмаған",
    disabled: "Өшірілген",
    accountId: "Аккаунт ID",
    robots: "Байланған роботтар",
    none: "Жоқ",
    accountCredentials: "Аккаунт кілттері",
    configuredCredentials: "Бапталған",
    missingCredentials: "Бапталмаған",
    apiKey: "API key",
    apiSecret: "API secret",
    setCredentials: "Кілттерді орнату",
    rotateCredentials: "Кілттерді ауыстыру",
    savingCredentials: "Сақталуда…",
    deleteCredentials: "Кілттерді жою",
    credentialsHint: "Екі мән де қорғалған сессия арқылы жіберіліп, осы аккаунт үшін шифрланған түрде сақталады. Олар браузерге ешқашан қайтарылмайды.",
    credentialsSaved: "Аккаунт кілттері сақталды.",
    credentialsRotated: "Аккаунт кілттері ауыстырылды.",
    credentialsDeleted: "Аккаунт кілттері жойылды.",
    credentialsDeleteConfirm: "Осы аккаунттың биржа кілттерін жою керек пе? Жаңа кілттер орнатылғанша live орындау қолжетімсіз болады.",
    inUse: "Аккаунтқа роботтар байланған кезде оны өшіру және жою бұғатталады.",
    created: "Сауда аккаунты қосылды.",
    updated: "Сауда аккаунты жаңартылды.",
    enabledDone: "Аккаунт қосылды.",
    disabledDone: "Аккаунт өшірілді.",
    deleted: "Сауда аккаунты жойылды.",
    operationFailed: "Аккаунт әрекеті орындалмады",
    disableConfirm: "Бұл аккаунтты өшіру керек пе? Онда жаңа роботтарды іске қосу бұғатталады.",
    deleteConfirm: "Бұл сауда аккаунтын жою керек пе? Әрекетті қайтару мүмкін емес."
  }
} as const;

export type AccountRegistryTextKey = keyof typeof messages.en;

export function accountRegistryText(locale: Locale, key: AccountRegistryTextKey): string {
  return messages[locale][key];
}
