import { localized, type Locale } from "../i18n";

const en = {
  title: "Account economics evidence",
  description: "Protected, read-only fee, borrow, transfer-network and stablecoin FX evidence. It never enables execution and never returns API keys.",
  symbols: "Native symbols (max 2)",
  assets: "Assets (max 4)",
  stableAssets: "Stable assets vs USDT (max 3)",
  refresh: "Refresh evidence",
  refreshing: "Refreshing…",
  invalidQuery: "Use comma-separated uppercase exchange symbols and assets within the stated limits.",
  unavailable: "Account evidence is unavailable",
  complete: "Complete response",
  partial: "Partial response",
  validUntil: "Valid until",
  configured: "configured",
  unconfigured: "not configured",
  fresh: "fresh",
  fees: "Account fee rates",
  borrow: "Borrow capacity and current rate",
  networks: "Deposit / withdrawal networks",
  fx: "Stablecoin bid / ask",
  maker: "Maker",
  taker: "Taker",
  tier: "Tier",
  available: "Available",
  limit: "Account limit",
  annualRate: "Annualized rate",
  recallUnknown: "Recall guarantee unavailable",
  deposit: "Deposit",
  withdrawal: "Withdrawal",
  withdrawalFee: "Withdrawal fee",
  arrival: "Estimated arrival",
  minutes: "min",
  usable: "usable for research economics",
  blocked: "blocked",
  noRows: "No usable evidence returned for this section.",
  blockers: "Conservative blockers",
  nonExecutable: "Research only · executable is always false",
  timestampVenue: "venue time",
  timestampReceive: "local receive time"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  title: "Экономика текущего аккаунта",
  description: "Защищённые данные только для чтения: комиссии, доступный займ, сети перевода и курс стейблкоинов. Они не включают исполнение и не возвращают API-ключи.",
  symbols: "Нативные символы (не более 2)",
  assets: "Активы (не более 4)",
  stableAssets: "Стейблкоины к USDT (не более 3)",
  refresh: "Обновить данные",
  refreshing: "Обновление…",
  invalidQuery: "Введите биржевые символы и активы через запятую в верхнем регистре, соблюдая лимиты.",
  unavailable: "Данные аккаунта недоступны",
  complete: "Полный ответ",
  partial: "Частичный ответ",
  validUntil: "Действительно до",
  configured: "настроено",
  unconfigured: "не настроено",
  fresh: "свежее",
  fees: "Комиссии аккаунта",
  borrow: "Доступный займ и текущая ставка",
  networks: "Сети ввода / вывода",
  fx: "Bid / ask стейблкоина",
  maker: "Maker",
  taker: "Taker",
  tier: "Уровень",
  available: "Доступно",
  limit: "Лимит аккаунта",
  annualRate: "Годовая ставка",
  recallUnknown: "Гарантия отсутствия отзыва не подтверждена",
  deposit: "Ввод",
  withdrawal: "Вывод",
  withdrawalFee: "Комиссия вывода",
  arrival: "Ожидаемое время",
  minutes: "мин",
  usable: "можно использовать в исследовательской экономике",
  blocked: "заблокировано",
  noRows: "Для этого раздела пригодные данные не получены.",
  blockers: "Консервативные ограничения",
  nonExecutable: "Только исследование · executable всегда false",
  timestampVenue: "время биржи",
  timestampReceive: "локальное время получения"
};

const kk: Record<Key, string> = {
  title: "Ағымдағы аккаунт экономикасы",
  description: "Қорғалған тек оқуға арналған деректер: комиссиялар, қолжетімді қарыз, аудару желілері және стейблкоин бағамы. Олар орындауды қоспайды және API кілттерін қайтармайды.",
  symbols: "Нативті символдар (ең көбі 2)",
  assets: "Активтер (ең көбі 4)",
  stableAssets: "USDT-ге қарсы стейбл активтер (ең көбі 3)",
  refresh: "Деректерді жаңарту",
  refreshing: "Жаңартылуда…",
  invalidQuery: "Биржа символдары мен активтерді үтір арқылы бас әріппен, көрсетілген шекте енгізіңіз.",
  unavailable: "Аккаунт деректері қолжетімсіз",
  complete: "Толық жауап",
  partial: "Жартылай жауап",
  validUntil: "Жарамды уақыты",
  configured: "бапталған",
  unconfigured: "бапталмаған",
  fresh: "жаңа",
  fees: "Аккаунт комиссиялары",
  borrow: "Қарыз лимиті және ағымдағы мөлшерлеме",
  networks: "Депозит / шығару желілері",
  fx: "Стейблкоин bid / ask",
  maker: "Maker",
  taker: "Taker",
  tier: "Деңгей",
  available: "Қолжетімді",
  limit: "Аккаунт лимиті",
  annualRate: "Жылдық мөлшерлеме",
  recallUnknown: "Қарызды кері шақырмау кепілі расталмаған",
  deposit: "Депозит",
  withdrawal: "Шығару",
  withdrawalFee: "Шығару комиссиясы",
  arrival: "Болжамды уақыт",
  minutes: "мин",
  usable: "зерттеу экономикасында қолдануға болады",
  blocked: "бұғатталған",
  noRows: "Бұл бөлім үшін жарамды дерек алынбады.",
  blockers: "Консервативті шектеулер",
  nonExecutable: "Тек зерттеу · executable әрқашан false",
  timestampVenue: "биржа уақыты",
  timestampReceive: "жергілікті қабылдау уақыты"
};

export function accountTelemetryText(locale: Locale, key: Key): string {
  return localized(locale, { en, ru, kk })[key];
}
