import type { Locale } from "../i18n";

const en = {
  title: "Market opportunity",
  description: "Research evidence transferred from the screener. Reviewing it does not place orders.",
  researchOnly: "Research only",
  liveBlocked: "Live execution blocked",
  source: "Source",
  evaluated: "Evaluated",
  expires: "Handoff expires",
  active: "Active",
  expired: "Expired",
  family: "Family",
  economics: "Economics",
  outcome: "Outcome type",
  projected: "Projected economics",
  researchSimulation: "Research simulation",
  twoSidedQuote: "Two-sided quote",
  grossEdge: "Gross edge",
  quoteWidth: "Quote width",
  twoSidedQuoteHint: "A positive quote width is a bid/ask cost, not a profit edge or detected inefficiency.",
  netEdge: "Net edge",
  expectedProfit: "Expected net profit",
  entryFees: "Numeric entry fees",
  aggregateCosts: "Aggregate estimated costs",
  nativeBid: "Native bid",
  nativeAsk: "Native ask",
  absoluteWidth: "Absolute quote width",
  capacity: "Visible capacity",
  costCoverage: "Cost coverage",
  funding: "Funding",
  borrowing: "Borrowing",
  slippage: "Slippage",
  basisScenario: "Basis cost scenario",
  scenarioAssumptions: "Assumptions",
  scenarioCosts: "Cost breakdown",
  scenarioModel: "Model",
  scenarioComputed: "Computed",
  requestedNotional: "Requested notional",
  executableNotional: "Executable notional",
  spotTaker: "Spot taker fee",
  perpetualTaker: "Perpetual taker fee",
  slippageReserve: "Round-trip slippage reserve",
  holdingPeriod: "Expected holding period",
  borrowRate: "Annual borrow rate",
  transferCost: "Transfer cost",
  tradingFees: "Trading fees",
  borrowCost: "Borrow cost",
  fundingCost: "Funding cost",
  totalCost: "Total estimated cost",
  fundingSettlements: "Funding settlements",
  fundingSchedule: "Funding schedule verified",
  yes: "Yes",
  no: "No",
  evidence: "Data evidence",
  quoteAge: "Quote age",
  legSkew: "Leg skew",
  sequence: "Sequence continuity",
  timestamps: "Exchange timestamps",
  quality: "Data quality",
  legs: "Opportunity legs",
  leg: "Leg",
  venue: "Venue",
  instrument: "Instrument",
  market: "Market",
  side: "Side",
  quantity: "Quantity",
  referencePrice: "Reference price",
  execution: "Execution boundary",
  mode: "Mode",
  state: "State",
  research: "Research",
  paper: "Paper plan",
  live: "Live",
  available: "Available",
  ready: "Ready",
  blocked: "Blocked",
  unsupported: "Unsupported",
  blockers: "Why execution is blocked",
  noBlockers: "No additional research blockers were reported.",
  openPaper: "Open paper journal",
  paperHintReady: "The envelope is eligible for paper research, but an exact short-lived paper-multi-leg plan is still required before submission.",
  paperHintBlocked: "This opportunity cannot be submitted to the paper multi-leg engine yet.",
  paperHintExpired: "This handoff expired. Return to the Screener and transfer a freshly evaluated opportunity.",
  expiredBlocker: "The short-lived Screener handoff has expired; its evidence cannot be used for paper research.",
  clear: "Clear opportunity",
  unknown: "Not available",
  derived: "Derived after choosing the native spread action"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  title: "Рыночная возможность",
  description: "Исследовательские данные переданы из скринера. Просмотр не отправляет ордера.",
  researchOnly: "Только исследование",
  liveBlocked: "Live-исполнение заблокировано",
  source: "Источник",
  evaluated: "Рассчитано",
  expires: "Срок передачи",
  active: "Действует",
  expired: "Истекло",
  family: "Семейство",
  economics: "Экономика",
  outcome: "Тип результата",
  projected: "Проекционная экономика",
  researchSimulation: "Исследовательская симуляция",
  twoSidedQuote: "Двусторонняя котировка",
  grossEdge: "Валовой edge",
  quoteWidth: "Ширина котировки",
  twoSidedQuoteHint: "Положительная ширина котировки — это издержка bid/ask, а не прибыльный edge или выявленная неэффективность.",
  netEdge: "Чистый edge",
  expectedProfit: "Ожидаемая чистая прибыль",
  entryFees: "Числовые комиссии входа",
  aggregateCosts: "Совокупные оценочные издержки",
  nativeBid: "Нативный bid",
  nativeAsk: "Нативный ask",
  absoluteWidth: "Абсолютная ширина котировки",
  capacity: "Видимая ёмкость",
  costCoverage: "Учёт издержек",
  funding: "Фандинг",
  borrowing: "Заимствования",
  slippage: "Проскальзывание",
  basisScenario: "Сценарий издержек basis",
  scenarioAssumptions: "Допущения",
  scenarioCosts: "Разбивка издержек",
  scenarioModel: "Модель",
  scenarioComputed: "Рассчитано",
  requestedNotional: "Запрошенный нотионал",
  executableNotional: "Исполнимый нотионал",
  spotTaker: "Taker-комиссия спота",
  perpetualTaker: "Taker-комиссия perpetual",
  slippageReserve: "Резерв проскальзывания round-trip",
  holdingPeriod: "Ожидаемый срок удержания",
  borrowRate: "Годовая ставка займа",
  transferCost: "Стоимость перевода",
  tradingFees: "Торговые комиссии",
  borrowCost: "Стоимость займа",
  fundingCost: "Стоимость funding",
  totalCost: "Всего оценочных издержек",
  fundingSettlements: "Расчёты funding",
  fundingSchedule: "Расписание funding подтверждено",
  yes: "Да",
  no: "Нет",
  evidence: "Качество данных",
  quoteAge: "Возраст котировки",
  legSkew: "Разброс времени ног",
  sequence: "Непрерывность последовательности",
  timestamps: "Биржевые метки времени",
  quality: "Статус данных",
  legs: "Ноги возможности",
  leg: "Нога",
  venue: "Площадка",
  instrument: "Инструмент",
  market: "Рынок",
  side: "Сторона",
  quantity: "Количество",
  referencePrice: "Опорная цена",
  execution: "Граница исполнения",
  mode: "Режим",
  state: "Статус",
  research: "Исследование",
  paper: "Paper-план",
  live: "Live",
  available: "Доступно",
  ready: "Готово",
  blocked: "Заблокировано",
  unsupported: "Не поддерживается",
  blockers: "Почему исполнение заблокировано",
  noBlockers: "Дополнительных исследовательских блокировок не указано.",
  openPaper: "Открыть paper-журнал",
  paperHintReady: "Карточка допущена к paper-исследованию, но перед отправкой всё равно нужен точный краткоживущий paper-multi-leg план.",
  paperHintBlocked: "Эту возможность пока нельзя передать в multi-leg paper-движок.",
  paperHintExpired: "Срок передачи истёк. Вернитесь в Скринер и передайте заново рассчитанную возможность.",
  expiredBlocker: "Краткоживущая передача из Скринера истекла; её данные нельзя использовать для paper-исследования.",
  clear: "Очистить возможность",
  unknown: "Недоступно",
  derived: "Определится после выбора действия native spread"
};

const kk: Record<Key, string> = {
  title: "Нарық мүмкіндігі",
  description: "Зерттеу деректері скринерден берілді. Қарау order жібермейді.",
  researchOnly: "Тек зерттеу",
  liveBlocked: "Live орындау бұғатталған",
  source: "Дереккөз",
  evaluated: "Есептелді",
  expires: "Беру мерзімі",
  active: "Белсенді",
  expired: "Мерзімі өтті",
  family: "Топ",
  economics: "Экономика",
  outcome: "Нәтиже түрі",
  projected: "Болжамды экономика",
  researchSimulation: "Зерттеу симуляциясы",
  twoSidedQuote: "Екі жақты котировка",
  grossEdge: "Жалпы edge",
  quoteWidth: "Котировка ені",
  twoSidedQuoteHint: "Оң котировка ені — bid/ask шығыны; ол пайда edge-і немесе анықталған тиімсіздік емес.",
  netEdge: "Таза edge",
  expectedProfit: "Күтілетін таза пайда",
  entryFees: "Кіру комиссияларының сандық мәні",
  aggregateCosts: "Жиынтық бағаланған шығындар",
  nativeBid: "Нативті bid",
  nativeAsk: "Нативті ask",
  absoluteWidth: "Котировканың абсолют ені",
  capacity: "Көрінетін сыйымдылық",
  costCoverage: "Шығындарды есепке алу",
  funding: "Фандинг",
  borrowing: "Қарыз алу",
  slippage: "Сырғу",
  basisScenario: "Basis шығындарының сценарийі",
  scenarioAssumptions: "Болжамдар",
  scenarioCosts: "Шығындар бөлінісі",
  scenarioModel: "Модель",
  scenarioComputed: "Есептелді",
  requestedNotional: "Сұралған нотионал",
  executableNotional: "Орындалатын нотионал",
  spotTaker: "Spot taker комиссиясы",
  perpetualTaker: "Perpetual taker комиссиясы",
  slippageReserve: "Round-trip сырғу резерві",
  holdingPeriod: "Күтілетін ұстау мерзімі",
  borrowRate: "Жылдық қарыз мөлшерлемесі",
  transferCost: "Аудару құны",
  tradingFees: "Сауда комиссиялары",
  borrowCost: "Қарыз құны",
  fundingCost: "Funding құны",
  totalCost: "Жалпы бағаланған шығын",
  fundingSettlements: "Funding есеп айырысулары",
  fundingSchedule: "Funding кестесі расталған",
  yes: "Иә",
  no: "Жоқ",
  evidence: "Дерек сапасы",
  quoteAge: "Баға жасы",
  legSkew: "Аяқ уақыттарының айырмасы",
  sequence: "Реттілік тұтастығы",
  timestamps: "Биржа уақыт белгілері",
  quality: "Дерек күйі",
  legs: "Мүмкіндік аяқтары",
  leg: "Аяқ",
  venue: "Алаң",
  instrument: "Құрал",
  market: "Нарық",
  side: "Бағыт",
  quantity: "Саны",
  referencePrice: "Тірек баға",
  execution: "Орындау шекарасы",
  mode: "Режим",
  state: "Күйі",
  research: "Зерттеу",
  paper: "Paper жоспары",
  live: "Live",
  available: "Қолжетімді",
  ready: "Дайын",
  blocked: "Бұғатталған",
  unsupported: "Қолдау жоқ",
  blockers: "Орындау неге бұғатталған",
  noBlockers: "Қосымша зерттеу шектеулері берілмеді.",
  openPaper: "Paper журналын ашу",
  paperHintReady: "Карточка paper зерттеуіне жарамды, бірақ жіберу үшін нақты қысқа мерзімді paper-multi-leg жоспар әлі де қажет.",
  paperHintBlocked: "Бұл мүмкіндікті multi-leg paper қозғалтқышына әзірге жіберуге болмайды.",
  paperHintExpired: "Беру мерзімі өтті. Скринерге оралып, жаңадан есептелген мүмкіндікті қайта жіберіңіз.",
  expiredBlocker: "Скринерден қысқа мерзімді беру аяқталды; оның деректерін paper зерттеуінде пайдалануға болмайды.",
  clear: "Мүмкіндікті тазарту",
  unknown: "Қолжетімсіз",
  derived: "Native spread әрекеті таңдалғаннан кейін анықталады"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function opportunityResearchText(locale: Locale, key: Key): string {
  return messages[locale][key];
}
