import { localized, type Locale } from "../i18n";
import type { PaperMultiLegStatus } from "./paperMultiLegTypes";

const en = {
  sidebar: "Multi-leg paper journal",
  title: "Multi-leg paper journal",
  description: "Run an already validated N-leg or route-family research plan through deterministic sequential fills and inspect every recovery event.",
  paperOnly: "Paper only · no live orders · no private exchange requests · credentials are rejected",
  recovery: "Restart recovery",
  recoveryReady: "Ready",
  recoveryRunning: "Recovery in progress",
  recoveryFailed: "Recovery failed",
  recoveryNotRun: "Not started",
  recoveredRuns: "Recovered runs",
  completedAt: "Completed",
  refresh: "Refresh journal",
  refreshing: "Refreshing…",
  formLegend: "Validated research plan",
  planLabel: "Validated paper plan JSON",
  planHint: "Paste the exact short-lived plan produced by the N-leg or route-family research engine. Maximum 64 KB; do not paste API keys or secrets.",
  idempotencyLabel: "Idempotency key",
  idempotencyHint: "Keep this key when retrying the same plan. A reused key cannot be attached to a different plan.",
  submit: "Run paper scenario",
  submitting: "Running paper scenario…",
  invalidPlan: "The paper plan is invalid",
  loadFailed: "The paper journal could not be loaded",
  submitFailed: "The paper scenario could not be submitted",
  created: "Paper run created and journaled",
  reused: "Existing paper run returned for this idempotency key",
  history: "Recent paper runs",
  historyCaption: "Recent deterministic multi-leg paper runs",
  noRuns: "No paper runs have been journaled yet.",
  runId: "Run ID",
  status: "Status",
  source: "Source",
  legs: "Legs",
  updated: "Updated",
  action: "Action",
  view: "View journal",
  loadingRun: "Loading run…",
  journal: "Event journal",
  journalCaption: "Append-only events for the selected paper run",
  sequence: "Sequence",
  time: "Time",
  event: "Event",
  details: "Details",
  noSelection: "Choose a run to inspect its append-only event journal.",
  originalFill: "Original fill",
  compensationFill: "Compensation fill",
  decision: "Compensation decision",
  terminal: "Terminal state",
  runCreated: "Run created",
  quantity: "filled",
  targets: "targets",
  unresolved: "unresolved exposures",
  stateExecuting: "Executing",
  stateAwaiting: "Awaiting compensation decision",
  stateCompensating: "Compensating",
  stateCompleted: "Completed",
  stateCompensated: "Compensated",
  stateAborted: "Aborted — no exposure",
  stateManual: "Manual review required"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  sidebar: "Журнал multi-leg paper",
  title: "Журнал multi-leg paper",
  description: "Запустите уже проверенный N-leg или route-family исследовательский план с детерминированным последовательным исполнением и изучите каждое событие восстановления.",
  paperOnly: "Только paper · без реальных ордеров · без приватных запросов к биржам · учётные данные отклоняются",
  recovery: "Восстановление после перезапуска",
  recoveryReady: "Готово",
  recoveryRunning: "Идёт восстановление",
  recoveryFailed: "Восстановление не удалось",
  recoveryNotRun: "Не запускалось",
  recoveredRuns: "Восстановлено прогонов",
  completedAt: "Завершено",
  refresh: "Обновить журнал",
  refreshing: "Обновление…",
  formLegend: "Проверенный исследовательский план",
  planLabel: "JSON проверенного paper-плана",
  planHint: "Вставьте точный краткоживущий план из N-leg или route-family исследовательского движка. Не более 64 КБ; не вставляйте API-ключи и секреты.",
  idempotencyLabel: "Ключ идемпотентности",
  idempotencyHint: "Сохраняйте этот ключ при повторе того же плана. Один ключ нельзя связать с другим планом.",
  submit: "Запустить paper-сценарий",
  submitting: "Запуск paper-сценария…",
  invalidPlan: "Paper-план недействителен",
  loadFailed: "Не удалось загрузить paper-журнал",
  submitFailed: "Не удалось отправить paper-сценарий",
  created: "Paper-прогон создан и записан в журнал",
  reused: "Для этого ключа идемпотентности возвращён существующий paper-прогон",
  history: "Недавние paper-прогоны",
  historyCaption: "Недавние детерминированные multi-leg paper-прогоны",
  noRuns: "Paper-прогонов в журнале пока нет.",
  runId: "ID прогона",
  status: "Статус",
  source: "Источник",
  legs: "Ноги",
  updated: "Обновлено",
  action: "Действие",
  view: "Открыть журнал",
  loadingRun: "Загрузка прогона…",
  journal: "Журнал событий",
  journalCaption: "Неизменяемые события выбранного paper-прогона",
  sequence: "Номер",
  time: "Время",
  event: "Событие",
  details: "Детали",
  noSelection: "Выберите прогон, чтобы изучить его неизменяемый журнал событий.",
  originalFill: "Исходное исполнение",
  compensationFill: "Компенсирующее исполнение",
  decision: "Решение о компенсации",
  terminal: "Конечное состояние",
  runCreated: "Прогон создан",
  quantity: "исполнено",
  targets: "цели",
  unresolved: "неустранённых экспозиций",
  stateExecuting: "Исполняется",
  stateAwaiting: "Ожидается решение о компенсации",
  stateCompensating: "Компенсация",
  stateCompleted: "Завершён",
  stateCompensated: "Компенсирован",
  stateAborted: "Остановлен — экспозиции нет",
  stateManual: "Требуется ручная проверка"
};

const kk: Record<Key, string> = {
  sidebar: "Multi-leg paper журналы",
  title: "Multi-leg paper журналы",
  description: "Алдын ала тексерілген N-leg немесе route-family зерттеу жоспарын детерминдік тізбекті орындалу арқылы іске қосып, қалпына келтіру оқиғаларын қараңыз.",
  paperOnly: "Тек paper · нақты ордер жоқ · биржаға жабық сұрау жоқ · тіркелгі деректері қабылданбайды",
  recovery: "Қайта іске қосқаннан кейін қалпына келтіру",
  recoveryReady: "Дайын",
  recoveryRunning: "Қалпына келтірілуде",
  recoveryFailed: "Қалпына келтіру сәтсіз",
  recoveryNotRun: "Іске қосылмаған",
  recoveredRuns: "Қалпына келген прогондар",
  completedAt: "Аяқталды",
  refresh: "Журналды жаңарту",
  refreshing: "Жаңартылуда…",
  formLegend: "Тексерілген зерттеу жоспары",
  planLabel: "Тексерілген paper-жоспардың JSON-ы",
  planHint: "N-leg немесе route-family зерттеу қозғалтқышы жасаған қысқа мерзімді жоспарды дәл енгізіңіз. Ең көбі 64 КБ; API кілттері мен құпияларды енгізбеңіз.",
  idempotencyLabel: "Идемпотенттік кілт",
  idempotencyHint: "Бір жоспарды қайталағанда осы кілтті сақтаңыз. Бір кілтті басқа жоспарға қолдануға болмайды.",
  submit: "Paper сценарийін іске қосу",
  submitting: "Paper сценарийі орындалуда…",
  invalidPlan: "Paper жоспары жарамсыз",
  loadFailed: "Paper журналын жүктеу мүмкін болмады",
  submitFailed: "Paper сценарийін жіберу мүмкін болмады",
  created: "Paper прогоны жасалып, журналға жазылды",
  reused: "Осы идемпотенттік кілт үшін бұрынғы paper прогоны қайтарылды",
  history: "Соңғы paper прогондары",
  historyCaption: "Соңғы детерминдік multi-leg paper прогондары",
  noRuns: "Журналда paper прогоны әзірге жоқ.",
  runId: "Прогон ID-і",
  status: "Күйі",
  source: "Дереккөз",
  legs: "Аяқтар",
  updated: "Жаңартылды",
  action: "Әрекет",
  view: "Журналды ашу",
  loadingRun: "Прогон жүктелуде…",
  journal: "Оқиғалар журналы",
  journalCaption: "Таңдалған paper прогонының өзгермейтін оқиғалары",
  sequence: "Реті",
  time: "Уақыт",
  event: "Оқиға",
  details: "Мәліметтер",
  noSelection: "Өзгермейтін оқиғалар журналын көру үшін прогонды таңдаңыз.",
  originalFill: "Бастапқы орындалу",
  compensationFill: "Өтемдік орындалу",
  decision: "Өтем туралы шешім",
  terminal: "Соңғы күй",
  runCreated: "Прогон жасалды",
  quantity: "орындалды",
  targets: "нысана",
  unresolved: "жабылмаған экспозиция",
  stateExecuting: "Орындалуда",
  stateAwaiting: "Өтем шешімі күтілуде",
  stateCompensating: "Өтем жасалуда",
  stateCompleted: "Аяқталды",
  stateCompensated: "Өтелді",
  stateAborted: "Тоқтатылды — экспозиция жоқ",
  stateManual: "Қолмен тексеру қажет"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function paperMultiLegText(locale: Locale, key: Key): string {
  return localized(locale, messages)[key];
}

export function paperMultiLegStatusText(locale: Locale, status: PaperMultiLegStatus): string {
  const key: Record<PaperMultiLegStatus, Key> = {
    executing: "stateExecuting",
    "awaiting-compensation-decision": "stateAwaiting",
    compensating: "stateCompensating",
    completed: "stateCompleted",
    compensated: "stateCompensated",
    "aborted-no-exposure": "stateAborted",
    "manual-review-required": "stateManual"
  };
  return paperMultiLegText(locale, key[status]);
}
