import { localized, type Locale } from "../i18n";
import type { ResearchAlertDeliveryStatus, ResearchAlertFamily } from "./researchAlertTypes";

const en = {
  sidebar: "Research alerts",
  title: "Cross-family research alerts",
  description: "Configure bounded notification policies for reviewed arbitrage candidates and inspect the durable delivery outbox.",
  safetyBadge: "Research only · execution disabled",
  safetyDetail: "This workspace cannot accept exchange credentials or submit orders. Policies only create notification intents.",
  protectedSession: "Protected operator session",
  refresh: "Refresh policies and outbox",
  refreshing: "Refreshing…",
  pollingActive: "Automatic refresh is active while this tab is visible.",
  pollingPaused: "Automatic refresh is paused while this tab is hidden.",
  loadFailed: "Research alerts could not be loaded",
  saveFailed: "The policy could not be saved",
  deleteFailed: "The policy could not be deleted",
  saved: "Research alert policy saved",
  deleted: "Research alert policy deleted",
  workerError: "Delivery worker error",
  newPolicy: "New policy",
  editPolicy: "Edit policy",
  cancelEdit: "Cancel editing",
  createLegend: "Create a bounded research policy",
  editLegend: "Edit the bounded research policy",
  filtersGroup: "Candidate filters",
  name: "Policy name",
  enabled: "Policy enabled",
  families: "Arbitrage families",
  familiesHint: "Select one or more families. No selection intentionally matches no candidates.",
  economicAssets: "Reviewed economic asset IDs",
  economicAssetsHint: "Optional comma- or line-separated canonical IDs, for example crypto:btc. Empty means every reviewed economic asset.",
  everyAsset: "Every reviewed asset",
  economicsGroup: "Conservative economics and capacity",
  minimumProfit: "Minimum conservative net profit",
  minimumEdge: "Minimum net edge (bps)",
  minimumCapacity: "Minimum executable capacity (valuation asset)",
  maximumCapital: "Maximum risk capital (valuation asset)",
  maximumCapitalHint: "Optional. Leave empty when the policy does not impose a capital ceiling.",
  evidenceGroup: "Evidence freshness",
  minimumQuality: "Minimum evidence quality",
  fresh: "Fresh",
  verified: "Verified",
  observationAge: "Maximum observation age (ms)",
  economicsAge: "Maximum economics age (ms)",
  identityAge: "Maximum reviewed identity age (ms)",
  deliveryGroup: "Delivery deduplication",
  cooldown: "Cooldown (seconds)",
  create: "Create research policy",
  save: "Save policy changes",
  saving: "Saving…",
  validationError: "Review the bounded policy fields",
  policies: "Policies",
  policiesCaption: "Bounded cross-family research alert policies",
  noPolicies: "No research alert policies have been created.",
  state: "State",
  active: "Enabled",
  inactive: "Disabled",
  filters: "Filters",
  economics: "Economics",
  freshness: "Freshness",
  cooldownShort: "Cooldown",
  lastDelivery: "Last delivery",
  updated: "Updated",
  actions: "Actions",
  edit: "Edit",
  delete: "Delete",
  confirmDelete: "Confirm deletion",
  cancelDelete: "Keep policy",
  outbox: "Delivery outbox",
  outboxCaption: "Recent durable research-only notification deliveries",
  noDeliveries: "The research alert outbox is empty.",
  route: "Route",
  family: "Family",
  asset: "Economic asset",
  result: "Conservative result",
  delivery: "Delivery",
  attempts: "Attempts",
  queued: "Queued",
  nextAttempt: "Next attempt",
  delivered: "Delivered",
  error: "Error",
  noError: "No delivery error",
  researchOnly: "Research only",
  executionDenied: "No execution permission",
  profit: "profit",
  edge: "edge",
  capacity: "capacity",
  riskCapital: "risk capital",
  maxObservation: "observation",
  maxEconomics: "economics",
  maxIdentity: "identity",
  notAvailable: "—"
} as const;

type Key = keyof typeof en;

const ru: Record<Key, string> = {
  sidebar: "Исследовательские алерты",
  title: "Исследовательские алерты для всех семейств",
  description: "Настройте ограниченные политики уведомлений для проверенных арбитражных кандидатов и контролируйте надёжный outbox доставки.",
  safetyBadge: "Только исследование · исполнение отключено",
  safetyDetail: "Этот раздел не принимает учётные данные бирж и не выставляет ордера. Политики создают только намерения уведомлений.",
  protectedSession: "Защищённая операторская сессия",
  refresh: "Обновить политики и outbox",
  refreshing: "Обновление…",
  pollingActive: "Автообновление активно, пока вкладка видима.",
  pollingPaused: "Автообновление приостановлено, пока вкладка скрыта.",
  loadFailed: "Не удалось загрузить исследовательские алерты",
  saveFailed: "Не удалось сохранить политику",
  deleteFailed: "Не удалось удалить политику",
  saved: "Политика исследовательских алертов сохранена",
  deleted: "Политика исследовательских алертов удалена",
  workerError: "Ошибка воркера доставки",
  newPolicy: "Новая политика",
  editPolicy: "Изменить политику",
  cancelEdit: "Отменить редактирование",
  createLegend: "Создать ограниченную исследовательскую политику",
  editLegend: "Изменить ограниченную исследовательскую политику",
  filtersGroup: "Фильтры кандидатов",
  name: "Название политики",
  enabled: "Политика включена",
  families: "Семейства арбитража",
  familiesHint: "Выберите одно или несколько семейств. Пустой выбор намеренно не соответствует ни одному кандидату.",
  economicAssets: "Проверенные ID экономических активов",
  economicAssetsHint: "Необязательные канонические ID через запятую или с новой строки, например crypto:btc. Пусто — все проверенные активы.",
  everyAsset: "Все проверенные активы",
  economicsGroup: "Консервативная экономика и ёмкость",
  minimumProfit: "Минимальная консервативная чистая прибыль",
  minimumEdge: "Минимальное чистое преимущество (б.п.)",
  minimumCapacity: "Минимальная исполнимая ёмкость (актив оценки)",
  maximumCapital: "Максимальный рисковый капитал (актив оценки)",
  maximumCapitalHint: "Необязательно. Оставьте пустым, если политика не ограничивает капитал сверху.",
  evidenceGroup: "Свежесть доказательств",
  minimumQuality: "Минимальное качество доказательств",
  fresh: "Свежие",
  verified: "Проверенные",
  observationAge: "Максимальный возраст наблюдения (мс)",
  economicsAge: "Максимальный возраст экономики (мс)",
  identityAge: "Максимальный возраст проверенной идентичности (мс)",
  deliveryGroup: "Дедупликация доставки",
  cooldown: "Пауза между уведомлениями (секунды)",
  create: "Создать исследовательскую политику",
  save: "Сохранить изменения",
  saving: "Сохранение…",
  validationError: "Проверьте ограниченные поля политики",
  policies: "Политики",
  policiesCaption: "Ограниченные политики исследовательских алертов для всех семейств",
  noPolicies: "Исследовательские политики ещё не созданы.",
  state: "Состояние",
  active: "Включена",
  inactive: "Отключена",
  filters: "Фильтры",
  economics: "Экономика",
  freshness: "Свежесть",
  cooldownShort: "Пауза",
  lastDelivery: "Последняя доставка",
  updated: "Обновлено",
  actions: "Действия",
  edit: "Изменить",
  delete: "Удалить",
  confirmDelete: "Подтвердить удаление",
  cancelDelete: "Оставить политику",
  outbox: "Outbox доставки",
  outboxCaption: "Недавние надёжные доставки исследовательских уведомлений",
  noDeliveries: "Outbox исследовательских алертов пуст.",
  route: "Маршрут",
  family: "Семейство",
  asset: "Экономический актив",
  result: "Консервативный результат",
  delivery: "Доставка",
  attempts: "Попытки",
  queued: "Поставлено в очередь",
  nextAttempt: "Следующая попытка",
  delivered: "Доставлено",
  error: "Ошибка",
  noError: "Ошибки доставки нет",
  researchOnly: "Только исследование",
  executionDenied: "Нет разрешения на исполнение",
  profit: "прибыль",
  edge: "преимущество",
  capacity: "ёмкость",
  riskCapital: "рисковый капитал",
  maxObservation: "наблюдение",
  maxEconomics: "экономика",
  maxIdentity: "идентичность",
  notAvailable: "—"
};

const kk: Record<Key, string> = {
  sidebar: "Зерттеу алерттері",
  title: "Барлық отбасыларға арналған зерттеу алерттері",
  description: "Тексерілген арбитраж үміткерлеріне шектеулі хабарландыру саясаттарын баптап, сенімді жеткізу outbox-ын бақылаңыз.",
  safetyBadge: "Тек зерттеу · орындау өшірулі",
  safetyDetail: "Бұл жұмыс кеңістігі биржа тіркелгі деректерін қабылдамайды және ордер жібермейді. Саясаттар тек хабарландыру ниетін жасайды.",
  protectedSession: "Қорғалған оператор сессиясы",
  refresh: "Саясаттар мен outbox-ты жаңарту",
  refreshing: "Жаңартылуда…",
  pollingActive: "Қойынды көрініп тұрғанда автоматты жаңарту белсенді.",
  pollingPaused: "Қойынды жасырылғанда автоматты жаңарту тоқтатылды.",
  loadFailed: "Зерттеу алерттерін жүктеу мүмкін болмады",
  saveFailed: "Саясатты сақтау мүмкін болмады",
  deleteFailed: "Саясатты жою мүмкін болмады",
  saved: "Зерттеу алертінің саясаты сақталды",
  deleted: "Зерттеу алертінің саясаты жойылды",
  workerError: "Жеткізу воркерінің қатесі",
  newPolicy: "Жаңа саясат",
  editPolicy: "Саясатты өзгерту",
  cancelEdit: "Өзгертуді тоқтату",
  createLegend: "Шектеулі зерттеу саясатын жасау",
  editLegend: "Шектеулі зерттеу саясатын өзгерту",
  filtersGroup: "Үміткер сүзгілері",
  name: "Саясат атауы",
  enabled: "Саясат қосулы",
  families: "Арбитраж отбасылары",
  familiesHint: "Бір немесе бірнеше отбасын таңдаңыз. Бос таңдау әдейі ешбір үміткерге сәйкес келмейді.",
  economicAssets: "Тексерілген экономикалық актив ID-лері",
  economicAssetsHint: "Үтірмен не жаңа жолмен бөлінген міндетті емес канондық ID, мысалы crypto:btc. Бос болса — барлық тексерілген актив.",
  everyAsset: "Барлық тексерілген актив",
  economicsGroup: "Консервативті экономика және сыйымдылық",
  minimumProfit: "Ең аз консервативті таза пайда",
  minimumEdge: "Ең аз таза артықшылық (б.п.)",
  minimumCapacity: "Ең аз орындалатын сыйымдылық (бағалау активі)",
  maximumCapital: "Ең көп тәуекел капиталы (бағалау активі)",
  maximumCapitalHint: "Міндетті емес. Саясат капиталға жоғарғы шек қоймаса, бос қалдырыңыз.",
  evidenceGroup: "Дәлелдердің өзектілігі",
  minimumQuality: "Дәлелдің ең төмен сапасы",
  fresh: "Өзекті",
  verified: "Тексерілген",
  observationAge: "Бақылаудың ең үлкен жасы (мс)",
  economicsAge: "Экономиканың ең үлкен жасы (мс)",
  identityAge: "Тексерілген сәйкестіктің ең үлкен жасы (мс)",
  deliveryGroup: "Жеткізуді дедупликациялау",
  cooldown: "Хабарландырулар аралығы (секунд)",
  create: "Зерттеу саясатын жасау",
  save: "Өзгерістерді сақтау",
  saving: "Сақталуда…",
  validationError: "Саясаттың шектеулі өрістерін тексеріңіз",
  policies: "Саясаттар",
  policiesCaption: "Барлық отбасыларға арналған шектеулі зерттеу алерт саясаттары",
  noPolicies: "Зерттеу алертінің саясаты әлі жасалмаған.",
  state: "Күйі",
  active: "Қосулы",
  inactive: "Өшірулі",
  filters: "Сүзгілер",
  economics: "Экономика",
  freshness: "Өзектілік",
  cooldownShort: "Аралық",
  lastDelivery: "Соңғы жеткізу",
  updated: "Жаңартылды",
  actions: "Әрекеттер",
  edit: "Өзгерту",
  delete: "Жою",
  confirmDelete: "Жоюды растау",
  cancelDelete: "Саясатты сақтау",
  outbox: "Жеткізу outbox-ы",
  outboxCaption: "Соңғы сенімді зерттеу хабарландыруларының жеткізілуі",
  noDeliveries: "Зерттеу алерттерінің outbox-ы бос.",
  route: "Бағыт",
  family: "Отбасы",
  asset: "Экономикалық актив",
  result: "Консервативті нәтиже",
  delivery: "Жеткізу",
  attempts: "Әрекеттер саны",
  queued: "Кезекке қойылды",
  nextAttempt: "Келесі әрекет",
  delivered: "Жеткізілді",
  error: "Қате",
  noError: "Жеткізу қатесі жоқ",
  researchOnly: "Тек зерттеу",
  executionDenied: "Орындауға рұқсат жоқ",
  profit: "пайда",
  edge: "артықшылық",
  capacity: "сыйымдылық",
  riskCapital: "тәуекел капиталы",
  maxObservation: "бақылау",
  maxEconomics: "экономика",
  maxIdentity: "сәйкестік",
  notAvailable: "—"
};

const messages: Record<Locale, Record<Key, string>> = { en, ru, kk };

export function researchAlertText(locale: Locale, key: Key): string {
  return localized(locale, messages)[key];
}

export function researchAlertFamilyText(_locale: Locale, family: ResearchAlertFamily): string {
  const labels: Record<ResearchAlertFamily, string> = {
    basis: "Basis",
    "cross-venue-spot-spot": "Cross-venue spot/spot",
    "reverse-cash-and-carry": "Reverse cash-and-carry",
    "perpetual-perpetual-funding": "Perpetual/perpetual funding",
    "spot-dated-future": "Spot/dated future",
    "calendar-spread": "Calendar spread",
    "perpetual-future": "Perpetual/future",
    triangular: "Triangular",
    "native-spread": "Native spread",
    "options-parity": "Options parity",
    "n-leg": "N-leg",
    "cex-dex": "CEX/DEX"
  };
  return labels[family];
}

export function researchAlertDeliveryStatusText(locale: Locale, status: ResearchAlertDeliveryStatus): string {
  const labels: Record<Locale, Record<ResearchAlertDeliveryStatus, string>> = {
    en: { queued: "Queued", sending: "Sending", retrying: "Retrying", delivered: "Delivered", failed: "Failed", cancelled: "Cancelled" },
    ru: { queued: "В очереди", sending: "Отправляется", retrying: "Повтор", delivered: "Доставлено", failed: "Ошибка", cancelled: "Отменено" },
    kk: { queued: "Кезекте", sending: "Жіберілуде", retrying: "Қайталануда", delivered: "Жеткізілді", failed: "Сәтсіз", cancelled: "Тоқтатылды" }
  };
  return labels[locale][status];
}
